import {
  CarsharingStatuses,
  GroupTransferStatuses,
  PersonalStatuses,
  PublicStatuses,
  TaxiStatuses,
  CarsharingStatusNames,
  GroupTransferStatusNames,
  PersonalStatusNames,
  PublicStatusNames,
  TaxiStatusNames
} from 'constants/constants.statuses';
import type { IStatus } from '../interfaces/Orders.interface';

export const CARSHARING_STATUSES: IStatus<CarsharingStatuses>[] = [
  {
    name: CarsharingStatuses.CARSHARING_AWAITING_APPROVAL,
    rusName: CarsharingStatusNames[CarsharingStatuses.CARSHARING_AWAITING_APPROVAL],
    editable: true,
    approvable: true,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: CarsharingStatuses.CARSHARING_APPROVED,
    rusName: CarsharingStatusNames[CarsharingStatuses.CARSHARING_APPROVED],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#10BF6A',
  },
  {
    name: CarsharingStatuses.CARSHARING_DECLINED,
    rusName: CarsharingStatusNames[CarsharingStatuses.CARSHARING_DECLINED],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF5743',
  },
  {
    name: CarsharingStatuses.CARSHARING_AWAITING_SEARCH,
    rusName: CarsharingStatusNames[CarsharingStatuses.CARSHARING_AWAITING_SEARCH],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: CarsharingStatuses.CARSHARING_TRIP_IN_PROGRESS,
    rusName: CarsharingStatusNames[CarsharingStatuses.CARSHARING_TRIP_IN_PROGRESS],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: CarsharingStatuses.CARSHARING_AWAITING_TRIP_APPROVAL,
    rusName: CarsharingStatusNames[CarsharingStatuses.CARSHARING_AWAITING_TRIP_APPROVAL],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: CarsharingStatuses.CARSHARING_TRIP_FINISHED,
    rusName: CarsharingStatusNames[CarsharingStatuses.CARSHARING_TRIP_FINISHED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#10BF6A',
  },
  {
    name: CarsharingStatuses.CARSHARING_CANCELLED,
    rusName: CarsharingStatusNames[CarsharingStatuses.CARSHARING_CANCELLED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#4D4D4D',
  },
];

export const GROUP_TRANSFER_STATUSES: IStatus<GroupTransferStatuses>[] = [
  {
    name: GroupTransferStatuses.GROUP_TRANSFER_AWAITING_APPROVAL,
    rusName: GroupTransferStatusNames[GroupTransferStatuses.GROUP_TRANSFER_AWAITING_APPROVAL],
    editable: true,
    approvable: true,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: GroupTransferStatuses.GROUP_TRANSFER_APPROVED,
    rusName: GroupTransferStatusNames[GroupTransferStatuses.GROUP_TRANSFER_APPROVED],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#10BF6A',
  },
  {
    name: GroupTransferStatuses.GROUP_TRANSFER_AWAITING_SEARCH,
    rusName: GroupTransferStatusNames[GroupTransferStatuses.GROUP_TRANSFER_AWAITING_SEARCH],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: GroupTransferStatuses.GROUP_TRANSFER_DRIVER_SEARCH,
    rusName: GroupTransferStatusNames[GroupTransferStatuses.GROUP_TRANSFER_DRIVER_SEARCH],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: GroupTransferStatuses.GROUP_TRANSFER_DRIVER_FOUND,
    rusName: GroupTransferStatusNames[GroupTransferStatuses.GROUP_TRANSFER_DRIVER_FOUND],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: GroupTransferStatuses.GROUP_TRANSFER_DRIVER_ON_THE_WAY,
    rusName: GroupTransferStatusNames[GroupTransferStatuses.GROUP_TRANSFER_DRIVER_ON_THE_WAY],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: GroupTransferStatuses.GROUP_TRANSFER_DRIVER_ARRIVED,
    rusName: GroupTransferStatusNames[GroupTransferStatuses.GROUP_TRANSFER_DRIVER_ARRIVED],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: GroupTransferStatuses.GROUP_TRANSFER_TRIP_IN_PROGRESS,
    rusName: GroupTransferStatusNames[GroupTransferStatuses.GROUP_TRANSFER_TRIP_IN_PROGRESS],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: GroupTransferStatuses.GROUP_TRANSFER_TRIP_FINISHED,
    rusName: GroupTransferStatusNames[GroupTransferStatuses.GROUP_TRANSFER_TRIP_FINISHED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#10BF6A',
  },
  {
    name: GroupTransferStatuses.GROUP_TRANSFER_CANCELLED,
    rusName: GroupTransferStatusNames[GroupTransferStatuses.GROUP_TRANSFER_CANCELLED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#FF5743',
  },
];

export const PERSONAL_STATUSES: IStatus<PersonalStatuses>[] = [
  {
    name: PersonalStatuses.PERSONAL_AWAITING_APPROVAL,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_AWAITING_APPROVAL],
    editable: true,
    approvable: true,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: PersonalStatuses.PERSONAL_APPROVED,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_APPROVED],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#10BF6A',
  },
  {
    name: PersonalStatuses.PERSONAL_AWAITING_SHARED_RIDE_APPROVAL,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_AWAITING_SHARED_RIDE_APPROVAL],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: PersonalStatuses.PERSONAL_SHARED_RIDE_DECLINED,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_SHARED_RIDE_DECLINED],
    editable: true,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#FF5743',
  },
  {
    name: PersonalStatuses.PERSONAL_SHARED_RIDE_APPROVED,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_SHARED_RIDE_APPROVED],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#10BF6A',
  },
  {
    name: PersonalStatuses.PERSONAL_ADDITIONAL_WAYPOINTS_APPROVAL,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_ADDITIONAL_WAYPOINTS_APPROVAL],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: PersonalStatuses.PERSONAL_ADDITIONAL_WAYPOINTS_APPROVED,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_ADDITIONAL_WAYPOINTS_APPROVED],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#10BF6A',
  },
  {
    name: PersonalStatuses.PERSONAL_ADDITIONAL_WAYPOINTS_DECLINED,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_ADDITIONAL_WAYPOINTS_DECLINED],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: true,
    backgroundColor: '#FF5743',
  },
  {
    name: PersonalStatuses.PERSONAL_TRIP_START_REMIND,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_TRIP_START_REMIND],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: PersonalStatuses.PERSONAL_TRIP_IN_PROGRESS,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_TRIP_IN_PROGRESS],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: true,
    backgroundColor: '#6979F7',
  },
  {
    name: PersonalStatuses.PERSONAL_WAYPOINT_ARRIVED,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_WAYPOINT_ARRIVED],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: PersonalStatuses.PERSONAL_AWAITING_TRIP_APPROVAL,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_AWAITING_TRIP_APPROVAL],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: PersonalStatuses.PERSONAL_AWAITING_TRIP_APPROVED,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_AWAITING_TRIP_APPROVED],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#10BF6A',
  },
  {
    name: PersonalStatuses.PERSONAL_AWAITING_TRIP_DECLINED,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_AWAITING_TRIP_DECLINED],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: true,
    backgroundColor: '#FF5743',
  },
  {
    name: PersonalStatuses.PERSONAL_ORDER_PAYMENT_FORMATION,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_ORDER_PAYMENT_FORMATION],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: PersonalStatuses.PERSONAL_PAYMENT_AWAITING,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_PAYMENT_AWAITING],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: PersonalStatuses.PERSONAL_PAYMENT_DONE,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_PAYMENT_DONE],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#10BF6A',
  },
  {
    name: PersonalStatuses.PERSONAL_PAYMENT_DECLINED,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_PAYMENT_DECLINED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#FF5743',
  },
  {
    name: PersonalStatuses.PERSONAL_CANCELLED,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_CANCELLED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#4D4D4D',
  },
  {
    name: PersonalStatuses.PERSONAL_TRIP_FINISHED,
    rusName: PersonalStatusNames[PersonalStatuses.PERSONAL_TRIP_FINISHED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#4D4D4D',
  },
];

export const PUBLIC_STATUSES: IStatus<PublicStatuses>[] = [
  {
    name: PublicStatuses.PUBLIC_AWAITING_APPROVAL,
    rusName: PublicStatusNames[PublicStatuses.PUBLIC_AWAITING_APPROVAL],
    editable: true,
    approvable: true,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: PublicStatuses.PUBLIC_TRIP_CONFIRMATION,
    rusName: PublicStatusNames[PublicStatuses.PUBLIC_TRIP_CONFIRMATION],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: PublicStatuses.PUBLIC_AWAITING_AFFIRMATIVE,
    rusName: PublicStatusNames[PublicStatuses.PUBLIC_AWAITING_AFFIRMATIVE],
    editable: true,
    approvable: true,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: PublicStatuses.PUBLIC_ORDER_PAYMENT_FORMATION,
    rusName: PublicStatusNames[PublicStatuses.PUBLIC_ORDER_PAYMENT_FORMATION],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: PublicStatuses.PUBLIC_PAYMENT_AWAITING,
    rusName: PublicStatusNames[PublicStatuses.PUBLIC_PAYMENT_AWAITING],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: PublicStatuses.PUBLIC_PAYMENT_DONE,
    rusName: PublicStatusNames[PublicStatuses.PUBLIC_PAYMENT_DONE],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#10BF6A',
  },
  {
    name: PublicStatuses.PUBLIC_PAYMENT_NOT_DONE,
    rusName: PublicStatusNames[PublicStatuses.PUBLIC_PAYMENT_NOT_DONE],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#FF5743',
  },
  {
    name: PublicStatuses.PUBLIC_CANCELLED,
    rusName: PublicStatusNames[PublicStatuses.PUBLIC_CANCELLED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#4D4D4D',
  },
];

export const TAXI_STATUSES: IStatus<TaxiStatuses>[] = [
  {
    name: TaxiStatuses.TAXI_AWAITING_APPROVAL,
    rusName: TaxiStatusNames[TaxiStatuses.TAXI_AWAITING_APPROVAL],
    editable: true,
    approvable: true,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#FF9A32',
  },
  {
    name: TaxiStatuses.TAXI_APPROVED,
    rusName: TaxiStatusNames[TaxiStatuses.TAXI_APPROVED],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#10BF6A',
  },
  {
    name: TaxiStatuses.TAXI_AWAITING_SEARCH,
    rusName: TaxiStatusNames[TaxiStatuses.TAXI_AWAITING_SEARCH],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: TaxiStatuses.TAXI_DRIVER_SEARCH,
    rusName: TaxiStatusNames[TaxiStatuses.TAXI_DRIVER_SEARCH],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: TaxiStatuses.TAXI_DRIVER_FOUND,
    rusName: TaxiStatusNames[TaxiStatuses.TAXI_DRIVER_FOUND],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: TaxiStatuses.TAXI_DRIVER_ON_THE_WAY,
    rusName: TaxiStatusNames[TaxiStatuses.TAXI_DRIVER_ON_THE_WAY],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: TaxiStatuses.TAXI_DRIVER_ARRIVED,
    rusName: TaxiStatusNames[TaxiStatuses.TAXI_DRIVER_ARRIVED],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: TaxiStatuses.TAXI_TRIP_IN_PROGRESS,
    rusName: TaxiStatusNames[TaxiStatuses.TAXI_TRIP_IN_PROGRESS],
    editable: false,
    approvable: false,
    cancelable: true,
    finalStatus: false,
    backgroundColor: '#6979F7',
  },
  {
    name: TaxiStatuses.TAXI_TRIP_FINISHED,
    rusName: TaxiStatusNames[TaxiStatuses.TAXI_TRIP_FINISHED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#10BF6A',
  },
  {
    name: TaxiStatuses.TAXI_CANCELLED,
    rusName: TaxiStatusNames[TaxiStatuses.TAXI_CANCELLED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
    backgroundColor: '#FF5743',
  },
];

export const STATUSES = [
  ...CARSHARING_STATUSES,
  ...TAXI_STATUSES,
  ...PERSONAL_STATUSES,
  ...PUBLIC_STATUSES,
  ...GROUP_TRANSFER_STATUSES,
];
