DROP INDEX CONTRACTORS.DRIVER_CONTRACTOR_UNIQUE_INDEX;
DROP TABLE CONTRACTORS.DRIVER;

CREATE TABLE CONTRACTORS.DRIVER_USER_PROFILE
(
    ID         UUID PRIMARY KEY,
    LAST_NAME  VARCHAR(255)        NOT NULL,
    FIRST_NAME VARCHAR(255)        NOT NULL,
    PATRONYMIC VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE CONTRACTORS.DRIVER
(
    ID              UUID PRIMARY KEY,
    USER_PROFILE_ID UUID
        CONSTRAINT DRIVER_USER_PROFILE_FK REFERENCES CONTRACTORS.DRIVER_USER_PROFILE (ID),
    CONTRACTOR_ID   UUID
        CONSTRAINT DRIVER_CONTRACTOR_FK REFERENCES CONTRACTORS.CONTRACTOR (ID)
);
