package ru.sber.transport.notifications.database.model.settings.notification;

import io.swagger.v3.oas.annotations.media.Schema;

public enum NotificationType {

    APPROVE,

    APPROVE_STATUS,

    WAITING_FOR_DRIVER,

    DRIVER_ASSIGNED,

    DRIVER_ASSIGNED_DISPATCHER,

    DRIVER_ASSIGNED_XML,

    DRIVER_ARRIVED,

    FREE_TIME_EXPIRED,

    TRIP_STARTED,

    WAYPOINT_ARRIVED,

    WAYPOINT_WAITING_EXPIRED,

    TRIP_FINISHED,

    COOP_TRIP_ATTACHMENT,

    COOP_TRIP_CHANGES,

    TRIP_CONFIRM,

    TRIP_AFFIRM,

    TRIP_AFFIRM_STATUS,

    PAYMENT_STATUS,

    COOP_TRIP_ATTACHMENT_APPROVE,

    COOP_TRIP_ATTACHMENT_STATUS,

    TRIP_START_REMIND,

    FINAL_ROUTE_AFFIRM,

    FINAL_ROUTE_AFFIRM_STATUS,

    ADDITIONAL_WAYPOINTS_APPROVAL,

    ADDITIONAL_WAYPOINTS_STATUS,

    TRANSPORT_BOOKING,

    TRANSPORT_OVERVIEW,

    TRANSPORT_BOOKING_FINISHED,

    REQUEST_EXECUTION,

    ALLOCATION,

    CHANGE,

    STATUS,

    LOW_REMAINS,

    LOW_REMAINS_FROM_EMPLOYEE,

    ASSIGNMENT,

    RESTRICTIONS_EDITED_DATE,

    RESTRICTIONS_EDITED_TYPE,

    RESTRICTIONS_EDITED,

    PAYMENT,

    PUSH_DECLINED_BY_DRIVER,

    PUSH_PASSENGER_COMMUNICATION_REQUEST,

    PUSH_DRIVER_NOT_ASSIGNED,

    PUSH_DECLINED_BY_PASSENGER,

    PUSH_LOW_GRADE_TRIP,

    PUSH_INDICATION_TRIP_REQUEST,

    DECLINED_BY_DRIVER,

    PASSENGER_COMMUNICATION_REQUEST,

    DRIVER_NOT_ASSIGNED,

    DECLINED_BY_PASSENGER,

    LOW_GRADE_TRIP,

    INDICATION_TRIP_REQUEST,
    DRIVER_REJECTED_REQUEST,
    PASSENGER_LOOKING_FOR_DRIVER,
    PASSENGER_REJECTED_REQUEST,
    TRIP_WITH_LOW_RATE,
    REQUEST_WITH_INDICATION_CREATED,
    DECLINED_BY_APPROVER,
    CARGO_DRIVER_AWAITING_DATA,
    CARGO_COURIER_AWAITING_DATA,
    CARGO_SHIPMENT_FINISHED,
    CARGO_CANCELED_BY_ENGINEER,
    CARGO_CANCELED_BY_CONTRACTOR,
    CARGO_AWAITING_TRANSFER,
    CARGO_TRANSFER_FINISHED,
    CARGO_DELIVERY_CONFIRMATION_FINISHED,
    CARGO_PLANNING,
    @Schema(description = "Изменение плановых сроков исполнения")
    CARGO_CHANGE_DESIRED_DATE,

    GROUP_TRANSFER_AWAITING_APPROVAL,
    GROUP_TRANSFER_DRIVER_SEARCH,
    GROUP_TRANSFER_DRIVER_FOUND,
    GROUP_TRANSFER_DRIVER_FOUND_MZK,
    GROUP_TRANSFER_APPROVED,
    GROUP_TRANSFER_AWAITING_SEARCH,
    GROUP_TRANSFER_DRIVER_ON_THE_WAY,
    GROUP_TRANSFER_DRIVER_ARRIVED,
    GROUP_TRANSFER_TRIP_IN_PROGRESS,
    GROUP_TRANSFER_TRIP_FINISHED,
    GROUP_TRANSFER_CANCELLED,

    CUSTOM_NOTIFICATION
}
