<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.sber.transport.etrn</groupId>
    <artifactId>parent</artifactId>
    <version>5.15</version>
    <packaging>pom</packaging>

    <name>etrn-cargo</name>
    <description>Сервис электронных транспортных накладных (ЭТрН) в контуре СберТранспорт</description>
    <modules>
        <module>application</module>
    </modules>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.12</version>
    </parent>

    <properties>
        <release.version>5.15</release.version>
        <image-tag>${project.version}-${username}</image-tag>
        <transport-core.version>3.24</transport-core.version>
        <sonar.projectKey>TRANSPORT_CARGO_etrn</sonar.projectKey>
        <sonar.exclusions>
            file:**/EtrnApplication.java
            file:**/config/*,
            file:**/dto/*,
            file:**/enums/**/*
        </sonar.exclusions>
        <server.port>8000</server.port>
        <kafka.default.broker>localhost:9092,127.0.0.1:9092</kafka.default.broker>
        <maven.compiler.plugin.version>3.13.0</maven.compiler.plugin.version>
        <hibernate.jpamodelgen.jakarta.version>5.6.15.Final</hibernate.jpamodelgen.jakarta.version>
        <maven.compiler.target>21</maven.compiler.target>
        <mapstruct.version>1.6.3</mapstruct.version>
        <lombok.version>1.18.38</lombok.version>
        <versions-maven-plugin.version>2.18.0</versions-maven-plugin.version>
        <jacoco-maven-plugin.version>0.8.13</jacoco-maven-plugin.version>
        <maven-surefire-plugin.version>3.3.1</maven-surefire-plugin.version>
        <maven-jar-plugin.version>3.4.2</maven-jar-plugin.version>
        <spring-cloud-dependencies.version>2025.0.0</spring-cloud-dependencies.version>
        <embedded-postgres.version>4.10</embedded-postgres.version>
        <authorization.version>4.10</authorization.version>
        <shedlock-spring.version>6.8.0</shedlock-spring.version>
        <kafka-functional.version>4.6.0.2</kafka-functional.version>
        <awaitility.version>4.0.3</awaitility.version>
        <jib-maven-plugin.version>3.4.6</jib-maven-plugin.version>
        <role-check-starter.version>3.18</role-check-starter.version>
        <ext-logging.version>260408-1</ext-logging.version>
        <source.image>
            registry-ci.delta.sbrf.ru/dev/ci02351878/ci02353146_transport_dev/transport/open-jdk:21.0.3
        </source.image>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport</groupId>
                <artifactId>transport-core</artifactId>
                <version>${transport-core.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>io.swagger.core.v3</groupId>
                        <artifactId>swagger-annotations</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.hibernate</groupId>
                <artifactId>hibernate-jpamodelgen-jakarta</artifactId>
                <version>${hibernate.jpamodelgen.jakarta.version}</version>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport</groupId>
                <artifactId>authorization</artifactId>
                <version>${authorization.version}</version>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport</groupId>
                <artifactId>role-check-starter</artifactId>
                <version>${role-check-starter.version}</version>
            </dependency>
            <dependency>
                <groupId>net.javacrumbs.shedlock</groupId>
                <artifactId>shedlock-spring</artifactId>
                <version>${shedlock-spring.version}</version>
            </dependency>
            <dependency>
                <groupId>net.javacrumbs.shedlock</groupId>
                <artifactId>shedlock-provider-jdbc-template</artifactId>
                <version>${shedlock-spring.version}</version>
            </dependency>

            <dependency>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-java-commons</artifactId>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>ru.sber.qa</groupId>
                <artifactId>allure-annotations</artifactId>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-junit5</artifactId>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport</groupId>
                <artifactId>embedded-postgres</artifactId>
                <version>${embedded-postgres.version}</version>
                <scope>test</scope>
                <exclusions>
                    <exclusion>
                        <groupId>org.liquibase</groupId>
                        <artifactId>liquibase-core</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport</groupId>
                <artifactId>kafka-functional</artifactId>
                <version>${kafka-functional.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>io.swagger.core.v3</groupId>
                        <artifactId>swagger-annotations</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.awaitility</groupId>
                <artifactId>awaitility</artifactId>
                <version>${awaitility.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport</groupId>
                <artifactId>ext-logging</artifactId>
                <version>${ext-logging.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>io.swagger.core.v3</groupId>
                        <artifactId>swagger-annotations</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-webmvc</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-web</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <finalName>etrn-cargo</finalName>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.plugin.version}</version>
                    <configuration>
                        <release>${maven.compiler.target}</release>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.mapstruct</groupId>
                                <artifactId>mapstruct-processor</artifactId>
                                <version>${mapstruct.version}</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok-mapstruct-binding</artifactId>
                                <version>0.2.0</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                            <dependency>
                                <groupId>org.hibernate</groupId>
                                <artifactId>hibernate-jpamodelgen-jakarta</artifactId>
                                <version>${hibernate.jpamodelgen.jakarta.version}</version>
                            </dependency>
                        </annotationProcessorPaths>
                        <fork>true</fork>
                        <compilerArgs>
                            <compilerArg>
                                -Amapstruct.defaultComponentModel=spring
                            </compilerArg>
                            <compilerArg>
                                -Amapstruct.defaultInjectionStrategy=constructor
                            </compilerArg>
                            <arg>-Xlint:all</arg>
                            <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</arg>
                            <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>
                            <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED</arg>
                            <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</arg>
                            <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED</arg>
                            <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</arg>
                            <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED</arg>
                            <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</arg>
                            <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
                            <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED</arg>
                        </compilerArgs>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>${jib-maven-plugin.version}</version>
                    <configuration>
                        <containerizingMode>packaged</containerizingMode>
                        <from>
                            <image>${source.image}</image>
                            <platforms>
                                <platform>
                                    <architecture>amd64</architecture>
                                    <os>linux</os>
                                </platform>
                            </platforms>
                            <auth>
                                <!--suppress MavenModelInspection -->
                                <username>${jib.to.auth.username}</username>
                                <!--suppress MavenModelInspection -->
                                <password>${jib.to.auth.password}</password>
                            </auth>
                        </from>
                        <to>
                            <!--suppress UnresolvedMavenProperty -->
                            <image>${jib.to.url}/transport/${project.build.finalName}:${image-tag}</image>
                            <tags>${image-tag}</tags>
                        </to>
                        <container>
                            <jvmFlags>
                                <jvmFlag>-Dfile.encoding=${project.build.sourceEncoding}</jvmFlag>
                                <jvmFlag>-Dsun.stderr.encoding=${project.build.sourceEncoding}</jvmFlag>
                                <jvmFlag>-Dsun.stdout.encoding=${project.build.sourceEncoding}</jvmFlag>
                                <jvmFlag>-Dnative.encoding=${project.build.sourceEncoding}</jvmFlag>
                                <jvmFlag>-XX:MaxRAMPercentage=75</jvmFlag>
                                <jvmFlag>-XX:+UseG1GC</jvmFlag>
                                <jvmFlag>-server</jvmFlag>
                                <jvmFlag>
                                    -Dspring.config.additional-location=optional:file:/app/resources/,optional:file:/app/resources/config/
                                </jvmFlag>
                                <jvmFlag>-XX:+AlwaysActAsServerClassMachine</jvmFlag>
                                <jvmFlag>-XX:+UseStringDeduplication</jvmFlag>
                                <jvmFlag>-XX:+PerfDisableSharedMem</jvmFlag>
                            </jvmFlags>
                            <creationTime>${maven.build.timestamp}</creationTime>
                            <labels>
                                <maintainer>${user.name}</maintainer>
                                <version>${project.version}</version>
                            </labels>
                            <creationTime>${maven.build.timestamp}</creationTime>
                        </container>
                        <!--suppress MavenModelInspection -->
                        <allowInsecureRegistries>${jib.allowInsecureRegistries}</allowInsecureRegistries>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>${versions-maven-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>properties-maven-plugin</artifactId>
                <version>1.0.0</version>
                <executions>
                    <execution>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>write-project-properties</goal>
                        </goals>
                        <configuration>
                            <outputFile>${project.build.outputDirectory}/pom.properties</outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco-maven-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven-jar-plugin.version}</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
                <configuration>
                    <argLine>@{argLine}</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>