<?xml version="1.0" encoding="UTF-8"?>
<!--suppress MavenModelInspection -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>parent</artifactId>
        <groupId>ru.sber.transport.token_generator</groupId>
        <version>3.17-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>application</artifactId>

    <properties>
        <server.port>8052</server.port>
        <!--suppress UnresolvedMavenProperty -->
        <source.image>
            registry.sigma.sbrf.ru/ci02351878/ci02353146_transport/open-jdk:17.5
        </source.image>
        <image-tag>${project.version}-${user.name}</image-tag>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.zonky.test.postgres</groupId>
                <artifactId>embedded-postgres-binaries-bom</artifactId>
                <version>13.0.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2023.0.3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport.token_generator</groupId>
                <artifactId>grpc</artifactId>
                <version>3.17-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport</groupId>
                <artifactId>kafka-functional</artifactId>
                <version>3.17-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport.roles</groupId>
                <artifactId>messaging</artifactId>
                <version>3.17-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport</groupId>
                <artifactId>jooq-database</artifactId>
                <version>3.16</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>1.6.0</version>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport.oauth</groupId>
                <artifactId>messaging</artifactId>
                <version>3.17-SNAPSHOT</version>
            </dependency>

            <dependency>
                <groupId>org.instancio</groupId>
                <artifactId>instancio-core</artifactId>
                <version>5.0.1</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport</groupId>
                <artifactId>embedded-postgres</artifactId>
                <version>3.17-SNAPSHOT</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>ru.sber.transport.service-discovery</groupId>
            <artifactId>starter</artifactId>
            <version>3.17-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>properties-loader</artifactId>
            <version>3.16.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.token_generator</groupId>
            <artifactId>grpc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.grpc</groupId>
            <artifactId>server</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>jooq-database</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>kafka-functional</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.roles</groupId>
            <artifactId>messaging</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.oauth</groupId>
            <artifactId>messaging</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-jose</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.instancio</groupId>
            <artifactId>instancio-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>embedded-postgres</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jdbc</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>token-generator</finalName>
        <plugins>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.4.3</version>
                <configuration>
                    <containerizingMode>packaged</containerizingMode>
                    <from>
                        <image>${source.image}</image>
                        <platforms>
                            <platform>
                                <architecture>amd64</architecture>
                                <os>linux</os>
                            </platform>
                        </platforms>
                        <auth>
                            <!--suppress MavenModelInspection -->
                            <username>${jib.to.auth.username}</username>
                            <!--suppress MavenModelInspection -->
                            <password>${jib.to.auth.password}</password>
                        </auth>
                    </from>
                    <to>
                        <!--suppress UnresolvedMavenProperty -->
                        <image>${jib.to.url}/transport/${project.build.finalName}:${image-tag}</image>
                        <tags>${image-tag}</tags>
                    </to>
                    <container>
                        <jvmFlags>
                            <jvmFlag>-Dfile.encoding=${project.build.sourceEncoding}</jvmFlag>
                            <jvmFlag>-Dsun.stderr.encoding=${project.build.sourceEncoding}</jvmFlag>
                            <jvmFlag>-Dsun.stdout.encoding=${project.build.sourceEncoding}</jvmFlag>
                            <jvmFlag>-Dnative.encoding=${project.build.sourceEncoding}</jvmFlag>
                            <jvmFlag>-XX:MaxRAMPercentage=75</jvmFlag>
                            <jvmFlag>-XX:+UseG1GC</jvmFlag>
                            <jvmFlag>-XX:G1HeapRegionSize=16M</jvmFlag>
                            <jvmFlag>-XX:MinMetaspaceFreeRatio=50</jvmFlag>
                            <jvmFlag>-XX:MaxMetaspaceFreeRatio=80</jvmFlag>
                            <jvmFlag>-server</jvmFlag>
                            <jvmFlag>-XX:MaxGCPauseMillis=20</jvmFlag>
                            <jvmFlag>-XX:InitiatingHeapOccupancyPercent=35</jvmFlag>
                            <jvmFlag>-XX:+ExplicitGCInvokesConcurrent</jvmFlag>
                            <jvmFlag>-XX:MaxInlineLevel=15</jvmFlag>
                            <jvmFlag>-Djava.awt.headless=true</jvmFlag>
                            <jvmFlag>
                                -Dspring.config.additional-location=optional:file:/app/resources/,optional:file:/app/resources/config/
                            </jvmFlag>
                            <jvmFlag>-XX:+AlwaysActAsServerClassMachine</jvmFlag>
                            <jvmFlag>-XX:+UseStringDeduplication</jvmFlag>
                            <jvmFlag>-XX:+PerfDisableSharedMem</jvmFlag>
                        </jvmFlags>
                        <creationTime>${maven.build.timestamp}</creationTime>
                        <labels>
                            <maintainer>${user.name}</maintainer>
                            <version>${project.version}</version>
                        </labels>
                        <creationTime>${maven.build.timestamp}</creationTime>
                    </container>
                    <!--suppress MavenModelInspection -->
                    <allowInsecureRegistries>${jib.allowInsecureRegistries}</allowInsecureRegistries>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <release>${maven.compiler.target}</release>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.6.0</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.springframework</groupId>
                            <artifactId>spring-context-indexer</artifactId>
                            <version>6.1.12</version>
                        </path>
                        <dependency>
                            <groupId>org.hibernate</groupId>
                            <artifactId>hibernate-jpamodelgen-jakarta</artifactId>
                            <version>5.6.15.Final</version>
                        </dependency>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>-Amapstruct.defaultComponentModel=spring</compilerArg>
                        <compilerArg>-Amapstruct.defaultInjectionStrategy=constructor</compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-meta</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-codegen</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-meta-extensions</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-meta-extensions-liquibase</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <generator>
                        <database>
                            <name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
                            <properties>
                                <property>
                                    <key>rootPath</key>
                                    <value>${basedir}/src/main/resources</value>
                                </property>
                                <property>
                                    <key>scripts</key>
                                    <value>db/changelog-master.yml</value>
                                </property>
                                <property>
                                    <key>includeLiquibaseTables</key>
                                    <value>false</value>
                                </property>
                                <property>
                                    <key>unqualifiedSchema</key>
                                    <value>none</value>
                                </property>
                                <property>
                                    <key>renderNameCase</key>
                                    <value>lower</value>
                                </property>
                                <property>
                                    <key>defaultNameCase</key>
                                    <value>lower</value>
                                </property>
                            </properties>
                        </database>
                        <generate>
                            <records>true</records>
                            <javaTimeTypes>true</javaTimeTypes>
                        </generate>
                        <target>
                            <packageName>ru.sber.transport.token_generator.database</packageName>
                            <directory>target/generated-sources/java/</directory>
                        </target>
                    </generator>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>