<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ru.sber.transport.request.external</groupId>
        <artifactId>parent</artifactId>
        <version>${release.version}</version>
    </parent>

    <artifactId>web</artifactId>

    <properties>
        <openapi.url>https://apistudio.sigma.sbrf.ru/public/bundle/yml/38e51566-cb7b-4c96-ad21-439ba66f82d0</openapi.url>
        <openapi.title>external-request</openapi.title>
        <openapi.optional>true</openapi.optional>
        <openapi.async>true</openapi.async>
        <openapi.delegatePattern>true</openapi.delegatePattern>
        <openapi.interfaceOnly>true</openapi.interfaceOnly>
        <java.version>21</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>authorization</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>documentation-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>role-check-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>24.1.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>file-works</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.request.external</groupId>
            <artifactId>providers</artifactId>
            <version>${parent.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.request.external</groupId>
            <artifactId>model</artifactId>
            <version>${parent.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.request.external</groupId>
            <artifactId>business</artifactId>
            <version>${parent.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.request.external</groupId>
            <artifactId>providers-grpc</artifactId>
            <version>${parent.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <configuration>
                    <configOptions>
                        <disallowAdditionalPropertiesIfNotPresent>true</disallowAdditionalPropertiesIfNotPresent>
                        <performBeanValidation>true</performBeanValidation>
                        <requestMappingMode>api_interface</requestMappingMode>
                        <serializableModel>true</serializableModel>
                        <useSpringController>true</useSpringController>
                    </configOptions>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>