package ru.sberbank.ditsib.transport.reports.enums;


import lombok.Getter;
import lombok.RequiredArgsConstructor;


@RequiredArgsConstructor
@Getter
public enum RequestPersonalStatus {
    PERSONAL_AWAITING_APPROVAL,
    PERSONAL_APPROVED,
    PERSONAL_AWAITING_SHARED_RIDE_APPROVAL,
    PERSONAL_SHARED_RIDE_DECLINED,
    PERSONAL_SHARED_RIDE_APPROVED,
    PERSONAL_ADDITIONAL_WAYPOINTS_APPROVAL,
    PERSONAL_ADDITIONAL_WAYPOINTS_APPROVED,
    PERSONAL_ADDITIONAL_WAYPOINTS_DECLINED,
    PERSONAL_TRIP_START_REMIND,
    PERSONAL_TRIP_IN_PROGRESS,
    PERSONAL_WAYPOINT_ARRIVED,
    PERSONAL_AWAITING_TRIP_APPROVAL,
    PERSONAL_AWAITING_TRIP_APPROVED,
    PERSONAL_AWAITING_TRIP_DECLINED,
    PERSONAL_ORDER_PAYMENT_FORMATION,
    PERSONAL_PAYMENT_AWAITING,
    PERSONAL_PAYMENT_DONE,
    PERSONAL_PAYMENT_DECLINED,
    PERSONAL_CANCELLED,
    PERSONAL_TRIP_FINISHED
}
