<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ru.sber.transport</groupId>
        <artifactId>fleet-common-parent</artifactId>
        <version>5.8.0.5</version>
    </parent>

    <groupId>ru.sber.transport.vehicle</groupId>
    <artifactId>parent</artifactId>
    <version>5.14</version>
    <modules>
        <module>application</module>
    </modules>
    <packaging>pom</packaging>

    <properties>
        <!-- Sonar properties -->
        <sonar.projectKey>TRANSPORT_FLEET_vehicle</sonar.projectKey>
        <sonar.moduleKey>${project.artifactId}</sonar.moduleKey>
        <sonar.exclusions>
            **/dto/**/*,
            **/config/*,
            **/dto/*,
            **/constants/*,
            **/exception/*,
            **/database/model/*
        </sonar.exclusions>
    </properties>
</project>
