DROP TABLE CONTRACTORS.VEHICLE;

CREATE TABLE CONTRACTORS.TRANSPORT
(
    ID            UUID PRIMARY KEY,
    BRAND         VARCHAR(255)       NOT NULL,
    MODEL         VARCHAR(20)        NOT NULL,
    STATE_NUMBER  VARCHAR(20) UNIQUE NOT NULL,
    COLOR         VARCHAR(20)        NOT NULL,
    CONTRACTOR_ID UUID
        CONSTRAINT TRANSPORT_CONTRACTOR_FK REFERENCES CONTRACTORS.CONTRACTOR (ID)
);