ALTER TABLE request_aggregation.address
    ALTER COLUMN address_name DROP NOT NULL,
ALTER COLUMN street DROP NOT NULL,
ALTER COLUMN house DROP NOT NULL,
ALTER COLUMN city DROP NOT NULL,
ALTER COLUMN region DROP NOT NULL,
ALTER COLUMN country DROP NOT NULL,
ALTER COLUMN region_type DROP NOT NULL;