### Настройки DevSecOps ###
### Общая информация о командах ###
team:
  - {
      # код команды в МУСе
      mus_code: "00EG0007",
      # название команды в МУСе
      mus_name: "Сбертранспорт",
      # Почтовый адрес Product Owner в МУСе для уведомлений с результатами сканирования
      # !!! Почта должна быть валидной для текущего домена, чтобы корректно определить пользователя, которому впоследствии предоставятся права на доступ к АС в SALM !!!
      # !!! Возможно указание нескольких почт через знаки ";" или "," внутри одной строки !!!
      # Пример: "user1@sberbank.ru; user2@sberbank.ru, user3@sberbank.ru"
      mus_po_mail: "sbertransport_devops@sberbank.ru",
    }
    # Возможно добавление нескольких команд
    # !!! Вторую и последующие команды необходимо добавить по формату, аналогичному первой !!!
#  - {
#      mus_code: "00040018",
#      mus_name: "Web SBOL Design",
#      mus_po_mail: "sspetrov@sberbank.ru",
#    }

### Общая информация о приложении ###
app:
  # Конфигурационный элемент (КЭ) приложения / модуля ПО в Service Manager.
  # !!! КЭ должен быть строкой, состоящей исключительно из цифр без лидирующих нулей !!!
  sm_id: "2351878"
  # название КЭ приложения / модуля ПО в Service Manager
  sm_name: "Сбертранспорт"

### Настройки SAST Checkmarx ###
sast_cx:
  # сredentials id в Jenkins для учетной записи Checkmarx одной команды, под которой будет проводиться сканирование
  creds_id: "checkmarx"
  # проектная область в JIRA для заведения и синхронизации дефектов
  jira_area: "TRANSPORT"
  # маски файлов и директорий для включения (**/*) в скан и исключения (!**/*) из скана.
  # Пример: "!**/utils/**/*.xml" - исключение всех xml файлов в папке utils
  masks: "!**/node_modules/**, !**/app/node_modules/**"
  # id профиля сканирования, по умолчанию 36. 14 - для мобильного приложения. 100003 - Smoke
  preset_id: "36"
  # макс время ожидания статуса QG в минутах
  wait_qg: "-1"

