<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <parent>
        <artifactId>java-parent</artifactId>
        <groupId>ru.sber.transport</groupId>
        <version>5.7</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>

    <groupId>ru.sber.transport.request_checks</groupId>
    <artifactId>parent</artifactId>
    <version>5.12</version>
    <name>request-checks</name>
    <modules>
        <module>application</module>
    </modules>

    <properties>
        <sonar.projectKey>TRANSPORT_PLATFORM_request_checks</sonar.projectKey>
        <collections.version>4.6</collections.version>
        <role-check-starter.version>230605-1</role-check-starter.version>
        <request.messaging.version>5.8</request.messaging.version>
        <sonar.exclusions>
            file:**/config/*
        </sonar.exclusions>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>properties-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>