spring:
  datasource:
    db-name: etrn_cargo
    url: jdbc:postgresql://localhost:5432/transport
    password: root
    username: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      connection-test-query: SELECT 1
      schema: ${spring.datasource.db-name}
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 25
          lob.non_contextual_creation: true
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        default_schema: ${spring.datasource.db-name}
        generate_statistics: ${HIBERNATE_GENERATE_STATISTIC:false}
        format_sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog-master.yml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    database-change-log-table: changelog_${spring.datasource.db-name}
    database-change-log-lock-table: changelog_${spring.datasource.db-name}_lock
    liquibase-schema: ${MIGRATIONS_SCHEMA:public}
