import { TKeys } from '../../interfaces/Orders.types';
import { IStatus } from '../../interfaces/Orders.interface';

// TODO: Выпилить в 1-м релиза не используемые тайтлы, после стабилизации 43-го релиза
export enum OrderTitle {
  humanReadableId = 'ID заявки',
  fullName = 'ФИО',
  status = 'Статус заявки',
  author = 'ФИО заявителя',
  authorPhone = 'Телефон заявителя',
  aprover = 'ФИО согласующего',
  sender = 'ФИО отправителя',
  senderPhone = 'Телефон отправителя',
  recipient = 'ФИО получателя',
  recipientPhone = 'Телефон получателя',
  tariffId = 'Тариф',
  date = 'Дата и время',
  creationTime = 'Дата и время создания заявки',
  departureTime = 'Дата и время отправления',
  plannedDate = 'Планируемая дата доставки',
  shipmentTime = 'Дата и время доставки',
  waitingTime = 'Время ожидания, ч',
  address = 'Адреса',
  senderAddress = 'Адрес отправления',
  recipientAddress = 'Адрес получения',
  cargo = 'Груз',
  cargoTitle = 'Наименования груза',
  cargoTypes = 'Тип груза',
  volume = 'Габариты груза (Ширина+Длина+Высота), м\u00B3',
  weight = 'Вес груза, кг',
  cargoSpace = 'Количество грузовых мест',
  carBrand = 'Марка',
  carModel = 'Модель',
  clientData = 'Участники грузоперевозки',
  initiator = 'Инициатор',
  person = 'Заявитель',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  personName = 'ФИО заявителя',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  personPhone = 'Телефон заявителя',
  position = 'Должность',
  additionalServices = 'Дополнительные услуги',
  moverDepartureAddress = 'Грузчики на адресе отправления (количество)',
  moverReceivingAddress = 'Грузчики на адресе получения (количество)',
  calculatedData = 'Расчетные данные',
  totalWeight = 'Общая масса, кг',
  totalVolume = 'Общий объём, м\u00B3',
  plannedDistance = 'Планируемое расстояние, км',
  actualDistance = 'Фактическое расстрояние, км',
  cost = 'Предварительная стоимость, руб',
  plannedCost = 'Планируемая стоимость по тарифу, руб',
  moverCost = 'Стоимость услуг Грузчиков, руб',
  totalCost = 'Общая планируемая стоимость по Заявке (по тарифу+услуги), руб',
  actualCost = 'Фактическая стоимость, руб',
  contractor = 'Исполнитель',
  tariffContractor = 'Контрагент исполнитель по Тарифу',
  car = 'Автомобиль. Марка',
  carNumber = 'Автомобиль. Номер',
  driver = 'Водитель (Курьер) ФИО',
  driverPhone = 'Водитель (Курьер) Номер телефона',
  comment = 'Комментарий',
  commentOrder = 'Комментарий к заказу',
  commonComment = 'Комментарий заявителя',
  commentEng = 'Комментарий инженера',
  mobilePhone = 'Мобильный телефон',
  employeeSigns = 'Признаки сотрудника',
  department = 'Подразделение',
  approvedBy = 'Согласующий',
  limitId = 'Номер лимита',
  limitType = 'Тип лимита',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  executor = 'Исполнитель',
  delivery = 'Доставка',
  transferTime = 'Дата и время сбора',
  distance = 'Предварительный километраж, км',
  deliveryType = 'Тип доставки',
  courier = 'ФИО курьера',
  route = 'Маршрут',
  loaders = 'Количество грузчиков',
}

export enum Statuses {
  CARGO_ACCEPTED = 'CARGO_ACCEPTED',
  CARGO_PLANNING = 'CARGO_PLANNING',
  CARGO_AWAITING_APPROVAL = 'CARGO_AWAITING_APPROVAL',
  CARGO_APPROVED = 'CARGO_APPROVED',
  CARGO_AWAITING_DATA = 'CARGO_AWAITING_DATA',
  CARGO_AWAITING_TRANSFER = 'CARGO_AWAITING_TRANSFER',
  CARGO_TRANSFER_FINISHED = 'CARGO_TRANSFER_FINISHED',
  CARGO_SHIPMENT_FINISHED = 'CARGO_SHIPMENT_FINISHED',
  CARGO_DELIVERY_CONFIRMATION_FINISHED = 'CARGO_DELIVERY_CONFIRMATION_FINISHED',
  CARGO_CANCELED = 'CARGO_CANCELED',
}

export const StatusNames: TKeys<string> = {
  [Statuses.CARGO_ACCEPTED]: 'Принята',
  [Statuses.CARGO_PLANNING]: 'Планирование',
  [Statuses.CARGO_AWAITING_APPROVAL]: 'На согласовании',
  [Statuses.CARGO_APPROVED]: 'Согласовано',
  [Statuses.CARGO_AWAITING_DATA]: 'Отправлено контрагенту',
  [Statuses.CARGO_AWAITING_TRANSFER]: 'На сборе',
  [Statuses.CARGO_TRANSFER_FINISHED]: 'Доставка',
  [Statuses.CARGO_SHIPMENT_FINISHED]: 'Доставлено',
  [Statuses.CARGO_DELIVERY_CONFIRMATION_FINISHED]: 'Завершено',
  [Statuses.CARGO_CANCELED]: 'Отменено',
};

export const STATUSES: IStatus<Statuses>[] = [
  {
    name: Statuses.CARGO_ACCEPTED,
    rusName: StatusNames[Statuses.CARGO_ACCEPTED],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
  },
  {
    name: Statuses.CARGO_PLANNING,
    rusName: StatusNames[Statuses.CARGO_PLANNING],
    editable: true,
    approvable: true,
    cancelable: true,
    finalStatus: false,
  },
  {
    name: Statuses.CARGO_AWAITING_APPROVAL,
    rusName: StatusNames[Statuses.CARGO_AWAITING_APPROVAL],
    editable: true,
    approvable: true,
    cancelable: true,
    finalStatus: false,
  },
  {
    name: Statuses.CARGO_APPROVED,
    rusName: StatusNames[Statuses.CARGO_APPROVED],
    editable: true,
    approvable: false,
    cancelable: true,
    finalStatus: false,
  },
  {
    name: Statuses.CARGO_AWAITING_DATA,
    rusName: StatusNames[Statuses.CARGO_AWAITING_DATA],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: false,
  },
  {
    name: Statuses.CARGO_AWAITING_TRANSFER,
    rusName: StatusNames[Statuses.CARGO_AWAITING_TRANSFER],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: false,
  },
  {
    name: Statuses.CARGO_TRANSFER_FINISHED,
    rusName: StatusNames[Statuses.CARGO_TRANSFER_FINISHED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: false,
  },
  {
    name: Statuses.CARGO_SHIPMENT_FINISHED,
    rusName: StatusNames[Statuses.CARGO_SHIPMENT_FINISHED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: false,
  },
  {
    name: Statuses.CARGO_DELIVERY_CONFIRMATION_FINISHED,
    rusName: StatusNames[Statuses.CARGO_DELIVERY_CONFIRMATION_FINISHED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
  },
  {
    name: Statuses.CARGO_CANCELED,
    rusName: StatusNames[Statuses.CARGO_CANCELED],
    editable: false,
    approvable: false,
    cancelable: false,
    finalStatus: true,
  },
];
