branch:
  ignore_regex: "^master$|^release/.*$|^hotfix/.*$" #регулярное выражение для игнорирования пр-ов из ветки такой-то
 
review_mode: # режим ревью: можно выбрать либо использовать одновременно
  - SUGGESTIONS # предлагает изменение в коде
  #- REPORT # оставляет комментарий в формате единого отчета
  - CUSTOM # оставляет комментарий в формате единого отчета по пользовательским инструкциям
  #- HTML # оставляет комментарий в формате html аттачмента
 
customer_instructions_file_name: "instructions.md" # имя файла с инструкциями
 
extra_instruction:
  suggestion: "instructions-suggestions.md" # (Можно указывать имя/путь до файла) Данная инструкция модифирует поведение режима предложения, оставьте пустыми если не хотите менять поведение агента
  #report: "Инструкция" # (Можно указывать имя/путь до файла) Данная инструкция модифицирует поведение режима отчета, оставьте пустыми если не хотите менять поведение агента
 
severity_type: # Фильтрация по серьезности дефектов
  - "MAJOR"
  - "MINOR"
  - "INFO"
 
# filter:
#   extensions:
#     - ".js" # Будет игнорировать файлы с расширением js
#     - ".html" #Будет игнорировать html файлы
#   paths:
#     - "src/test/demo.cpp" # Игнорит конкретный путь
#     - "~src/test/js" # Игнорит пути которые содержат
 
auto_approve: true
 
description: APPEND #Либо NEW  
 
git:
   update_strategy: MERGE # Либо REBASE