<?xml version="1.0" encoding="windows-1251"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by VI (GNIVC FNS RF) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sch="http://purl.oclc.org/dsdl/schematron"
           xmlns:usch="http://www.unisoftware.ru/schematron-extensions"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Файл">
		<xs:annotation>
			<!---*******************************************************************************************************************************************************************************-->
			<xs:appinfo>
				<sch:pattern name="Проверка имени файла на соответствие значению атрибута @ИдФайл">
					<sch:rule context="Файл">
						<!--Проверка имени файла на соответствие ИдФайл-->
						<sch:assert test="usch:getFileName() = @ИдФайл">
							<usch:error code="0400400007" path="@ИдФайл" value-of-select="@ИдФайл" doc-id-path="usch:getFileName()" doc-id-caption="Файл">Имя файла обмена "<usch:value-of select="usch:getFileName()"/>" не совпадает со значением элемента ИдФайл "<usch:value-of select="@ИдФайл"/>"</usch:error>
						</sch:assert>
					</sch:rule>
				</sch:pattern>
			</xs:appinfo>
			<!---*******************************************************************************************************************************************************************************-->
			<xs:documentation>Файл обмена</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ИдПолИной" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Идентификатор иного получателя</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="4"/>
							<xs:maxLength value="46"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Документ">
					<xs:annotation>
						<!---*************************************************************************************************************************************************************-->
						<xs:appinfo>
							<sch:pattern name="Наличие элемента УИДПЛПред в зависимости от значения элемента ПризнНачРейс">
								<sch:rule context="Документ">
									<!-- Контроль наличия элемента УИДПЛПред в зависимости от значения элемента ПризнНачРейс -->
									<sch:assert test="usch:iif( 
						@ПризнНачРейс=2   ,
						count(@УИДПЛПред)!=0  , 
						count(@УИДПЛПред)=0  
						)">
										<usch:error code="0400400007" path="@УИДПЛПред" value-of-select="count(@УИДПЛПред)"> Не выполнено условие присутствия (отсутствия) элемента УИДПЛПред при значении элемента ПризнНачРейс, равном "<usch:value-of select="@ПризнНачРейс"/>".  </usch:error>
									</sch:assert>
								</sch:rule>
							</sch:pattern>
						</xs:appinfo>
						<!---*************************************************************************************************************************************************************-->
						<xs:documentation>Путевой лист, информация об обстоятельствах и особенностях рейса</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="СодИнфСоб">
								<xs:annotation>
									<!---*************************************************************************************************************************************************************-->
									<xs:appinfo>
										<sch:pattern name="Наличие элемента ВидКП в зависимости от значения элемента ВидПрв">
											<sch:rule context="СодИнфСоб">
												<!-- Контроль наличия элемента ВидКП в зависимости от значения элемента ВидПрв -->
												<sch:assert test="usch:iif( 
						@ВидПрв='КП' ,
						count(@ВидКП)!=0  , 
						count(@ВидКП)=0 
						)">
													<usch:error code="0400400007" path="@ВидКП" value-of-select="count(@ВидКП)"> Не выполнено условие присутствия (отсутствия) элемента ВидКП при значении элемента ВидПрв, равном "<usch:value-of select="@ВидПрв"/>".  </usch:error>
												</sch:assert>
											</sch:rule>
										</sch:pattern>
									</xs:appinfo>
									<!---*************************************************************************************************************************************************************-->
									<!---*************************************************************************************************************************************************************-->
									<xs:appinfo>
										<sch:pattern name="Наличие элемента МестОтпр в зависимости от значения элемента ВидКП">
											<sch:rule context="СодИнфСоб">
												<!-- Контроль наличия элемента МестОтпр в зависимости от значения элемента ВидКП -->
												<sch:assert test="usch:iif( 
						count(@ВидКП)!=0  and  @ВидКП='ПГ' ,
						count(МестОтпр)!=0  , 
						( count(МестОтпр)!=0  or  count(МестОтпр)=0 ) 
						)">
													<usch:error code="0400400007" path="МестОтпр" value-of-select="count(МестОтпр)"> Не выполнено условие присутствия (отсутствия) элемента МестОтпр при значении элемента ВидКП, равном "<usch:value-of select="@ВидКП"/>".  </usch:error>
												</sch:assert>
											</sch:rule>
										</sch:pattern>
									</xs:appinfo>
									<!---*************************************************************************************************************************************************************-->
									<!---*************************************************************************************************************************************************************-->
									<xs:appinfo>
										<sch:pattern name="Наличие элемента АдрПункт в зависимости от значения элемента ВидКП">
											<sch:rule context="СодИнфСоб">
												<!-- Контроль наличия элемента АдрПункт в зависимости от значения элемента ВидКП -->
												<sch:assert test="usch:iif( 
						count(@ВидКП)!=0  and  @ВидКП='ПГ' ,
						count(АдрПункт)!=0  , 
						( count(АдрПункт)!=0  or  count(АдрПункт)=0 ) 
						)">
													<usch:error code="0400400007" path="АдрПункт" value-of-select="count(АдрПункт)"> Не выполнено условие присутствия (отсутствия) элемента АдрПункт при значении элемента ВидКП, равном "<usch:value-of select="@ВидКП"/>".  </usch:error>
												</sch:assert>
											</sch:rule>
										</sch:pattern>
									</xs:appinfo>
									<!---*************************************************************************************************************************************************************-->
									<xs:documentation>Содержание путевого листа, информация об обстоятельствах и особенностях рейса</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="МестОтпр" type="АдресПользТип" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Место отправления</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="АдрПункт" type="АдресПользТип" minOccurs="0" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Адреса пунктов погрузки и выгрузки</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="СрокПЛ">
											<xs:annotation>
												<!---*************************************************************************************************************************************************************-->
												<xs:appinfo>
													<sch:pattern name="Наличие элемента ДатаИспПЛ в зависимости от значения элемента ПЛДень">
														<sch:rule context="СрокПЛ">
															<!-- Контроль наличия элемента ДатаИспПЛ в зависимости от значения элемента ПЛДень -->
															<sch:assert test="usch:iif( 
						@ПЛДень=1 ,
						count(@ДатаИспПЛ)!=0  , 
						count(@ДатаИспПЛ)=0  
						)">
																<usch:error code="0400400007" path="@ДатаИспПЛ" value-of-select="count(@ДатаИспПЛ)"> Не выполнено условие присутствия (отсутствия) элемента ДатаИспПЛ при значении элемента ПЛДень, равном "<usch:value-of select="@ПЛДень"/>".  </usch:error>
															</sch:assert>
														</sch:rule>
													</sch:pattern>
												</xs:appinfo>
												<!---*************************************************************************************************************************************************************-->
												<!---*************************************************************************************************************************************************************-->
												<xs:appinfo>
													<sch:pattern name="Наличие элемента ДатаНачИспПЛ в зависимости от значения элемента ПЛДень">
														<sch:rule context="СрокПЛ">
															<!-- Контроль наличия элемента ДатаНачИспПЛ в зависимости от значения элемента ПЛДень -->
															<sch:assert test="usch:iif( 
						@ПЛДень=2 ,
						count(@ДатаНачИспПЛ)!=0  , 
						count(@ДатаНачИспПЛ)=0  
						)">
																<usch:error code="0400400007" path="@ДатаНачИспПЛ" value-of-select="count(@ДатаНачИспПЛ)"> Не выполнено условие присутствия (отсутствия) элемента ДатаНачИспПЛ при значении элемента ПЛДень, равном "<usch:value-of select="@ПЛДень"/>".  </usch:error>
															</sch:assert>
														</sch:rule>
													</sch:pattern>
												</xs:appinfo>
												<!---*************************************************************************************************************************************************************-->
												<!---*************************************************************************************************************************************************************-->
												<xs:appinfo>
													<sch:pattern name="Наличие элемента ДатаКонИспПЛ в зависимости от значения элемента ПЛДень">
														<sch:rule context="СрокПЛ">
															<!-- Контроль наличия элемента ДатаКонИспПЛ в зависимости от значения элемента ПЛДень -->
															<sch:assert test="usch:iif( 
						@ПЛДень=2 ,
						count(@ДатаКонИспПЛ)!=0  , 
						count(@ДатаКонИспПЛ)=0  
						)">
																<usch:error code="0400400007" path="@ДатаКонИспПЛ" value-of-select="count(@ДатаКонИспПЛ)"> Не выполнено условие присутствия (отсутствия) элемента ДатаКонИспПЛ при значении элемента ПЛДень, равном "<usch:value-of select="@ПЛДень"/>".  </usch:error>
															</sch:assert>
														</sch:rule>
													</sch:pattern>
												</xs:appinfo>
												<!---*************************************************************************************************************************************************************-->
												<xs:documentation>Сведения о сроке действия путевого листа</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:attribute name="ПЛДень" use="required">
													<xs:annotation>
														<xs:documentation>Признак формирования путевого листа на один день</xs:documentation>
													</xs:annotation>
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:length value="1"/>
															<xs:enumeration value="1"/>
															<xs:enumeration value="2"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="ДатаИспПЛ" type="ДатаТип" use="optional">
													<xs:annotation>
														<xs:documentation>Дата, в течение которой путевой лист может быть использован</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="ДатаНачИспПЛ" type="ДатаТип" use="optional">
													<xs:annotation>
														<xs:documentation>Дата начала срока использования путевого листа</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="ДатаКонИспПЛ" type="ДатаТип" use="optional">
													<xs:annotation>
														<xs:documentation>Дата окончания срока использования путевого листа</xs:documentation>
													</xs:annotation>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element name="СвЛицПЛ">
											<xs:annotation>
												<xs:documentation>Сведения о лице, оформившем путевой лист</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ИдСв">
														<xs:annotation>
															<xs:documentation>Идентификационные сведения</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:choice>
																<xs:element name="СвИП">
																	<xs:annotation>
																		<xs:documentation>Сведения об индивидуальном предпринимателе</xs:documentation>
																	</xs:annotation>
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="ФИО" type="ФИОТип">
																				<xs:annotation>
																					<xs:documentation>Фамилия, имя, отчество (при наличии)</xs:documentation>
																				</xs:annotation>
																			</xs:element>
																		</xs:sequence>
																		<xs:attribute name="ИНН" type="ИННФЛТип" use="optional">
																			<xs:annotation>
																				<xs:documentation>ИНН</xs:documentation>
																			</xs:annotation>
																		</xs:attribute>
																		<xs:attribute name="ОГРНИП" type="ОГРНИПТип" use="required">
																			<xs:annotation>
																				<xs:documentation>Основной государственный регистрационный номер индивидуального предпринимателя</xs:documentation>
																			</xs:annotation>
																		</xs:attribute>
																	</xs:complexType>
																</xs:element>
																<xs:element name="СвЮЛУч">
																	<xs:annotation>
																		<xs:documentation>Сведения о юридическом лице, состоящем на учете в налоговых органах</xs:documentation>
																	</xs:annotation>
																	<xs:complexType>
																		<xs:attribute name="НаимОрг" use="required">
																			<xs:annotation>
																				<xs:documentation>Наименование полное</xs:documentation>
																			</xs:annotation>
																			<xs:simpleType>
																				<xs:restriction base="xs:string">
																					<xs:minLength value="1"/>
																					<xs:maxLength value="1000"/>
																				</xs:restriction>
																			</xs:simpleType>
																		</xs:attribute>
																		<xs:attribute name="ИННЮЛ" type="ИННЮЛТип" use="optional">
																			<xs:annotation>
																				<xs:documentation>ИНН</xs:documentation>
																			</xs:annotation>
																		</xs:attribute>
																		<xs:attribute name="КПП" type="КППТип" use="optional">
																			<xs:annotation>
																				<xs:documentation>КПП</xs:documentation>
																			</xs:annotation>
																		</xs:attribute>
																		<xs:attribute name="ОГРН" type="ОГРНТип" use="required">
																			<xs:annotation>
																				<xs:documentation>Основной государственный регистрационный номер юридического лица</xs:documentation>
																			</xs:annotation>
																		</xs:attribute>
																	</xs:complexType>
																</xs:element>
															</xs:choice>
														</xs:complexType>
													</xs:element>
													<xs:element name="Адрес" type="АдресТип">
														<xs:annotation>
															<xs:documentation>Адрес в пределах местонахождения юридического лица / адрес регистрации по месту жительства индивидуального предпринимателя</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="Контакт" type="КонтактТип">
														<xs:annotation>
															<xs:documentation>Контактные данные</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="ЛицоОфПЛ" use="required">
													<xs:annotation>
														<xs:documentation>Лицо, оформившее путевой лист</xs:documentation>
													</xs:annotation>
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:length value="1"/>
															<xs:enumeration value="С"/>
															<xs:enumeration value="А"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element name="СвГО" type="УчастникТип" minOccurs="0" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Сведения о грузоотправителе (грузоотправителях)</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="СвТС">
											<xs:annotation>
												<xs:documentation>Сведения о транспортном средстве</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ТС">
														<xs:annotation>
															<!---*************************************************************************************************************************************************************-->
															<xs:appinfo>
																<sch:pattern name="Наличие элемента РегНомер в зависимости от наличия элемент ИнвНомер">
																	<sch:rule context="ТС">
																		<!--Контроль наличия элемента РегНомер в зависимости от наличия элемент ИнвНомер-->
																		<sch:assert test="usch:iif( 
						count(@ИнвНомер)=0  ,
						count(@РегНомер)!=0  , 
						( count(@РегНомер)!=0  or  count(@РегНомер)=0 ) 
						)">
																			<usch:error code="0400400007" path="@РегНомер" value-of-select="count(@РегНомер)"> Не выполнено условие присутствия элемента РегНомер при отсутсвии элемента ИнвНомер>". 
																 </usch:error>
																		</sch:assert>
																	</sch:rule>
																</sch:pattern>
															</xs:appinfo>
															<!---*************************************************************************************************************************************************************-->
															<!---*************************************************************************************************************************************************************-->
															<xs:appinfo>
																<sch:pattern name="Наличие элемента ИнвНомер в зависимости от наличия элемент ИнвНомер">
																	<sch:rule context="ТС">
																		<!--Контроль наличия элемента ИнвНомер в зависимости от наличия элемент ИнвНомер-->
																		<sch:assert test="usch:iif( 
						count(@РегНомер)=0  ,
						count(@ИнвНомер)!=0  , 
						( count(@ИнвНомер)!=0  or  count(@ИнвНомер)=0 ) 
						)">
																			<usch:error code="0400400007" path="@ИнвНомер" value-of-select="count(@РегНомер)"> Не выполнено условие присутствия элемента ИнвНомер при отсутсвии элемента РегНомер>". 
																 </usch:error>
																		</sch:assert>
																	</sch:rule>
																</sch:pattern>
															</xs:appinfo>
															<!---*************************************************************************************************************************************************************-->
															<xs:documentation>Транспортное средство</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:attribute name="Тип" use="required">
																<xs:annotation>
																	<xs:documentation>Тип транспортного средства согласно паспорту транспортного средства</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:minLength value="1"/>
																		<xs:maxLength value="1000"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="Марка" use="required">
																<xs:annotation>
																	<xs:documentation>Марка транспортного средства согласно паспорту транспортного средства</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:minLength value="1"/>
																		<xs:maxLength value="1000"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="Модель" use="required">
																<xs:annotation>
																	<xs:documentation>Модель транспортного средства согласно паспорту транспортного средства</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:minLength value="1"/>
																		<xs:maxLength value="1000"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="РегНомер" use="optional">
																<xs:annotation>
																	<xs:documentation>Государственный регистрационный номер транспортного средства</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:minLength value="1"/>
																		<xs:maxLength value="9"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="ИнвНомер" use="optional">
																<xs:annotation>
																	<xs:documentation>Инвентарный номер</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:minLength value="1"/>
																		<xs:maxLength value="60"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
													<xs:element name="Прицеп" minOccurs="0" maxOccurs="unbounded">
														<xs:annotation>
															<xs:documentation>Прицеп (полуприцеп)</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:attribute name="Марка" use="required">
																<xs:annotation>
																	<xs:documentation>Марка прицепа (полуприцепа)</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:minLength value="1"/>
																		<xs:maxLength value="1000"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="Модель" use="required">
																<xs:annotation>
																	<xs:documentation>Модель прицепа (полуприцепа)</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:minLength value="1"/>
																		<xs:maxLength value="1000"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="РегНомер" use="required">
																<xs:annotation>
																	<xs:documentation>Государственный регистрационный номер прицепа (полуприцепа)</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:minLength value="1"/>
																		<xs:maxLength value="9"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="СвВодит" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Сведения о водителе (водителях) транспортного средства</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ВодитУд" minOccurs="0">
														<xs:annotation>
															<xs:documentation>Данные водительского удостоверения</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:attribute name="НомВУ" use="required">
																<xs:annotation>
																	<xs:documentation>Номер водительского удостоверения</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:minLength value="1"/>
																		<xs:maxLength value="20"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="СерВУ" use="required">
																<xs:annotation>
																	<xs:documentation>Серия водительского удостоверения</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:minLength value="1"/>
																		<xs:maxLength value="20"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="ДатаВыдВУ" type="ДатаТип" use="required">
																<xs:annotation>
																	<xs:documentation>Дата выдачи водительского удостоверения</xs:documentation>
																</xs:annotation>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
													<xs:element name="ФИО" type="ФИОТип">
														<xs:annotation>
															<xs:documentation>Фамилия, имя, отчество (при наличии)</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="ИННФЛ" type="ИННФЛТип" use="optional">
													<xs:annotation>
														<xs:documentation>ИНН физического лица</xs:documentation>
													</xs:annotation>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element name="ИнфПол" type="ИнфПолТип" minOccurs="0" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Информационное поле</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="УИД_ПЛ" use="optional">
										<xs:annotation>
											<xs:documentation>Уникальный идентификатор документа путевого листа</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
												<xs:maxLength value="36"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ОбМедОсмПосле" use="required">
										<xs:annotation>
											<xs:documentation>Признак обязательности проведения послесменного, послерейсового медицинского осмотра</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:length value="1"/>
												<xs:enumeration value="1"/>
												<xs:enumeration value="2"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ВидПрв" use="required">
										<xs:annotation>
											<xs:documentation>Сведения о виде перевозки</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:length value="2"/>
												<xs:enumeration value="КП"/>
												<xs:enumeration value="СН"/>
												<xs:enumeration value="СТ"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ВидКП" use="optional">
										<xs:annotation>
											<xs:documentation>Вид коммерческой перевозки</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:length value="2"/>
												<xs:enumeration value="РП"/>
												<xs:enumeration value="ПГ"/>
												<xs:enumeration value="ЗП"/>
												<xs:enumeration value="ЛТ"/>
												<xs:enumeration value="ПД"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ВидСообщ" use="required">
										<xs:annotation>
											<xs:documentation>Сведения о виде сообщения</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:length value="1"/>
												<xs:enumeration value="Г"/>
												<xs:enumeration value="П"/>
												<xs:enumeration value="М"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="ПодпИнфСоб" type="ПодписантТип">
								<xs:annotation>
									<!---*************************************************************************************************************************************************************-->
									<xs:appinfo>
										<sch:pattern name="Наличие элемента СвДоверЭл в зависимости от значения элемента СпосПодтПолном">
											<sch:rule context="ПодпИнфСоб">
												<!--Контроль наличия элемента СвДоверЭл в зависимости от значения элемента СпосПодтПолном-->
												<sch:assert test="usch:iif( 
						@СпосПодтПолном=3  ,
						count(СвДоверЭл)!=0  , 
						count(СвДоверЭл)=0 
						)">
													<usch:error code="0400400007" path="СвДоверЭл" value-of-select="count(СвДоверЭл)"> Не выполнено условие присутствия (отсутствия) элемента СвДоверЭл при при значении элемента СпосПодтПолном, равном "<usch:value-of select="@СпосПодтПолном"/>". </usch:error>
												</sch:assert>
											</sch:rule>
										</sch:pattern>
									</xs:appinfo>
									<!---*************************************************************************************************************************************************************-->
									<!---*************************************************************************************************************************************************************-->
									<xs:appinfo>
										<sch:pattern name="Наличие элемента СвДоверБум в зависимости от значения элемента СпосПодтПолном">
											<sch:rule context="ПодпИнфСоб">
												<!--Контроль наличия элемента СвДоверБум в зависимости от значения элемента СпосПодтПолном-->
												<sch:assert test="usch:iif( 
						@СпосПодтПолном=5  ,
						count(СвДоверБум)!=0  , 
						count(СвДоверБум)=0 
						)">
													<usch:error code="0400400007" path="СвДоверБум" value-of-select="count(СвДоверБум)"> Не выполнено условие присутствия (отсутствия) элемента СвДоверБум при при значении элемента СпосПодтПолном, равном "<usch:value-of select="@СпосПодтПолном"/>". </usch:error>
												</sch:assert>
											</sch:rule>
										</sch:pattern>
									</xs:appinfo>
									<!---*************************************************************************************************************************************************************-->
									<xs:documentation>Сведения о лице, подписывающем файл обмена информации об обстоятельствах и особенностиях рейса в электронной форме</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="КНД" use="required">
							<xs:annotation>
								<xs:documentation>Код документа по КНД</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="КНДТип">
									<xs:enumeration value="1110380"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ДатИнфСоб" type="ДатаТип" use="required">
							<xs:annotation>
								<xs:documentation>Дата формирования файла обмена информации об обстоятельствах и особенностях рейса</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="ВрИнфСоб" type="ВремяТип" use="required">
							<xs:annotation>
								<xs:documentation>Время формирования файла обмена информации об обстоятельствах и особенностях рейса</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="НомерПЛ" use="optional">
							<xs:annotation>
								<xs:documentation>Номер путевого листа</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1"/>
									<xs:maxLength value="36"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ДатаПЛ" type="ДатаТип" use="optional">
							<xs:annotation>
								<xs:documentation>Дата путевого листа</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="ПризнНачРейс" use="required">
							<xs:annotation>
								<xs:documentation>Признак начала рейса</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:length value="1"/>
									<xs:enumeration value="1"/>
									<xs:enumeration value="2"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="УИДПЛПред" use="optional">
							<xs:annotation>
								<xs:documentation>Уникальный идентификатор предыдущего путевого листа</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1"/>
									<xs:maxLength value="36"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ИдФайл" use="required">
				<xs:annotation>
					<xs:documentation>Идентификатор файла</xs:documentation>
					<xs:documentation>Содержит (повторяет) имя сформированного файла (без расширения)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ВерсПрог" use="required">
				<xs:annotation>
					<xs:documentation>Версия программы, с помощью которой сформирован файл</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="40"/>
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ВерсФорм" use="required">
				<xs:annotation>
					<xs:documentation>Версия формата</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="5"/>
						<xs:enumeration value="5.01"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="УчастникТип">
		<xs:annotation>
			<xs:documentation>Сведения о лице, имеющем отношение к перевозке (об участнике перевозки)</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ИнфДляУчаст" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Информация для участника документооборота</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="ИННУчаст" use="required">
						<xs:annotation>
							<xs:documentation>ИНН участника</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="10"/>
								<xs:maxLength value="12"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="ИнфУчаст" use="required">
						<xs:annotation>
							<xs:documentation>Информация для участника</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
								<xs:maxLength value="255"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="ИдСв" type="ИдСвТип">
				<xs:annotation>
					<xs:documentation>Идентификационные сведения о лице, имеющем отношение к перевозке (об участнике перевозки)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Адрес" type="АдресТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Сведения об адресе </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Контакт" type="КонтактТип">
				<xs:annotation>
					<xs:documentation>Контактные данные</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ИдСвТип">
		<xs:annotation>
			<xs:documentation>Идентификационные сведения о лице, имеющем отношение к перевозке (об участнике перевозки)</xs:documentation>
		</xs:annotation>
		<xs:choice>
			<xs:element name="СвИП" type="СвИПТип">
				<xs:annotation>
					<xs:documentation>Сведения об индивидуальном предпринимателе</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="СвЮЛУч" type="СвЮЛУчТип">
				<xs:annotation>
					<xs:documentation>Сведения об организации, состоящей на учете в налоговых органах</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="СвИнНеУч" type="СвИнНеУчТип">
				<xs:annotation>
					<!---*************************************************************************************************************************************************************-->
					<xs:appinfo>
						<sch:pattern name="Наличие элемента Стран в зависимости от значения элемента ИдСтат">
							<sch:rule context="СвИнНеУч">
								<!-- Контроль наличия элемента Стран в зависимости от значения элемента ИдСтат -->
								<sch:assert test="usch:iif( 
						@ИдСтат='ИО' ,
						count(@Стран)!=0  , 
						( count(@Стран)!=0  or  count(@Стран)=0 ) 
						)">
									<usch:error code="0400400007" path="@Стран" value-of-select="count(@Стран)"> Не выполнено условие присутствия (отсутствия) элемента Стран при значении элемента ИдСтат, равном "<usch:value-of select="@ИдСтат"/>".  </usch:error>
								</sch:assert>
							</sch:rule>
						</sch:pattern>
					</xs:appinfo>
					<!---*************************************************************************************************************************************************************-->
					<!---*************************************************************************************************************************************************************-->
					<xs:appinfo>
						<sch:pattern name="Наличие элемента Наим в зависимости от значения элемента ИдСтат">
							<sch:rule context="СвИнНеУч">
								<!-- Контроль наличия элемента Наим в зависимости от значения элемента ИдСтат -->
								<sch:assert test="usch:iif( 
						@ИдСтат='ИГ' ,
						count(@Наим)!=0  , 
						( count(@Наим)!=0  or  count(@Наим)=0 ) 
						)">
									<usch:error code="0400400007" path="@Наим" value-of-select="count(@Наим)"> Не выполнено условие присутствия (отсутствия) элемента Наим при значении элемента ИдСтат, равном "<usch:value-of select="@ИдСтат"/>".  </usch:error>
								</sch:assert>
							</sch:rule>
						</sch:pattern>
					</xs:appinfo>
					<!---*************************************************************************************************************************************************************-->
					<!---*************************************************************************************************************************************************************-->
					<xs:appinfo>
						<sch:pattern name="Наличие элемента Идентиф в зависимости от от значения элемента ИдСтат и наличия элементов Наим и ИныеСвед">
							<sch:rule context="СвИнНеУч">
								<!--Контроль наличия элемента Идентиф в зависимости от от значения элемента ИдСтат и наличия элементов Наим и ИныеСвед-->
								<sch:assert test="usch:iif( 
						@ИдСтат='ИО' and count(@Наим)=0 and count(@ИныеСвед)=0 ,
						count(@Идентиф)!=0  , 
						( count(@Идентиф)!=0  or  count(@Идентиф)=0 ) 
						)">
									<usch:error code="0400400007" path="@Идентиф" value-of-select="count(@Идентиф)"> Не выполнено условие присутствия (отсутствия) элемента Идентиф при при значении элемента ИдСтат, равном "<usch:value-of select="@ИдСтат"/>" и наличии элемента Наим в количестве, равном "<usch:value-of select="count(@Наим)"/>" и элемента  ИныеСвед в количестве, равном "<usch:value-of select="count(@ИныеСвед)"/>". </usch:error>
								</sch:assert>
							</sch:rule>
						</sch:pattern>
					</xs:appinfo>
					<!---*************************************************************************************************************************************************************-->
					<!---*************************************************************************************************************************************************************-->
					<xs:appinfo>
						<sch:pattern name="Наличие элемента ИныеСвед в зависимости от от значения элемента ИдСтат и наличия элементов Наим и Идентиф">
							<sch:rule context="СвИнНеУч">
								<!--Контроль наличия элемента ИныеСвед в зависимости от от значения элемента ИдСтат и наличия элементов Наим и Идентиф-->
								<sch:assert test="usch:iif( 
						@ИдСтат='ИО' and count(@Наим)=0 and count(@Идентиф)=0 ,
						count(@ИныеСвед)!=0  , 
						( count(@ИныеСвед)!=0  or  count(@ИныеСвед)=0 ) 
						)">
									<usch:error code="0400400007" path="@ИныеСвед" value-of-select="count(@ИныеСвед)"> Не выполнено условие присутствия (отсутствия) элемента ИныеСвед при при значении элемента ИдСтат, равном "<usch:value-of select="@ИдСтат"/>" и наличии элемента Наим в количестве, равном "<usch:value-of select="count(@Наим)"/>" и элемента  Идентиф в количестве, равном "<usch:value-of select="count(@Идентиф)"/>". </usch:error>
								</sch:assert>
							</sch:rule>
						</sch:pattern>
					</xs:appinfo>
					<!---*************************************************************************************************************************************************************-->
					<!---*************************************************************************************************************************************************************-->
					<xs:appinfo>
						<sch:pattern name="Наличие элемента УдЛичнИГ в зависимости от значения элемента ИдСтат">
							<sch:rule context="СвИнНеУч">
								<!-- Контроль наличия элемента УдЛичнИГ в зависимости от значения элемента ИдСтат -->
								<sch:assert test="usch:iif( 
						@ИдСтат='ИГ' ,
						count(УдЛичнИГ)!=0  , 
						( count(УдЛичнИГ)!=0  or  count(УдЛичнИГ)=0 ) 
						)">
									<usch:error code="0400400007" path="УдЛичнИГ" value-of-select="count(УдЛичнИГ)"> Не выполнено условие присутствия (отсутствия) элемента УдЛичнИГ при значении элемента ИдСтат, равном "<usch:value-of select="@ИдСтат"/>".  </usch:error>
								</sch:assert>
							</sch:rule>
						</sch:pattern>
					</xs:appinfo>
					<!---*************************************************************************************************************************************************************-->
					<xs:documentation>Сведения об иностранной организации (иностранном гражданине), не состоящей(ем) на учете в налоговых органах</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="СвФЛУчаст" type="СвФЛТип">
				<xs:annotation>
					<xs:documentation>Сведения о физическом лице</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="СвИПТип">
		<xs:annotation>
			<xs:documentation>Сведения об индивидуальном предпринимателе</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ФИО" type="ФИОТип">
				<xs:annotation>
					<xs:documentation>Фамилия, имя, отчество (при наличии)</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="ИНН" type="ИННФЛТип" use="required">
			<xs:annotation>
				<xs:documentation>ИНН</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ОГРНИП" type="ОГРНИПТип" use="optional">
			<xs:annotation>
				<xs:documentation>Основной государственный регистрационный номер индивидуального предпринимателя</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ИныеСвед" use="optional">
			<xs:annotation>
				<xs:documentation>Иные сведения, идентифицирующие физическое лицо</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="СвЮЛУчТип">
		<xs:annotation>
			<xs:documentation>Сведения об организации, состоящей на учете в налоговых органах</xs:documentation>
		</xs:annotation>
		<xs:attribute name="НаимОрг" use="required">
			<xs:annotation>
				<xs:documentation>Наименование полное</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="1000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ИННЮЛ" type="ИННЮЛТип" use="required">
			<xs:annotation>
				<xs:documentation>ИНН</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="КПП" type="КППТип" use="optional">
			<xs:annotation>
				<xs:documentation>КПП</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="СвИнНеУчТип">
		<xs:annotation>
			<xs:documentation>Сведения об иностранной организации (иностранном гражданине), не состоящей(ем) на учете в налоговых органах</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="УдЛичнИГ" type="УдЛичнИГТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Данные документа, удостоверяющего личность иностранного гражданина</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="ИдСтат" use="required">
			<xs:annotation>
				<xs:documentation>Идентификация статуса</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="25"/>
					<xs:enumeration value="ИО"/>
					<xs:enumeration value="ИГ"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Стран" use="optional">
			<xs:annotation>
				<xs:documentation>Страна</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Наим" use="optional">
			<xs:annotation>
				<xs:documentation>Наименование иностранной организации полное /Фамилия, имя, отчество (при наличии) иностранного гражданина</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="1000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Идентиф" use="optional">
			<xs:annotation>
				<xs:documentation>Идентификатор иностранной организации (иностранного гражданина)</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ИныеСвед" use="optional">
			<xs:annotation>
				<xs:documentation>Иные сведения, идентифицирующие иностранную организацию (иностранного гражданина)</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="СвФЛТип">
		<xs:annotation>
			<xs:documentation>Сведения о физическом лице</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ФИО" type="ФИОТип">
				<xs:annotation>
					<xs:documentation>Фамилия, имя, отчество (при наличии)</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="ИННФЛ" type="ИННФЛТип" use="required">
			<xs:annotation>
				<xs:documentation>ИНН физического лица</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ИныеСвед" use="optional">
			<xs:annotation>
				<xs:documentation>Иные сведения, идентифицирующие физическое лицо</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="УдЛичнИГТип">
		<xs:annotation>
			<xs:documentation>Данные документа, удостоверяющего личность иностранного гражданина</xs:documentation>
		</xs:annotation>
		<xs:attribute name="ВидДок" use="required">
			<xs:annotation>
				<xs:documentation>Вид документа</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="1000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="НомДок" use="required">
			<xs:annotation>
				<xs:documentation>Номер документа</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="100"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ДатаДок" type="ДатаТип" use="required">
			<xs:annotation>
				<xs:documentation>Дата выдачи документа</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ПодписантТип">
		<xs:annotation>
			<xs:documentation>Сведения о лице, подписывающем информацию отправителя в электронной форме</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ФИО" type="ФИОТип">
				<xs:annotation>
					<xs:documentation>Фамилия, имя, отчество (при наличии)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="СвДоверЭл" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Сведения о доверенности в машиночитаемом виде, используемой для подтверждения полномочий</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="НомДовер" use="required">
						<xs:annotation>
							<xs:documentation>Номер доверенности</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:length value="36"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="ДатаДовер" type="ДатаТип" use="required">
						<xs:annotation>
							<xs:documentation>Дата совершения доверенности</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="ВнНомДовер" use="optional">
						<xs:annotation>
							<xs:documentation>Внутренний регистрационный номер доверенности</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
								<xs:maxLength value="50"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="ДатаВнРегДовер" type="ДатаТип" use="optional">
						<xs:annotation>
							<xs:documentation>Дата внутренней регистрации доверенности</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="ИдСистХран" use="required">
						<xs:annotation>
							<xs:documentation>Идентифицирующая информация об информационной системе, в которой осуществляется хранение доверенности, необходимая для запроса информации из такой информационной системы</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
								<xs:maxLength value="500"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="СвДоверБум" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Сведения о доверенности в бумажном виде, используемой для подтверждения полномочий</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ФИО" type="ФИОТип" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Фамилия, имя, отчество (при наличии) лица, подписавшего доверенность</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="ДатаДовер" type="ДатаТип" use="required">
						<xs:annotation>
							<xs:documentation>Дата совершения доверенности</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="ВнНомДовер" use="required">
						<xs:annotation>
							<xs:documentation>Внутренний регистрационный номер доверенности</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
								<xs:maxLength value="50"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="СвИдДовер" use="optional">
						<xs:annotation>
							<xs:documentation>Сведения, идентифицирующие доверителя</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
								<xs:maxLength value="1000"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Должн" use="optional">
			<xs:annotation>
				<xs:documentation>Должность</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ТипПодпис" use="optional">
			<xs:annotation>
				<xs:documentation>Тип подписи</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="1"/>
					<xs:enumeration value="1"/>
					<xs:enumeration value="2"/>
					<xs:enumeration value="3"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="СпосПодтПолном" use="required">
			<xs:annotation>
				<xs:documentation>Способ подтверждения полномочий на подписание документа</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="1"/>
					<xs:enumeration value="1"/>
					<xs:enumeration value="2"/>
					<xs:enumeration value="3"/>
					<xs:enumeration value="4"/>
					<xs:enumeration value="5"/>
					<xs:enumeration value="6"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ДопСведПодп" use="optional">
			<xs:annotation>
				<xs:documentation>Дополнительные сведения</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ИнфПолТип">
		<xs:annotation>
			<xs:documentation>Информационное поле</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ТекстИнф" type="ТекстИнфТип" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Текстовая информация</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="ИдФайлИнфПол" use="optional">
			<xs:annotation>
				<xs:documentation>Идентификатор файла информационного поля</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="36"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ТекстИнфТип">
		<xs:annotation>
			<xs:documentation>Текстовая информация</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Идентиф" use="required">
			<xs:annotation>
				<xs:documentation>Идентификатор</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Значение" use="required">
			<xs:annotation>
				<xs:documentation>Значение</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="2000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="АдресПользТип">
		<xs:annotation>
			<xs:documentation>Сведения об адресе</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ГЛН" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Глобальный номер места нахождения (GLN места)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="13"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Коорд" type="КоордТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Координаты места</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Адрес" type="АдресТип">
				<xs:annotation>
					<xs:documentation>Сведения об адресе местонахождения</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="АдрКоммент" use="optional">
			<xs:annotation>
				<xs:documentation>Комментарии к адресу</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="2000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="КоордТип">
		<xs:annotation>
			<xs:documentation>Координаты места</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Широта" use="required">
			<xs:annotation>
				<xs:documentation>Широта </xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="15"/>
					<xs:maxLength value="17"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Долгота" use="required">
			<xs:annotation>
				<xs:documentation>Долгота</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="15"/>
					<xs:maxLength value="18"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="АдресТип">
		<xs:annotation>
			<xs:documentation>Адрес местонахождения</xs:documentation>
		</xs:annotation>
		<xs:choice>
			<xs:element name="АдрРФ" type="АдрРФТип">
				<xs:annotation>
					<xs:documentation>Адрес, указанный в Едином государственном реестре юридических лиц/почтовый адрес/адрес места жительства индивидуального предпринимателя (реквизиты адреса на территории Российской Федерации)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="АдрФИАС" type="АдрФИАСТип">
				<xs:annotation>
					<!---**************************************************************************************************************************************************************************-->
					<xs:appinfo>
						<sch:pattern name="Проверка присутствия (отсутствия) элемента МуниципРайон в зависимости от значения элемента Регион">
							<sch:rule context="АдрФИАС">
								<sch:assert test="usch:iif(
								Регион=99, 
								count(МуниципРайон)=0, 
								count(МуниципРайон)!=0
								)">
									<usch:error code="0400300003" path="МуниципРайон" value-of-select="Регион">Не выполнено условие присутствия (отсутствия) элемента МуниципРайон при значении элемента Регион, равном "<usch:value-of select="Регион"/>" </usch:error>
								</sch:assert>
							</sch:rule>
						</sch:pattern>
					</xs:appinfo>
					<!---**************************************************************************************************************************************************************************-->
					<xs:documentation>Адрес по ФИАС, указанный в Едином государственном реестре юридических лиц/почтовый адрес/адрес места жительства индивидуального предпринимателя (реквизиты адреса на территории Российской Федерации)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="АдрИнф" type="АдрИнфТип">
				<xs:annotation>
					<xs:documentation>Адрес, указанный в Едином государственном реестре юридических лиц/почтовый адрес/адрес места жительства индивидуального предпринимателя (информация об адресе, в том числе об адресе за пределами территории Российской Федерации)</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="АдрРФТип">
		<xs:annotation>
			<xs:documentation>Сведения об адресе в Российской Федерации, содержащиеся в ЕГРЮЛ</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Индекс" use="required">
			<xs:annotation>
				<xs:documentation>Почтовый индекс</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="6"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="КодРегион" type="СCРФТип" use="required">
			<xs:annotation>
				<xs:documentation>Код субъекта Российской Федерации</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Район" use="optional">
			<xs:annotation>
				<xs:documentation>Район</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Город" use="optional">
			<xs:annotation>
				<xs:documentation>Город</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="НаселПункт" use="optional">
			<xs:annotation>
				<xs:documentation>Населенный пункт</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Улица" use="optional">
			<xs:annotation>
				<xs:documentation>Улица</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Дом" use="optional">
			<xs:annotation>
				<xs:documentation>Дом</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="20"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Корпус" use="optional">
			<xs:annotation>
				<xs:documentation>Корпус</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="20"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Кварт" use="optional">
			<xs:annotation>
				<xs:documentation>Квартира</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="20"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ИныеСвед" use="optional">
			<xs:annotation>
				<xs:documentation>Иные сведения об адресе в Российской Федерации</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="1000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="АдрФИАСТип">
		<xs:annotation>
			<xs:documentation>Адрес по ФИАС</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Регион" type="СCРФТип">
				<xs:annotation>
					<xs:documentation>Субъект Российской Федерации (код)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="МуниципРайон" type="ВидНаимКодТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Муниципальный район/городской округ/внутригородская территория города федерального значения/муниципальный округ/федеральная территория</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ГородСелПоселен" type="ВидНаимКодТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Городское поселение/сельское поселение/межселенная территория в составе муниципального района/внутригородской район городского округа</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="НаселенПункт" type="ВидНаимТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Населенный пункт (город, деревня, село и прочее)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ЭлПланСтруктур" type="ТипНаимТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Элемент планировочной структуры</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ЭлУлДорСети" type="ТипНаимТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Элемент улично-дорожной сети</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ЗемелУчасток" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Земельный участок (номер)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Здание" type="НомерТип" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Здание / сооружение/объект незавершенного строительства</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ПомещЗдания" type="НомерТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Помещение в пределах здания, сооружения/машино-место</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ПомещКвартиры" type="НомерТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Помещение в пределах квартиры</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="ИдНом" use="optional">
			<xs:annotation>
				<xs:documentation>Уникальный идентификационный номер</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="36"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Индекс" use="optional">
			<xs:annotation>
				<xs:documentation>Почтовый индекс</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="6"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ВидНаимКодТип">
		<xs:annotation>
			<xs:documentation>Сведения о виде (код) и наименовании адресного элемента</xs:documentation>
		</xs:annotation>
		<xs:attribute name="ВидКод" use="required">
			<xs:annotation>
				<xs:documentation>Вид (код) элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="1"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Наим" use="required">
			<xs:annotation>
				<xs:documentation>Наименование элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ВидНаимТип">
		<xs:annotation>
			<xs:documentation>Сведения о виде и наименовании адресного элемента</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Вид" use="required">
			<xs:annotation>
				<xs:documentation>Вид элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Наим" use="required">
			<xs:annotation>
				<xs:documentation>Наименование элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ТипНаимТип">
		<xs:annotation>
			<xs:documentation>Сведения о типе и наименовании адресного элемента</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Тип" use="required">
			<xs:annotation>
				<xs:documentation>Тип элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Наим" use="required">
			<xs:annotation>
				<xs:documentation>Наименование элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="НомерТип">
		<xs:annotation>
			<xs:documentation>Сведения о номере адресного элемента</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Тип" use="required">
			<xs:annotation>
				<xs:documentation>Тип элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Номер" use="required">
			<xs:annotation>
				<xs:documentation>Номер элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="АдрИнфТип">
		<xs:annotation>
			<xs:documentation>Информация об адресе, в том числе об адресе за пределами территории Российской Федерации</xs:documentation>
		</xs:annotation>
		<xs:attribute name="КодСтр" type="ОКСМТип" use="required">
			<xs:annotation>
				<xs:documentation>Код страны</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="АдрТекст" use="required">
			<xs:annotation>
				<xs:documentation>Адрес</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="1000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="КонтактТип">
		<xs:annotation>
			<xs:documentation>Контактные данные</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Тлф" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Номер контактного телефона/факс</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ЭлПочта" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Адрес электронной почты</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ИнКонт" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Иные контактные данные</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ФИОТип">
		<xs:annotation>
			<xs:documentation>Фамилия, имя, отчество физического лица</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Фамилия" use="required">
			<xs:annotation>
				<xs:documentation>Фамилия</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="60"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Имя" use="required">
			<xs:annotation>
				<xs:documentation>Имя</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="60"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Отчество" use="optional">
			<xs:annotation>
				<xs:documentation>Отчество</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="60"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="ИННЮЛТип">
		<xs:annotation>
			<xs:documentation>Идентификационный номер налогоплательщика - организации</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="10"/>
			<xs:pattern value="([0-9]{1}[1-9]{1}|[1-9]{1}[0-9]{1})[0-9]{8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ИННФЛТип">
		<xs:annotation>
			<xs:documentation>Идентификационный номер налогоплательщика - физического лица</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="12"/>
			<xs:pattern value="([0-9]{1}[1-9]{1}|[1-9]{1}[0-9]{1})[0-9]{10}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="КППТип">
		<xs:annotation>
			<xs:documentation>Код причины постановки на учет (КПП) - 5 и 6 знаки от 0-9 и A-Z</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="9"/>
			<xs:pattern value="([0-9]{1}[1-9]{1}|[1-9]{1}[0-9]{1})([0-9]{2})([0-9A-Z]{2})([0-9]{3})"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="КНДТип">
		<xs:annotation>
			<xs:documentation>Код из Классификатора налоговой документации</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="7"/>
			<xs:pattern value="[0-9]{7}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ОГРНИПТип">
		<xs:annotation>
			<xs:documentation>Основной государственный регистрационный номер индивидуального предпринимателя</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="15"/>
			<xs:pattern value="[0-9]{15}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ОГРНТип">
		<xs:annotation>
			<xs:documentation>Основной государственный регистрационный номер юридического лица  </xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="13"/>
			<xs:pattern value="[0-9]{13}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="СCРФТип">
		<xs:annotation>
			<xs:documentation>Код из Справочника субъектов Российской Федерации </xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="2"/>
			<xs:pattern value="[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="СПДУЛТип">
		<xs:annotation>
			<xs:documentation>Коды Справочника видов документов, удостоверяющих личность налогоплательщика</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="2"/>
			<xs:pattern value="[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="СПДУЛШТип">
		<xs:annotation>
			<xs:documentation>Шаблон серии, номера из Справочника видов документов, удостоверяющих личность налогоплательщика</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="25"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ОКСМТип">
		<xs:annotation>
			<xs:documentation>Код из Общероссийского классификатора стран мира</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="3"/>
			<xs:pattern value="[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ВремяТип">
		<xs:annotation>
			<xs:documentation>Время в формате ЧЧ:ММ:СС</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="8"/>
			<xs:pattern value="([0-1]{1}[0-9]{1}|2[0-3]{1}):([0-5]{1}[0-9]{1}):([0-5]{1}[0-9]{1})"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ДатаВремяВЗТип">
		<xs:annotation>
			<xs:documentation>Дата и время в формате ДД.ММ.ГГГГTЧЧ:ММ:CC+-ЧЧ:ММ</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="25"/>
			<xs:pattern value="(((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\.(01|0[3-9]{1}|1[0-2]{1}))|(31\.(01|03|05|07|08|10|12)))\.((19|20)[0-9]{2}))|(29\.02\.((19|20)(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6))))))([T]([0-1]{1}[0-9]{1}|2[0-3]{1}):([0-5]{1}[0-9]{1}):([0-5]{1}[0-9]{1})([+|-]([01][0-9])[:]([0-5][0-9])))"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ДатаТип">
		<xs:annotation>
			<xs:documentation>Дата в формате ДД.ММ.ГГГГ (01.01.1900 - 31.12.2099)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="10"/>
			<xs:pattern value="(((0[1-9]{1}|[1-2]{1}[0-9]{1})\.(0[1-9]{1}|1[0-2]{1}))|((30)\.(01|0[3-9]{1}|1[0-2]{1}))|((31)\.(01|03|05|07|08|10|12)))\.(19[0-9]{2}|20[0-9]{2})"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
