application: authentication
repo: app_platform_authentication
resources:
  limits:
    cpu: '1'
    memory: 2G
  requests:
    cpu: '1'
    memory: 2G
port:
  http:
    number: 8001
    name: authentication
    target: 8080
routing:
  match:
    prefix: /api/auth
  rewrite:
    uri: ' '
secman:
  type: built_in
profiles: kafka,kafka-ssl,authentication
additional:
  envs:
    - name: SPRING_CLOUD_CONFIG_URI
      value: 'http://http-config-server:8080'
  configMap:
    - name: kafka-ssl
      data:
        application-kafka-ssl.yml: |-
          spring:
            cloud:
              vault:
                namespace: CI02351878_CI02671580
                authentication: kubernetes
                kubernetes:
                  role: ci02351878-edevgen-sbertransport-dev
                  kubernetes-path: os/dev-terra000003-ids.ocp.delta.sbrf.ru
                enabled: true
                port: 443
                host: t.secrets.delta.sbrf.ru
            config:
              import: 
                - optional:vault://A/TRANSP/OSH/MAIN/KV/ci02351878-edevgen-sbertransport-dev/application,kafka-ssl
    - name: authentication
      data:
        application-authentication.yml: |-
          spring:
            cloud:
              vault:
                namespace: CI02351878_CI02671580
                authentication: kubernetes
                kubernetes:
                  role: ci02351878-edevgen-sbertransport-dev
                  kubernetes-path: os/dev-terra000003-ids.ocp.delta.sbrf.ru
                enabled: true
                port: 443
                host: t.secrets.delta.sbrf.ru
            config:
              import: 
                - optional:vault://A/TRANSP/OSH/MAIN/KV/ci02351878-edevgen-sbertransport-dev/authentication
  volumes:
    - name: kafka-ssl
      configMap:
        name: kafka-ssl
        defaultMode: 420
    - name: authentication
      configMap:
        name: authentication
        defaultMode: 420
  mounts:
    - name: kafka-ssl
      mountPath: /app/resources/application-kafka-ssl.yml
      subPath: application-kafka-ssl.yml
    - name: authentication
      mountPath: /app/resources/application-authentication.yml
      subPath: application-authentication.yml
