<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ru.sber.transport.tariff</groupId>
        <artifactId>parent</artifactId>
        <version>5.8</version>
    </parent>

    <artifactId>application</artifactId>

    <properties>
        <protoc.plugins>target/mvn/grpc</protoc.plugins>
        <server.port>8005</server.port>
        <start-class>ru.sberbank.ditsib.transport.tariff.TariffApplication</start-class>
        <proto.source.root>src/main/resources/proto</proto.source.root>
        <hibernate.jpamodelgen.version>5.6.15.Final</hibernate.jpamodelgen.version>
    </properties>

    <dependencies>

        <!-- Spring -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>http-request-check-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>role-check-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.contractor</groupId>
            <artifactId>messaging</artifactId>
            <version>4.11</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.corporate</groupId>
            <artifactId>messaging</artifactId>
            <version>4.8</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.geo-zones</groupId>
            <artifactId>messaging</artifactId>
            <version>4.9</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>tariff-messaging</artifactId>
            <version>250527-1</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.geo</groupId>
            <artifactId>grpc</artifactId>
            <version>3.20</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>tariff-grpc</artifactId>
            <version>250527-1</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.limits</groupId>
            <artifactId>grpc</artifactId>
            <version>4.2</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>properties-loader</artifactId>
        </dependency>

        <!-- Database -->
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>documentation-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.geo-zones</groupId>
            <artifactId>grpc</artifactId>
            <version>4.9</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.grpc</groupId>
            <artifactId>client</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>audit</artifactId>
        </dependency>

        <!-- Utils -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>file-works</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>extended-rest-template</artifactId>
        </dependency>
        <dependency>
            <groupId>net.javacrumbs.shedlock</groupId>
            <artifactId>shedlock-spring</artifactId>
        </dependency>
        <dependency>
            <groupId>net.javacrumbs.shedlock</groupId>
            <artifactId>shedlock-provider-jdbc-template</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-vault-config</artifactId>
        </dependency>

        <!-- project -->
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>authorization</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>transport-core</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>core</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.service-discovery</groupId>
            <artifactId>starter</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>scripting</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>human-readable-generator</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.grpc</groupId>
            <artifactId>server</artifactId>
        </dependency>
        <dependency>
            <groupId>io.hypersistence</groupId>
            <artifactId>hypersistence-utils-hibernate-63</artifactId>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-test-binder</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>embedded-postgres</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.instancio</groupId>
            <artifactId>instancio-junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.github.ascopes</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <release>${maven.compiler.target}</release>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <dependency>
                            <groupId>org.hibernate</groupId>
                            <artifactId>hibernate-jpamodelgen-jakarta</artifactId>
                            <version>${hibernate.jpamodelgen.version}</version>
                        </dependency>
                    </annotationProcessorPaths>
                    <fork>true</fork>
                    <compilerArgs>
                        <compilerArg>
                            -Amapstruct.defaultComponentModel=spring
                        </compilerArg>
                        <compilerArg>
                            -Amapstruct.defaultInjectionStrategy=constructor
                        </compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
