<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>ru.sber.transport.notifications</groupId>
        <artifactId>parent</artifactId>
        <version>${release.version}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>application</artifactId>

    <description>Service for sending notifications</description>

    <properties>
        <server.port>8017</server.port>
        <start-class>ru.sber.transport.notifications.NotificationsApplication</start-class>
        <avro.source.path>../_documents/api/avro</avro.source.path>
        <tomcat.version>10.1.42</tomcat.version>
        <proto.source.root>../_documents/api/grpc</proto.source.root>
    </properties>

    <dependencies>
        <!-- Spring -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-vault-config</artifactId>
        </dependency>

        <!-- Jackson -->
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>role-check-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.contractor</groupId>
            <artifactId>messaging</artifactId>
            <version>3.18</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>request-messaging</artifactId>
            <version>240426-1</version>
            <exclusions>
                <exclusion>
                    <groupId>ru.sberbank.ditsib</groupId>
                    <artifactId>kafka</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ru.sber.transport</groupId>
                    <artifactId>kafka-functional</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.dispatcher</groupId>
            <artifactId>messaging</artifactId>
            <version>4.12</version>
            <exclusions>
                <exclusion>
                    <groupId>ru.sberbank.ditsib</groupId>
                    <artifactId>kafka</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ru.sber.transport</groupId>
                    <artifactId>kafka-functional</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.corporate</groupId>
            <artifactId>messaging</artifactId>
            <version>4.6.0.3</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>kafka-functional</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.service-discovery</groupId>
            <artifactId>starter</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>limits-messaging</artifactId>
            <version>230407-4</version>
            <exclusions>
                <exclusion>
                    <groupId>ru.sber.transport</groupId>
                    <artifactId>kafka-functional</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>deadline-messaging</artifactId>
            <version>230727-1</version>
            <exclusions>
                <exclusion>
                    <groupId>ru.sber.transport</groupId>
                    <artifactId>kafka-functional</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>approvals-messaging</artifactId>
            <version>230228-1</version>
            <exclusions>
                <exclusion>
                    <groupId>ru.sber.transport</groupId>
                    <artifactId>kafka-functional</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>tariff-messaging</artifactId>
            <version>231115-1</version>
            <exclusions>
                <exclusion>
                    <groupId>ru.sber.transport</groupId>
                    <artifactId>kafka-functional</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.roles</groupId>
            <artifactId>messaging</artifactId>
            <version>231030-2</version>
            <exclusions>
                <exclusion>
                    <groupId>ru.sber.transport</groupId>
                    <artifactId>kafka-functional</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.email</groupId>
            <artifactId>messaging</artifactId>
            <version>231110-1</version>
            <exclusions>
                <exclusion>
                    <groupId>ru.sber.transport</groupId>
                    <artifactId>kafka-functional</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>sms-messaging</artifactId>
            <version>230419-1</version>
            <exclusions>
                <exclusion>
                    <groupId>ru.sber.transport</groupId>
                    <artifactId>kafka-functional</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.push</groupId>
            <artifactId>messaging</artifactId>
            <version>4.4.0.1</version>
            <exclusions>
                <exclusion>
                    <groupId>ru.sber.transport</groupId>
                    <artifactId>kafka-functional</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-client</artifactId>
        </dependency>

        <!-- Database -->
        <dependency>
            <groupId>io.hypersistence</groupId>
            <artifactId>hypersistence-utils-hibernate-63</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
        </dependency>

        <!-- Utils -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>transport-core</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>enums</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>authorization</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>documentation-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>properties-loader</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.sber.transport.grpc</groupId>
            <artifactId>server</artifactId>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>embedded-postgres</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-test-binder</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.notifications</groupId>
            <artifactId>business</artifactId>
            <version>4.7.1</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>ru.sber.transport.grpc</groupId>
            <artifactId>test</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <finalName>notifications</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <release>${maven.compiler.target}</release>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <dependency>
                            <groupId>org.hibernate</groupId>
                            <artifactId>hibernate-jpamodelgen-jakarta</artifactId>
                            <version>5.6.15.Final</version>
                        </dependency>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>-Amapstruct.defaultComponentModel=spring</compilerArg>
                        <compilerArg>-Amapstruct.defaultInjectionStrategy=constructor</compilerArg>
                        <compilerArg>-Amapstruct.defaultInjectionStrategy=constructor</compilerArg>
                        <compilerArg>-Amapstruct.verbose=true</compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.github.ascopes</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
