ALTER TABLE CONTRACTORS.DRIVER_TAG
    DROP COLUMN is_active;

CREATE UNIQUE INDEX IF NOT EXISTS DRIVER_TAG_CONTRACTOR_UNIQUE_INDEX
    ON CONTRACTORS.DRIVER_TAG(NAME, CONTRACTOR_ID);

COMMENT ON INDEX CONTRACTORS.DRIVER_TAG_CONTRACTOR_UNIQUE_INDEX IS 'Уникальность признака водителя в рамках контрагента';
