application: dispatcher
repo: app_platform_dispatcher
resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 500m
    memory: 1G
port:
  http:                                             # Не добавлять если нет. Если указано, добавит service с описанием http
    number: 8080
    name: dispatcher
    target: 8080
  grpc:                                             # Не добавлять если нет. Если указано, добавит service с описанием http
    number: 6565
    name: dispatcher
routing:
  match:
    prefix: /api/dispatcher-room
  rewrite:
    uri: ' '
profiles: prod,kafka
secman:
  type: built_in
additional:
  envs:
    - name: KAFKA_BROKERS
      valueFrom:
        configMapKeyRef:
          name: kafka
          key: brokers
    - name: FILE_MAX_SIZE
      valueFrom:
        configMapKeyRef:
          name: files
          key: image.size.max
    - name: STAFF_LIMIT
      valueFrom:
        configMapKeyRef:
          name: dispatcher-service
          key: contractor.staff.limit
    - name: JWKS_URI
      value: 'http://jwks:8080'
    - name: SCHEMA_REGISTRY_URL
    - name: SPRING_PROFILES_INCLUDE
      value: secman
    - name: SPRING_CLOUD_CONFIG_URI
      value: 'http://http-config-server:8080'
    - name: SSL_KAFKA_BROKERS
      valueFrom:
        configMapKeyRef:
          name: kafka
          key: brokers
    - name: KAFKA_SECURITY_PROTOCOL
      value: PLAINTEXT
    - name: KAFKA_SSL_KEYSTORE_LOCATION
      value: /vault/secrets/kafka-keystore.jks
    - name: KAFKA_SSL_TRUSTSTORE_LOCATION
      value: /vault/secrets/kafka-truststore.jks