export enum CreateRequestLinks {
  purpose = 'purpose',
  purposeMessage = 'purposeMessage',
  purposePlaceholder = 'purposePlaceholder',
  purposeDateWarning = 'purposeDateWarning',
  addWaypoint = 'addWaypoint',
  save = 'save',
  order = 'order',
  join = 'join',
  findCoopTrip = 'findCoopTrip',
  goNow = 'goNow',
  planTrip = 'planTrip',
  noSuitableTrips = 'noSuitableTrips',
  noSuitableTripsSearch = 'noSuitableTripsSearch',
  additional = 'additional',
  suitableOpportunity = 'suitableOpportunity',

  chooseDateAndTime = 'chooseDateAndTime',
  cooperateType = 'cooperate',
  individualType = 'individual',
  tripType = 'tripType',
  coworkersCount = 'coworkersCount',
  iWillGo = 'iWillGo',
  coworkerWillGo = 'coworkerWillGo',
  coworkersName = 'coworkersName',
  enterCommentary = 'enterCommentary',
  preferences = 'preferences',
  choosePreferences = 'choosePreferences',
  suitableTrips = 'suitableTrips',
  landing = 'landing',
  dateAndTime = 'dateAndTime',
  tripCreator = 'tripCreator',
  mobilePhone = 'mobilePhone',
  economy = 'economy',
  tripStartsFrom = 'tripStartsFrom',
  createForAnother = 'createForAnother',
}

export const CreateRequestLinksTitles = {
  [CreateRequestLinks.purpose]: 'Цель поездки',
  [CreateRequestLinks.purposeMessage]: 'Пожалуйста, выберите цель поездки',
  [CreateRequestLinks.purposePlaceholder]: 'Выберите цель поездки',
  [CreateRequestLinks.purposeDateWarning]: 'Укажите дату, не противоречащую условиям выбранной цели поездки',
  [CreateRequestLinks.addWaypoint]: 'Добавить точку назначения',
  [CreateRequestLinks.save]: 'Сохранить',
  [CreateRequestLinks.order]: 'Заказать',
  [CreateRequestLinks.join]: 'Присоединиться',
  [CreateRequestLinks.findCoopTrip]: 'Найти совместную поездку',
  [CreateRequestLinks.goNow]: 'Поеду сейчас',
  [CreateRequestLinks.planTrip]: 'Запланирую поездку',
  [CreateRequestLinks.noSuitableTrips]:
    // eslint-disable-next-line max-len
    'К сожалению, подходящие по вашим параметрам поездки не найдены. Создайте совместную поездку и ожидайте присоединения к ней других участников.',
  [CreateRequestLinks.suitableOpportunity]:
    'Вы можете разделить поездку с кем-то. Выберите, сколько мест в машине вы бронируете:',
  [CreateRequestLinks.noSuitableTripsSearch]: 'Для поиска совместной поездки должны быть выбраны: маршрут и цель',
  [CreateRequestLinks.additional]: 'Дополнительно',
  [CreateRequestLinks.chooseDateAndTime]: 'Выберите дату и время',
  [CreateRequestLinks.cooperateType]: 'Совместная',
  [CreateRequestLinks.individualType]: 'Индивидуальная',
  [CreateRequestLinks.tripType]: 'Тип поездки',
  [CreateRequestLinks.coworkersCount]: 'Количество коллег',
  [CreateRequestLinks.iWillGo]: 'Поеду сам',
  [CreateRequestLinks.coworkerWillGo]: 'Поедет коллега',
  [CreateRequestLinks.coworkersName]: 'Как зовут коллегу?',
  [CreateRequestLinks.enterCommentary]: 'Введите текст комментария',
  [CreateRequestLinks.preferences]: 'Предпочтения',
  [CreateRequestLinks.choosePreferences]: 'Выберите предпочтения',
  [CreateRequestLinks.suitableTrips]: 'Cовместные поездки',
  [CreateRequestLinks.landing]: 'Посадка',
  [CreateRequestLinks.dateAndTime]: 'Дата и время: ',
  [CreateRequestLinks.tripCreator]: 'Инициатор поездки: ',
  [CreateRequestLinks.mobilePhone]: 'Номер телефона: ',
  [CreateRequestLinks.economy]: 'Экономия: ',
  [CreateRequestLinks.tripStartsFrom]: 'Отправление от: ',
  [CreateRequestLinks.createForAnother]: 'Заказать коллеге',
};
