spring:
  cloud:
    stream:
      bindings:
        geoZoneSource-out-0:
          destination: service.geo.zones
          binder: kafka
        grpcInternalConfigurator-in-0:
          destination: configuration.grpc
          group: ${spring.application.name}
          binder: kafka
