create schema request;
comment on schema request is 'Заявки';

create table request.department
(
    id              uuid                      not null
        constraint department_pkey
            primary key,
    organization_id uuid,
    parent_id       uuid,
    department_name varchar(255) default ''::character varying,
    structure_path  varchar(255) default ''::character varying,
    location        varchar(255),
    department_head uuid,
    humanreadableid varchar(100),
    active          boolean      default true not null
);

comment on column request.department.humanreadableid is 'Уникальный идентификатор (человекочитаемый ID)';

comment on column request.department.active is 'Флаг активности(неудаленности)';

create table request.employee
(
    id                          uuid                 not null
        constraint employee_pkey
            primary key,
    first_name                  varchar(255),
    last_name                   varchar(255),
    patronymic                  varchar(255),
    personnel_number            varchar(255),
    user_id                     uuid,
    department_id               uuid,
    position_id                 uuid,
    supervisor_id               uuid,
    humanreadableid             varchar(100)
        constraint ux_employee_1
            unique,
    active                      boolean default true not null,
    mobile_phone                varchar(255),
    cost_center                 varchar(256),
    itinerant_type              varchar(256),
    marriage_certificate_number varchar(512)
);

comment on column request.employee.humanreadableid is 'Уникальный идентификатор (человекочитаемый ID)';

comment on column request.employee.active is 'Флаг активности(неудаленности)';

comment on column request.employee.mobile_phone is 'Мобильный телефон';

comment on column request.employee.cost_center is 'Место возникновения затрат';

comment on column request.employee.itinerant_type is 'Тип разъездного характера сотрудника';

comment on column request.employee.marriage_certificate_number is 'Номер свидетельства о браке';

create table request.expected
(
    id       uuid not null
        constraint expected_pkey
            primary key,
    cost     double precision,
    distance double precision,
    time     bigint
);

create table request.address
(
    building                 varchar(255),
    city                     varchar(255),
    country                  varchar(255),
    house                    varchar(255),
    latitude                 double precision                not null,
    longitude                double precision                not null,
    region                   varchar(255),
    street                   varchar(255),
    structure                varchar(255),
    id                       uuid not null
        constraint address_pk
            primary key,
    exist_in_vsp_tb_registry boolean
);

comment on column request.address.exist_in_vsp_tb_registry is 'Адрес найден в реестре ВСП/ГОСБ/ТБ';

create table request.organization
(
    id       uuid                 not null
        constraint organization_pkey
            primary key,
    digit_id numeric,
    active   boolean default true not null
);

comment on column request.organization.digit_id is 'Уникальный идентификатор (числовой ID)';

comment on column request.organization.active is 'Флаг активности(неудаленности)';

create table request.position
(
    id              uuid                 not null
        constraint position_pkey
            primary key,
    position_name   varchar(255)         not null,
    self_approved   boolean,
    organization_id uuid                 not null,
    active          boolean default true not null
);

comment on column request.position.active is 'Флаг активности(неудаленности)';

create table request.position_taxi_classes
(
    position_id uuid not null
        constraint fk_position_taxi_class
            references request.position,
    taxi_class  varchar(255)
);

create table request.trip_purpose
(
    id           integer generated by default as identity,
    purpose      varchar(255)         not null,
    active       boolean default true not null,
    organization uuid,
    id_uuid      uuid                 not null
        constraint trip_purpose_pkey
            primary key
);

create table request.waypoint
(
    address_id             uuid                               not null
        constraint waypoint_address_fk
            references request.address,
    ordering_index         integer,
    wait_time              bigint,
    id                     uuid    not null
        constraint waypoint_pk
            primary key,
    request_id             uuid                               not null,
    checkin_automatic      boolean default false,
    checkin_manual         boolean default false,
    radius                 integer default 0,
    absence_reason         varchar(500),
    checkin_automatic_time timestamp,
    checkin_manual_time    timestamp,
    checkin_only_manual    boolean default false,
    active                 boolean default true,
    constraint waypoint_uk
        unique (request_id, address_id, ordering_index)
);

comment on column request.waypoint.checkin_automatic is 'Статус автоматического чекина';

comment on column request.waypoint.checkin_manual is 'Статус ручного чекина';

comment on column request.waypoint.radius is 'Радиус поиска';

comment on column request.waypoint.absence_reason is 'Причина отсутствия';

comment on column request.waypoint.checkin_automatic_time is 'Время автоматического чекина';

comment on column request.waypoint.checkin_manual_time is 'Время ручного чекина';

comment on column request.waypoint.checkin_only_manual is 'Режим подтверждения прибытия в точку маршрута';

comment on column request.waypoint.active is 'Точка активна';

create table request.transport_type
(
    id   uuid         not null
        constraint transport_type_pkey
            primary key,
    name varchar(255) not null
);

create table request.request
(
    id                    uuid                                                      not null
        constraint request_pkey
            primary key,
    approval_date         timestamp,
    approval_state        varchar(255),
    coop_trip             boolean,
    creation_time         timestamp,
    desired_date          timestamp                                                 not null,
    limit_id              uuid,
    passenger_count       integer,
    request_status        varchar(255),
    tariff_id             uuid,
    trip_class            varchar(255),
    approved_by_id        uuid
        constraint fk_request_approved
            references request.employee,
    author_id             uuid                                                      not null
        constraint fk_request_author
            references request.employee,
    expected_id           uuid
        constraint fk_request_expected
            references request.expected,
    passenger_id          uuid                                                      not null
        constraint fk_request_passenger
            references request.employee,
    purpose_id            integer,
    comment               varchar(255),
    transport_type_id     uuid default '7f18ce71-99a7-47b5-b285-335058c6715c'::uuid not null
        constraint request_transport_type_fk
            references request.transport_type,
    rating_mark           integer,
    rating_comment        varchar(255),
    rating_advantages     jsonb,
    rating_drawbacks      jsonb,
    finished_time         timestamp,
    humanreadableid       varchar(100)                                              not null
        constraint ux_request_1
            unique,
    magenta_order_id      bigint,
    shared_ride_id        bigint,
    expected_cost         double precision,
    expected_distance     double precision,
    expected_time         bigint,
    segments              jsonb,
    transport_type        varchar(255),
    trip_purpose          uuid
        constraint request_fk
            references request.trip_purpose,
    status_code           integer,
    occupied_places_count smallint,
    request_options       jsonb
);

comment on column request.request.magenta_order_id is 'Id связанного заказа в  Magenta';

comment on column request.request.shared_ride_id is 'Id связанной совместной поездки в Magenta';

comment on column request.request.segments is 'JSON с предварительными параметрами заявки';

comment on column request.request.transport_type is 'тип транспорта';

comment on column request.request.status_code is 'Код статуса';

comment on column request.request.occupied_places_count is 'Количество занятых мест в личном транспорте';

comment on column request.request.request_options is 'JSON с опциями заявки';

create table request.route_segment
(
    id             uuid not null
        constraint route_segment_pkey
            primary key,
    cost           double precision,
    distance       double precision,
    time           bigint,
    expected_id    uuid
        constraint fk_segment_expected
            references request.expected,
    ordering_index integer,
    request_id     uuid not null
        constraint route_segment_request_id_fkey
            references request.request
);

create table request.route_segment_coordinates
(
    route_segment_id uuid             not null
        constraint fk_coordinates_segment
            references request.route_segment
            on delete cascade,
    latitude         double precision not null,
    longitude        double precision not null,
    ordering_index   integer          not null,
    constraint route_segment_coordinates_pkey
        primary key (route_segment_id, ordering_index)
);

create table request.request_history
(
    id             uuid         not null
        constraint request_history_pkey
            primary key,
    change_date    timestamp    not null,
    code           integer      not null,
    comment        varchar(255),
    request_status varchar(255) not null,
    request_id     uuid         not null
        constraint fk_request_history_request
            references request.request,
    initiator_id   uuid         not null
        constraint fk_history_employee
            references request.employee
);

create table request.company_sq
(
    id         uuid                                   not null
        constraint company_sq_pkey
            primary key,
    prefix     varchar(2)                             not null,
    orgdigitid numeric                                not null,
    sq         numeric                                not null,
    dt_insert  timestamp with time zone default now() not null,
    dt_modify  timestamp with time zone default now() not null
);

comment on table request.company_sq is 'Таблица для формирования последовательностей для компаний';

comment on column request.company_sq.id is 'Уникальный идентификатор (первичный ключ)';

comment on column request.company_sq.prefix is 'Кодовое обозначение типа сущности';

comment on column request.company_sq.orgdigitid is 'ID организации (числовой)';

comment on column request.company_sq.sq is 'Порядковый номер (в рамках клиента)';

comment on column request.company_sq.dt_insert is 'Дата время вставки записи';

comment on column request.company_sq.dt_modify is 'Дата время модификации записи';

create unique index if not exists ux_company_sq_1
    on request.company_sq (prefix, orgdigitid, sq);

create unique index if not exists ux_company_sq_2
    on request.company_sq (prefix, orgdigitid);

create table request.kpi
(
    id                uuid not null
        constraint kpi_pkey
            primary key,
    total_cost        double precision,
    total_distance_km double precision,
    total_time_min    integer
);

comment on table request.kpi is 'Расчитаный Маджента KPI совместной поездки';

comment on column request.kpi.id is 'Id';

comment on column request.kpi.total_cost is 'kpi';

comment on column request.kpi.total_distance_km is 'Расчитанное общее расстояние';

comment on column request.kpi.total_time_min is 'Расчитанное общее время';

create table request.order_kpi
(
    id                uuid not null
        constraint order_kpi_pkey
            primary key,
    cost_share_part   double precision,
    order_distance_km integer,
    order_id          bigint
        constraint order_kpi_order_id_check
            check (order_id >= 0),
    ride_time_min     integer,
    savings           double precision
        constraint order_kpi_savings_check
            check (savings >= (0)::double precision),
    savings_pct       double precision
        constraint order_kpi_savings_pct_check
            check (savings_pct >= (0)::double precision),
    kpi_id            uuid
);

comment on table request.order_kpi is 'Расчитанный Magenta KPI отдельного заказа в составе совместной поездки';

comment on column request.order_kpi.id is 'Id';

comment on column request.order_kpi.cost_share_part is 'Доля стоимости заказа от общей';

comment on column request.order_kpi.order_distance_km is 'Расчитанное расстояние заказа';

comment on column request.order_kpi.order_id is 'Идентификатор заказа в Мадженте';

comment on column request.order_kpi.ride_time_min is 'Время в пути';

comment on column request.order_kpi.savings is 'Экономия';

comment on column request.order_kpi.savings_pct is 'Процент экономии';

comment on column request.order_kpi.kpi_id is 'Id родительского объекта';

create table request.shared_ride
(
    magenta_id bigint               not null
        constraint shared_ride_pkey
            primary key,
    passengers integer
        constraint shared_ride_passengers_check
            check (passengers >= 1),
    active     boolean default true not null,
    tariff_id  uuid,
    kpi        uuid
        constraint shared_ride_kpi_fkey
            references request.kpi
);

comment on table request.shared_ride is 'Точка маршрута совместной поездки';

comment on column request.shared_ride.magenta_id is 'Id';

comment on column request.shared_ride.passengers is 'Количество пассажиров';

comment on column request.shared_ride.active is 'Флаг активности';

comment on column request.shared_ride.tariff_id is 'Id используемого тарифа';

comment on column request.shared_ride.kpi is 'KPI';

create table request.magenta_waypoint
(
    id             uuid                     not null
        constraint magenta_waypoint_pkey
            primary key,
    order_id       bigint                   not null,
    ride_id        bigint                   not null
        constraint magenta_waypoint_ride_id_fkey
            references request.shared_ride,
    waypoint_id    uuid                     not null
        constraint magenta_waypoint_waypoint_id_fkey
            references request.waypoint,
    active         boolean                  not null,
    event_type     varchar(50)              not null,
    start_time     timestamp with time zone not null,
    end_time       timestamp with time zone not null,
    ordering_index integer
);

comment on column request.magenta_waypoint.id is 'Id';

comment on column request.magenta_waypoint.order_id is 'Id заказа Magenta';

comment on column request.magenta_waypoint.ride_id is 'Id совместной поездки';

comment on column request.magenta_waypoint.waypoint_id is 'Id точки маршрута';

comment on column request.magenta_waypoint.active is 'Флаг активности';

comment on column request.magenta_waypoint.event_type is 'Тип события';

comment on column request.magenta_waypoint.start_time is 'Время начала остновки';

comment on column request.magenta_waypoint.end_time is 'Время завершения остановки';

comment on column request.magenta_waypoint.ordering_index is 'Индекс в списке';

create table request.taxi_trip
(
    trip_type                 varchar(50)          not null,
    id                        uuid                 not null
        constraint taxi_trip_pkey
            primary key,
    date_time_registered      timestamp,
    organization_id           uuid                 not null
        constraint taxi_trip_organization_id_fkey
            references request.organization,
    tariff_id                 uuid                 not null,
    trip_finish_time          timestamp,
    trip_start_time           timestamp,
    shared_request_id         integer
        constraint taxi_trip_shared_request_id_fkey
            references request.shared_ride,
    request_id                uuid,
    status                    varchar(255),
    taxi_id                   varchar(50),
    trip_fact_distance        double precision,
    trip_fact_duration        bigint,
    trip_fact_price           integer,
    trip_fact_wait_time       bigint,
    trip_assignment_date_time timestamp,
    active                    boolean default true not null,
    human_readable_id         varchar(255),
    contractor_comment        varchar(255),
    resolution                varchar(2000),
    decision_code             varchar(255),
    car_brand_name            varchar(128),
    car_model                 varchar(128),
    car_color                 varchar(128),
    car_registration_number   varchar,
    time_work_start           timestamp,
    time_work_finish          timestamp,
    last_known_position_id    uuid
);

comment on table request.taxi_trip is 'Поездка на такси';

comment on column request.taxi_trip.trip_type is 'Дата и время начала поездки';

comment on column request.taxi_trip.id is 'Идентификатор';

comment on column request.taxi_trip.date_time_registered is 'Дата и время регистрации в системе исполнителя';

comment on column request.taxi_trip.organization_id is 'Идентификатор организации, к которой принадлежат пассажиры';

comment on column request.taxi_trip.trip_finish_time is 'Дата и время завершения поездки';

comment on column request.taxi_trip.shared_request_id is 'Связанная совместаная поездка';

comment on column request.taxi_trip.request_id is 'Связанная индивидуальная поездка';

comment on column request.taxi_trip.status is 'Статус из системы исполнителя';

comment on column request.taxi_trip.taxi_id is 'Идентификатор поездки в системе исполнителя';

comment on column request.taxi_trip.trip_fact_distance is 'Километраж';

comment on column request.taxi_trip.trip_fact_duration is 'Длительность поездки';

comment on column request.taxi_trip.trip_fact_price is 'Стоимость заявки';

comment on column request.taxi_trip.trip_fact_wait_time is 'Время простоя ТС';

comment on column request.taxi_trip.trip_assignment_date_time is 'Дата и время назначения водителя на заявку';

comment on column request.taxi_trip.active is 'Флаг активности(false - удалено)';

comment on column request.taxi_trip.human_readable_id is 'Человекочитаемый идентификатор';

comment on column request.taxi_trip.contractor_comment is 'Комментарий исполнителя';

comment on column request.taxi_trip.resolution is 'Решение (изменяется контрагентом)';

comment on column request.taxi_trip.decision_code is 'Код закрытия (изменяется контрагентом)';

comment on column request.taxi_trip.car_brand_name is 'Брэнд автомобиля';

comment on column request.taxi_trip.car_model is 'Модель автомобиля';

comment on column request.taxi_trip.car_color is 'Цвет автомобиля';

comment on column request.taxi_trip.car_registration_number is 'Номер автомобиля';

comment on column request.taxi_trip.time_work_start is 'Время начала работ';

comment on column request.taxi_trip.time_work_finish is 'Время  завершения работ';

create table request.waypoint_info
(
    id               uuid not null
        constraint waypoint_info_pkey
            primary key,
    fact_time_arrive timestamp,
    waypoint_id      integer,
    trip_id          uuid not null
        constraint waypoint_info_trip_id_fkey
            references request.taxi_trip
);

comment on table request.waypoint_info is 'Фактическая информация по точкам маршрута';

comment on column request.waypoint_info.id is 'Идентификатор';

comment on column request.waypoint_info.waypoint_id is 'Порядковый индекс';

comment on column request.waypoint_info.trip_id is 'Ссылка на связанную поездку';

create table request.route_history_element
(
    id        uuid             not null
        constraint route_history_element_pkey
            primary key,
    geo_time  timestamp        not null,
    latitude  double precision not null,
    longitude double precision not null,
    trip_id   uuid             not null
        constraint route_history_element_trip_id_fkey
            references request.taxi_trip
);

comment on table request.route_history_element is 'Список всех зарегистрированных положений автомобиля';

comment on column request.route_history_element.id is 'Идентификатор';

comment on column request.route_history_element.geo_time is 'Время';

comment on column request.route_history_element.latitude is 'Широта';

comment on column request.route_history_element.longitude is 'Долгота';

comment on column request.route_history_element.trip_id is 'Ссылка на связанную поездку';

alter table request.taxi_trip
    add constraint taxi_trip_last_known_position_id_fkey
        foreign key (last_known_position_id) references request.route_history_element;
DO
    $$
    BEGIN
        IF (select NOT EXISTS ( SELECT  constraint_schema, constraint_name
                                FROM    information_schema.referential_constraints
                                WHERE   constraint_schema = 'request'
                                  AND   constraint_name = 'taxi_trip_last_known_position_id_fkey'))
        THEN
            ALTER TABLE request.taxi_trip ADD CONSTRAINT taxi_trip_last_known_position_id_fkey
                foreign key (last_known_position_id) references route_history_element;
        END IF;
    END;
    $$ LANGUAGE PLPGSQL;

create table request.methods
(
    id          uuid    not null
        constraint methods_pkey
            primary key,
    name        varchar not null
        constraint methods_name_key
            unique,
    description varchar
);

comment on table request.methods is 'Информация о методах';

comment on column request.methods.id is 'ID метода';

comment on column request.methods.name is 'Наименование метода';

comment on column request.methods.description is 'Описание метода';

create table request.method_roles
(
    id        uuid not null
        constraint method_roles_pkey
            primary key,
    method_id uuid
        constraint method_roles_method_id_fkey
            references request.methods,
    role_code varchar,
    constraint method_roles_role_method_uk
        unique (method_id, role_code)
);

comment on table request.method_roles is 'Связи методов и ролей';

comment on column request.method_roles.id is 'ID связи';

comment on column request.method_roles.method_id is 'ID метода';

comment on column request.method_roles.role_code is 'Наименование роли';

create table request.corp_delegate
(
    id             uuid not null
        constraint corp_delegate_pkey
            primary key,
    start_date     date,
    end_date       date,
    delegate_id    uuid,
    supervisor_id  uuid,
    transport_type text
);

create table request.update_request
(
    id                uuid not null
        constraint update_request_pkey
            primary key,
    request_id        uuid not null,
    waypoints         jsonb,
    segments          jsonb,
    expected_cost     double precision,
    expected_distance double precision,
    expected_time     bigint
);

create table request.request_for_taxi
(
    id                       uuid                  not null
        constraint request_for_taxi_pkey
            primary key,
    humanreadableid          varchar(100)          not null
        constraint request_for_taxi_humanreadableid_key
            unique,
    author_id                uuid                  not null
        constraint fk_request_for_taxi_author
            references request.employee,
    passenger_id             uuid                  not null
        constraint fk_request_for_taxi_passenger
            references request.employee,
    creation_time            timestamp,
    transport_type           varchar(255)          not null,
    approved_by_id           uuid
        constraint fk_request_for_taxi_approved
            references request.employee,
    approval_date            timestamp,
    segments                 jsonb,
    tariff_id                uuid,
    request_status           varchar(255),
    status_code              integer,
    approval_state           varchar(255),
    expected_cost            double precision,
    expected_distance        double precision,
    expected_time            bigint,
    trip_purpose             uuid
        constraint fk_request_for_taxi_purpose
            references request.trip_purpose,
    request_options          jsonb,
    desired_date             timestamp             not null,
    coop_trip                boolean,
    passenger_count          integer,
    trip_class               varchar(255),
    comment                  varchar(255),
    rating_advantages        jsonb,
    rating_drawbacks         jsonb,
    rating_mark              integer,
    rating_comment           varchar(255),
    finished_time            timestamp,
    magenta_order_id         bigint,
    shared_ride_id           bigint,
    contractor_id            uuid,
    driver_id                uuid,
    dispatcher_id            uuid
        constraint fk_dispatcher_employee
            references request.employee,
    auto_cancel_deadline_min integer default 15,
    sent_to_contractor       boolean default false not null,
    deadline_state           integer,
    deadline                 bigint,
    active                   boolean default true  not null,
    taxi_trip_id             uuid
        constraint request_for_taxi_taxi_trip_id_fkey
            references request.taxi_trip,
    resolution               varchar(2000)
);

comment on column request.request_for_taxi.contractor_id is 'Контрагент - перевозчик';

comment on column request.request_for_taxi.driver_id is 'ID водителя';

comment on column request.request_for_taxi.dispatcher_id is 'ID ответственного диспетчера';

comment on column request.request_for_taxi.auto_cancel_deadline_min is 'Минимальное время до планируемого для согласования';

comment on column request.request_for_taxi.sent_to_contractor is 'Флаг отправки исполнителю (true - отправлено)';

comment on column request.request_for_taxi.deadline_state is 'Индикатор контрольного срока (ordinal): 0 - NONE, 1 - YELLOW, 2 - RED';

comment on column request.request_for_taxi.deadline is 'Контрольный срок, мин';

comment on column request.request_for_taxi.active is 'Флаг активности';

comment on column request.request_for_taxi.resolution is 'Описание состояния поездки от исполнителя';

create table request.request_for_personal
(
    id                    uuid                 not null
        constraint request_for_personal_pkey
            primary key,
    humanreadableid       varchar(100)         not null
        constraint request_for_personal_humanreadableid_key
            unique,
    author_id             uuid                 not null
        constraint fk_request_for_personal_author
            references request.employee,
    passenger_id          uuid                 not null
        constraint fk_request_for_personal_passenger
            references request.employee,
    creation_time         timestamp,
    transport_type        varchar(255)         not null,
    approved_by_id        uuid
        constraint fk_request_for_personal_approved
            references request.employee,
    approval_date         timestamp,
    segments              jsonb,
    tariff_id             uuid,
    request_status        varchar(255),
    status_code           integer,
    approval_state        varchar(255),
    expected_cost         double precision,
    expected_distance     double precision,
    expected_time         bigint,
    trip_purpose          uuid
        constraint fk_request_for_personal_purpose
            references request.trip_purpose,
    request_options       jsonb,
    desired_date          timestamp            not null,
    coop_trip             boolean,
    passenger_count       integer,
    comment               varchar(255),
    finished_time         timestamp,
    magenta_order_id      bigint,
    shared_ride_id        bigint,
    occupied_places_count integer,
    personal_car_id       uuid,
    personal_car          varchar,
    active                boolean default true not null,
    employee_driver_id    uuid,
    trip_start_time       timestamp,
    trip_start_latitude   double precision,
    trip_start_longitude  double precision
);

comment on column request.request_for_personal.personal_car_id is 'Идентификатор личного транспорта';

comment on column request.request_for_personal.personal_car is 'Личный транспорт';

comment on column request.request_for_personal.active is 'Флаг активности';

comment on column request.request_for_personal.employee_driver_id is 'Идентификатор водителя в поездке на личном транспорте';

comment on column request.request_for_personal.trip_start_time is 'Время начала поездки';

comment on column request.request_for_personal.trip_start_latitude is 'Широта начала поездки';

comment on column request.request_for_personal.trip_start_longitude is 'Долгота начала поездки';

create table request.request_for_public
(
    id                     uuid                 not null
        constraint request_for_public_pkey
            primary key,
    humanreadableid        varchar(100)         not null
        constraint request_for_public_humanreadableid_key
            unique,
    author_id              uuid                 not null
        constraint fk_request_for_public_author
            references request.employee,
    passenger_id           uuid                 not null
        constraint fk_request_for_public_passenger
            references request.employee,
    creation_time          timestamp,
    transport_type         varchar(255)         not null,
    approved_by_id         uuid
        constraint fk_request_for_public_approved
            references request.employee,
    approval_date          timestamp,
    segments               jsonb,
    tariff_id              uuid,
    request_status         varchar(255),
    status_code            integer,
    approval_state         varchar(255),
    expected_cost          double precision,
    expected_distance      double precision,
    expected_time          bigint,
    trip_purpose           uuid
        constraint fk_request_for_public_purpose
            references request.trip_purpose,
    request_options        jsonb,
    desired_date           timestamp            not null,
    active                 boolean default true not null,
    trip_confirmation_date timestamp
);

comment on column request.request_for_public.active is 'Флаг активности';

create table request.request_for_taxi_history
(
    id                  uuid         not null
        constraint request_for_taxi_history_pkey
            primary key,
    change_date         timestamp    not null,
    code                integer,
    comment             varchar(255),
    request_status      varchar(255) not null,
    request_for_taxi_id uuid         not null
        constraint fk_request_history_request_for_taxi
            references request.request_for_taxi,
    initiator_id        uuid         not null
        constraint fk_taxi_history_employee
            references request.employee
);

create table request.request_for_personal_history
(
    id                      uuid         not null
        constraint request_for_personal_history_pkey
            primary key,
    change_date             timestamp    not null,
    code                    integer,
    comment                 varchar(255),
    request_status          varchar(255) not null,
    request_for_personal_id uuid         not null
        constraint fk_request_history_request_for_personal
            references request.request_for_personal,
    initiator_id            uuid         not null
        constraint fk_personal_history_employee
            references request.employee
);

create table request.request_for_public_history
(
    id                    uuid         not null
        constraint request_for_public_history_pkey
            primary key,
    change_date           timestamp    not null,
    code                  integer,
    comment               varchar(255),
    request_status        varchar(255) not null,
    request_for_public_id uuid         not null
        constraint fk_request_history_request_for_public
            references request.request_for_public,
    initiator_id          uuid         not null
        constraint fk_public_history_employee
            references request.employee
);

create table request.advantages
(
    request_id uuid not null,
    value      text not null
);

create table request.drawbacks
(
    request_id uuid not null,
    value      text not null
);

create table request.compensation_document
(
    id            uuid         not null
        constraint compensation_document_pkey
            primary key,
    name          text         not null,
    size          integer      not null
        constraint compensation_document_size_check
            check (size <= 20971520),
    format        varchar(255) not null,
    request_id    uuid
        constraint compensation_document_request_id_fkey
            references request.request_for_public,
    creation_time timestamp,
    folder        uuid         not null
);

create table request.checkin_settings
(
    id                  uuid    not null
        constraint checkin_settings_pkey
            primary key,
    service_type        varchar not null,
    transport_type      varchar not null,
    region              varchar,
    radius              integer,
    region_id           uuid,
    checkin_only_manual boolean default false
);

comment on column request.checkin_settings.region_id is 'Идентификатор региона';

comment on column request.checkin_settings.checkin_only_manual is 'Режим подтверждения прибытия в точку маршрута';

create table request.approvers
(
    department_id  uuid not null,
    employee_id    uuid not null,
    transport_type text,
    constraint approvers_ukey
        unique (department_id, employee_id, transport_type)
);

comment on column request.approvers.department_id is 'Подразделение, заявки которого разрешено согласовывать сотруднику employee_id';

comment on column request.approvers.employee_id is 'Сотрудник, имеющий право согласовывать заявки подразделения department_id';

comment on column request.approvers.transport_type is 'Тип транспорта. Заявки только данного типа транспорта можно согласовывать сотруднику employee_id';

create table request.address_catalog
(
    id        uuid             not null
        constraint address_catalog_pkey
            primary key,
    address   varchar(255)     not null,
    longitude double precision not null,
    latitude  double precision not null
);

create table request.address_catalog_versions
(
    id               uuid         not null
        constraint address_catalog_versions_pkey
            primary key,
    file_update_time timestamp    not null,
    filename         varchar(255) not null
);

create table request.request_for_carsharing
(
    id                uuid                 not null
        constraint request_for_carsharing_pkey
            primary key,
    humanreadableid   varchar(100)         not null
        constraint request_for_carsharing_humanreadableid_key
            unique,
    author_id         uuid                 not null,
    passenger_id      uuid                 not null,
    creation_time     timestamp,
    transport_type    varchar(255)         not null,
    approved_by_id    uuid,
    approval_date     timestamp,
    segments          jsonb,
    tariff_id         uuid,
    request_status    varchar(255),
    status_code       integer,
    approval_state    varchar(255),
    expected_cost     double precision,
    expected_distance double precision,
    expected_time     bigint,
    trip_purpose      uuid,
    request_options   jsonb,
    desired_date      timestamp            not null,
    coop_trip         boolean,
    passenger_count   integer,
    finished_time     timestamp,
    contractor_id     uuid                 not null,
    carsharing_class  varchar(255),
    active            boolean default true not null
);

comment on column request.request_for_carsharing.id is 'ID';

comment on column request.request_for_carsharing.humanreadableid is 'Уникальный идентификатор (человекочитаемый ID)';

comment on column request.request_for_carsharing.author_id is 'ID создателя заявки';

comment on column request.request_for_carsharing.passenger_id is 'ID пассажира';

comment on column request.request_for_carsharing.creation_time is 'Дата и время создания заявки';

comment on column request.request_for_carsharing.transport_type is 'Тип транспорта';

comment on column request.request_for_carsharing.approved_by_id is 'ID согласовавшего лица';

comment on column request.request_for_carsharing.approval_date is 'Дата и время согласования';

comment on column request.request_for_carsharing.segments is 'JSON с предварительными параметрами заявки';

comment on column request.request_for_carsharing.tariff_id is 'ID тарифа';

comment on column request.request_for_carsharing.request_status is 'Статус заявки';

comment on column request.request_for_carsharing.status_code is 'Код статуса';

comment on column request.request_for_carsharing.approval_state is 'Статус согласования';

comment on column request.request_for_carsharing.expected_cost is 'Предварительная стоимость, руб';

comment on column request.request_for_carsharing.expected_distance is 'Дальность, км';

comment on column request.request_for_carsharing.expected_time is 'Длительность, мин';

comment on column request.request_for_carsharing.trip_purpose is 'Цель поездки';

comment on column request.request_for_carsharing.request_options is 'Доп. опции';

comment on column request.request_for_carsharing.desired_date is 'Желаемая дата и время поездки';

comment on column request.request_for_carsharing.coop_trip is 'Тип поездки (индивидуальная/совместная)';

comment on column request.request_for_carsharing.passenger_count is 'Количество пассажиров';

comment on column request.request_for_carsharing.finished_time is 'Дата и время окончания поездки';

comment on column request.request_for_carsharing.contractor_id is 'Каршеринговая компания';

comment on column request.request_for_carsharing.carsharing_class is 'Выбранный класс автомобиля';

comment on column request.request_for_carsharing.active is 'Флаг активности';

create table request.request_for_carsharing_history
(
    id                        uuid         not null
        constraint request_for_carsharing_history_pkey
            primary key,
    change_date               timestamp    not null,
    code                      integer,
    comment                   varchar(255),
    request_status            varchar(255) not null,
    request_for_carsharing_id uuid         not null
        constraint fk_request_history_request_for_carsharing
            references request.request_for_carsharing,
    initiator_id              uuid         not null
        constraint fk_carsharing_history_employee
            references request.employee
);

comment on column request.request_for_carsharing_history.id is 'ID';

comment on column request.request_for_carsharing_history.change_date is 'Дата';

comment on column request.request_for_carsharing_history.code is 'Код';

comment on column request.request_for_carsharing_history.comment is 'Комментарий';

comment on column request.request_for_carsharing_history.request_status is 'Статус заявки';

comment on column request.request_for_carsharing_history.request_for_carsharing_id is 'ID заявки на каршеринге';

comment on column request.request_for_carsharing_history.initiator_id is 'ID пользователя';

create table request.driver
(
    id                              uuid not null
        constraint driver_pkey
            primary key,
    active                          boolean,
    autopark_id                     uuid,
    contact_phone                   varchar(255),
    contractor_id                   uuid,
    driver_license_number           varchar(255),
    experience                      varchar(255),
    first_name                      varchar(255),
    last_name                       varchar(255),
    passport                        varchar(255),
    patronymic                      varchar(255),
    rating                          integer,
    service_provider_license_number varchar(255)
);

comment on table request.driver is 'Водители';

comment on column request.driver.id is 'Уникальный идентификатор';

comment on column request.driver.active is 'Активность водителя';

comment on column request.driver.autopark_id is 'Идентификатор автопарка';

comment on column request.driver.contact_phone is 'Контактный номер телефона';

comment on column request.driver.contractor_id is 'Идентификатор контрагента';

comment on column request.driver.driver_license_number is 'Номер ВУ';

comment on column request.driver.experience is 'Опыт';

comment on column request.driver.first_name is 'Имя';

comment on column request.driver.last_name is 'Фамилия';

comment on column request.driver.passport is 'Серия и номер пасспорта';

comment on column request.driver.patronymic is 'Отчество';

comment on column request.driver.rating is 'Рейтинг водителя';

comment on column request.driver.service_provider_license_number is 'Номер провайдера лицензии';

create table request.driver_tag
(
    id            uuid not null
        constraint driver_tag_pkey
            primary key,
    contractor_id uuid,
    name          varchar(255)
);

comment on table request.driver_tag is 'Таблица признаков водителей';

comment on column request.driver_tag.id is 'Уникальный идентификатор';

comment on column request.driver_tag.contractor_id is 'Идентификатор контрагента';

comment on column request.driver_tag.name is 'Имя признака';

create table request.driver_tag_connector
(
    driver_id uuid not null,
    tag_id    uuid not null,
    constraint driver_tag_connector_pkey
        primary key (driver_id, tag_id)
);

comment on table request.driver_tag_connector is 'Соединительная таблица для водителей и их признаков';

comment on column request.driver_tag_connector.driver_id is 'Идентификатор водителя';

comment on column request.driver_tag_connector.tag_id is 'Идентификатор признака';

create table request.driver_license_classes
(
    driver_id uuid not null
        constraint driver_license_classes_driver_id_fkey
            references request.driver,
    class     varchar(255)
);

comment on table request.driver_license_classes is 'Классы прав';

comment on column request.driver_license_classes.driver_id is 'Идентификатор водителя';

comment on column request.driver_license_classes.class is 'Категория ВУ';

create table request.autopark
(
    id            uuid not null
        constraint autopark_pkey
            primary key,
    autopark_name varchar(255)
);

comment on table request.autopark is 'Автопарки';

comment on column request.autopark.id is 'Уникальный идентификатор';

comment on column request.autopark.autopark_name is 'Название автопарка';

create table request.contractor
(
    id   uuid not null
        constraint contractor_pkey
            primary key,
    name varchar(255)
);

comment on table request.contractor is 'Контрагенты';

comment on column request.contractor.id is 'Уникальный идентификатор';

comment on column request.contractor.name is 'Название контрагента';

create table request.driver_filters
(
    id             uuid not null
        constraint driver_filters_pkey
            primary key,
    autopark_names varchar(255),
    tags           varchar(255),
    last_name      varchar(255),
    first_name     varchar(255),
    patronymic     varchar(255),
    rating         smallint,
    active         boolean default true,
    expirience     varchar(255)
);

comment on column request.driver_filters.id is 'ID';

comment on column request.driver_filters.autopark_names is 'Названия автопарков';

comment on column request.driver_filters.tags is 'Признаки водителя';

comment on column request.driver_filters.last_name is 'Фамилия';

comment on column request.driver_filters.first_name is 'Имя';

comment on column request.driver_filters.patronymic is 'Отчество';

comment on column request.driver_filters.rating is 'Рейтинг';

comment on column request.driver_filters.active is 'Активность';

comment on column request.driver_filters.expirience is 'Опыт';

create table request.contract_message
(
    id             uuid    not null
        constraint contract_message_pkey
            primary key,
    transport_type varchar(50),
    service_type   varchar(100),
    contractor_id  uuid,
    region         text,
    active         boolean not null,
    deleted        boolean not null
);

comment on table request.contract_message is 'Контракт с контрагентом, получаемый из сообщения';

comment on column request.contract_message.id is 'ID контракта';

comment on column request.contract_message.transport_type is 'Тип транспорта';

comment on column request.contract_message.service_type is 'Вид транспортной услуги';

comment on column request.contract_message.contractor_id is 'ID контрагента';

comment on column request.contract_message.region is 'Регион';

comment on column request.contract_message.active is 'Флаг активности';

comment on column request.contract_message.deleted is 'Флаг удаления контракта';

create table request.contract_message_organization
(
    contract_id     uuid not null
        constraint contract_message_organization_contract_id_fkey
            references request.contract_message,
    organization_id uuid
);

comment on table request.contract_message_organization is 'Таблица связи Контракт - ID организации';

comment on column request.contract_message_organization.contract_id is 'ID контракта';

comment on column request.contract_message_organization.organization_id is 'ID организации';

create table request.corporate_carsharing
(
    id              uuid                 not null
        constraint corporate_carsharing_pkey
            primary key,
    organization_id uuid                 not null,
    contract_id     uuid                 not null,
    active          boolean default true not null,
    constraint corporate_carsharing_uk
        unique (contract_id, organization_id)
);

comment on table request.corporate_carsharing is 'Программно генерируемая таблица - Корпоративные каршеринги';

comment on column request.corporate_carsharing.id is 'ID каршеринга';

comment on column request.corporate_carsharing.organization_id is 'Конкретный корп.клиент каршеринга';

comment on column request.corporate_carsharing.contract_id is 'ID контракта с контрагентом';

comment on column request.corporate_carsharing.active is 'Флаг активности';

create table request.corporate_carsharing_joined_employee
(
    corporate_carsharing_id uuid not null
        constraint corporate_carsharing_joined_employ_corporate_carsharing_id_fkey
            references request.corporate_carsharing,
    employee_id             uuid not null
        constraint corporate_carsharing_joined_employee_employee_id_fkey
            references request.employee,
    constraint corporate_carsharing_joined_employee_pkey
        primary key (corporate_carsharing_id, employee_id)
);

comment on table request.corporate_carsharing_joined_employee is 'Таблица связи Каршеринг - Сотрудник';

comment on column request.corporate_carsharing_joined_employee.corporate_carsharing_id is 'ID каршеринга';

comment on column request.corporate_carsharing_joined_employee.employee_id is 'ID сотрудника';

create table request.tariff_message
(
    id                uuid    not null
        constraint tariff_message_pkey
            primary key,
    humanreadableid   varchar(255),
    transport_type_id uuid,
    contract_id       uuid,
    region            text,
    deleted           boolean not null
);

comment on table request.tariff_message is 'Тарифа каршеринга, получаемый из сообщения';

comment on column request.tariff_message.id is 'ID тарифа';

comment on column request.tariff_message.humanreadableid is 'Человекочитаемый ID';

comment on column request.tariff_message.transport_type_id is 'ID типа транспорта';

comment on column request.tariff_message.contract_id is 'ID контракта с контрагентом';

comment on column request.tariff_message.region is 'Регион';

comment on column request.tariff_message.deleted is 'Флаг удаления тарифа';

create table request.contractor_message
(
    id      uuid    not null
        constraint contractor_message_pkey
            primary key,
    name    varchar(255),
    msrn    varchar(50),
    tin     varchar(50),
    deleted boolean not null
);

comment on table request.contractor_message is 'Контрагент, получаемый из сообщения';

comment on column request.contractor_message.id is 'ID контрагента';

comment on column request.contractor_message.name is 'Наименование контрагента';

comment on column request.contractor_message.msrn is 'ОГРН';

comment on column request.contractor_message.tin is 'ИНН';

comment on column request.contractor_message.deleted is 'Флаг удаления';

create table request.carsharing_join_request_text
(
    organization_id          uuid not null
        constraint carsharing_join_request_text_pkey
            primary key,
    before_fio_first_part    text,
    before_fio_second_part   text,
    before_fio_third_part    text,
    deadline_unit            varchar(50),
    deadline_value           smallint,
    after_carsharings        text,
    after_email              text,
    after_phone              text,
    with_personal_data_agree text,
    with_rules_p144_agree    text
);

comment on table request.carsharing_join_request_text is 'Список текстовых полей заявки на подключение к корп.каршерингу';

comment on column request.carsharing_join_request_text.organization_id is 'ID записи';

comment on column request.carsharing_join_request_text.before_fio_first_part is 'Первая часть текстового поля до ФИО (до указания КС)';

comment on column request.carsharing_join_request_text.before_fio_second_part is 'Вторая часть текстового поля до ФИО - из настроек КС';

comment on column request.carsharing_join_request_text.before_fio_third_part is 'Третья часть текстового поля до ФИО (после указания КС)';

comment on column request.carsharing_join_request_text.deadline_unit is 'Единица измерения времени из настройки КС';

comment on column request.carsharing_join_request_text.deadline_value is 'Значение времени из настройки КС';

comment on column request.carsharing_join_request_text.after_carsharings is 'Текст после списка корп.каршерингов';

comment on column request.carsharing_join_request_text.after_email is 'Текст после почты';

comment on column request.carsharing_join_request_text.after_phone is 'Текст после номера телефона';

comment on column request.carsharing_join_request_text.with_personal_data_agree is 'Текст чекбокса - Согласие на обработку персональных данных';

comment on column request.carsharing_join_request_text.with_rules_p144_agree is 'Текст чекбокса - Согласие с Памяткой П-144';

create table request.carsharing_join_request
(
    id                  uuid         not null
        constraint carsharing_join_request_pkey
            primary key,
    human_readable_id   varchar(30)  not null,
    employee_id         uuid         not null
        constraint carsharing_join_request_employee_id_fkey
            references request.employee,
    email               text         not null,
    phone               varchar(30)  not null,
    request_status      varchar(100) not null,
    rules_p144_agree    boolean,
    personal_data_agree boolean,
    text_id             uuid         not null
        constraint carsharing_join_request_text_id_fkey
            references request.carsharing_join_request_text,
    creation_time       timestamp    not null,
    status_code         integer,
    cancel_reason       varchar
);

comment on table request.carsharing_join_request is 'Заявка на подключение к корп.каршерингу';

comment on column request.carsharing_join_request.id is 'ID заявки на подключение';

comment on column request.carsharing_join_request.human_readable_id is 'Человекочитаемый ID';

comment on column request.carsharing_join_request.employee_id is 'ID подключаемого сотудника';

comment on column request.carsharing_join_request.email is 'Почта, с которой сотрудник зарегистрирован в каршеринговом сервисе';

comment on column request.carsharing_join_request.phone is 'Номер телефона, с которым сотрудник зарегистрирован в каршеринговом сервисе';

comment on column request.carsharing_join_request.request_status is 'Статус заявки ';

comment on column request.carsharing_join_request.rules_p144_agree is 'Согласие с правилами Памятка П-144';

comment on column request.carsharing_join_request.personal_data_agree is 'Согласие на обработку персональных данных';

comment on column request.carsharing_join_request.text_id is 'ID записи - текстовых полей заявки';

comment on column request.carsharing_join_request.creation_time is 'Дата и время создания заявки';

comment on column request.carsharing_join_request.status_code is 'Код статуса';

comment on column request.carsharing_join_request.cancel_reason is 'Причина изменения';

create table request.contractor_status
(
    id              uuid    not null
        constraint contractor_status_pkey
            primary key,
    region          text    not null,
    join_status     varchar(100),
    employee_choice boolean not null,
    contractor_id   uuid    not null
        constraint contractor_status_contractor_id_fkey
            references request.contractor_message
);

comment on table request.contractor_status is 'Контрагент и статус подключения к нему сотрудника';

comment on column request.contractor_status.id is 'ID записи';

comment on column request.contractor_status.region is 'Регион';

comment on column request.contractor_status.join_status is 'Статус подключения';

comment on column request.contractor_status.employee_choice is 'Выбор сотрудником каршеринга, к которому необходимо подключение';

comment on column request.contractor_status.contractor_id is 'ID контрагента';

create table request.carsharing_join_request_and_contractor_status
(
    join_request_id      uuid not null
        constraint carsharing_join_request_and_contractor_sta_join_request_id_fkey
            references request.carsharing_join_request,
    contractor_status_id uuid not null
        constraint carsharing_join_request_and_contracto_contractor_status_id_fkey
            references request.contractor_status,
    constraint carsharing_join_request_and_contractor_status_pkey
        primary key (join_request_id, contractor_status_id)
);

comment on table request.carsharing_join_request_and_contractor_status is 'Подключаемые корп.каршеринги со статусами подключения';

comment on column request.carsharing_join_request_and_contractor_status.join_request_id is 'ID заявки на подключение';

comment on column request.carsharing_join_request_and_contractor_status.contractor_status_id is 'ID записи о контрагенте и статусе подключения';

create table request.join_request_processing_mode
(
    processing_mode varchar(100) not null
        constraint join_request_processing_mode_pkey
            primary key
);

comment on table request.join_request_processing_mode is 'Настройка режима обработки заявок на подключение к корп.каршерингу';

comment on column request.join_request_processing_mode.processing_mode is 'Режим обработки заявок на подключение к корп.каршерингу';

create table request.deadline_settings_item_message
(
    item_type              varchar(31) not null,
    id                     uuid        not null
        constraint deadline_settings_item_message_pkey
            primary key,
    transport_type         varchar(255),
    request_status         varchar(255),
    limit_type             varchar(255),
    carsharing_join_status varchar(255),
    unit                   varchar(255),
    value                  smallint
);

comment on table request.deadline_settings_item_message is 'Элемент Настройки контрольных сроков для организации';

comment on column request.deadline_settings_item_message.item_type is 'Тип элемента (discriminator column)';

comment on column request.deadline_settings_item_message.id is 'ID элемента настройки';

comment on column request.deadline_settings_item_message.transport_type is 'Тип транспорта';

comment on column request.deadline_settings_item_message.request_status is 'Cтатус заявки на поездку';

comment on column request.deadline_settings_item_message.limit_type is 'Тип лимита';

comment on column request.deadline_settings_item_message.carsharing_join_status is 'Статус заявки на подключение к корп. каршерингу';

comment on column request.deadline_settings_item_message.unit is 'Единица измерения времени';

comment on column request.deadline_settings_item_message.value is 'Значение контрольного срока (в указанных ед.изменрения)';

create table request.deadline_settings_message
(
    id                                                 uuid not null
        constraint deadline_settings_message_pkey
            primary key,
    organization_id                                    uuid,
    taxi_awaiting_approvals_deadline_id                uuid
        constraint deadline_settings_message_taxi_awaiting_approvals_deadline_fkey
            references request.deadline_settings_item_message
            on delete cascade,
    taxi_driver_search_deadline_id                     uuid
        constraint deadline_settings_message_taxi_driver_search_deadline_id_fkey
            references request.deadline_settings_item_message
            on delete cascade,
    taxi_trip_finished_deadline_id                     uuid
        constraint deadline_settings_message_taxi_trip_finished_deadline_id_fkey
            references request.deadline_settings_item_message
            on delete cascade,
    personal_awaiting_approvals_deadline_id            uuid
        constraint deadline_settings_message_personal_awaiting_approvals_dead_fkey
            references request.deadline_settings_item_message
            on delete cascade,
    personal_awaiting_shared_ride_approval_deadline_id uuid
        constraint deadline_settings_message_personal_awaiting_shared_ride_ap_fkey
            references request.deadline_settings_item_message
            on delete cascade,
    personal_trip_in_progress_deadline_id              uuid
        constraint deadline_settings_message_personal_trip_in_progress_deadli_fkey
            references request.deadline_settings_item_message
            on delete cascade,
    personal_awaiting_trip_approval_deadline_id        uuid
        constraint deadline_settings_message_personal_awaiting_trip_approval__fkey
            references request.deadline_settings_item_message
            on delete cascade,
    public_awaiting_approval_deadline_id               uuid
        constraint deadline_settings_message_public_awaiting_approval_deadlin_fkey
            references request.deadline_settings_item_message
            on delete cascade,
    public_trip_confirmation_deadline_id               uuid
        constraint deadline_settings_message_public_trip_confirmation_deadlin_fkey
            references request.deadline_settings_item_message
            on delete cascade,
    public_awaiting_affirmative_deadline_id            uuid
        constraint deadline_settings_message_public_awaiting_affirmative_dead_fkey
            references request.deadline_settings_item_message
            on delete cascade,
    carsharing_join_deadline_id                        uuid
        constraint deadline_settings_message_carsharing_join_deadline_id_fkey
            references request.deadline_settings_item_message
            on delete cascade
);

comment on table request.deadline_settings_message is 'Настройки контрольных сроков для организации';

comment on column request.deadline_settings_message.id is 'ID настройки';

comment on column request.deadline_settings_message.organization_id is 'Организация. Одна настройка для одной организации';

comment on column request.deadline_settings_message.taxi_awaiting_approvals_deadline_id is 'Контрольный срок - такси - на согласовании';

comment on column request.deadline_settings_message.taxi_driver_search_deadline_id is 'Контрольный срок - такси - поиск водителя';

comment on column request.deadline_settings_message.taxi_trip_finished_deadline_id is 'Контрольный срок - такси - поездка завершена';

comment on column request.deadline_settings_message.personal_awaiting_approvals_deadline_id is 'Контрольный срок - личный а/м - на согласовании';

comment on column request.deadline_settings_message.personal_awaiting_shared_ride_approval_deadline_id is 'Контрольный срок - личный а/м - согласование присоединения к СП';

comment on column request.deadline_settings_message.personal_trip_in_progress_deadline_id is 'Контрольный срок - личный а/м - поездка';

comment on column request.deadline_settings_message.personal_awaiting_trip_approval_deadline_id is 'Контрольный срок - личный а/м - утверждение маршрута';

comment on column request.deadline_settings_message.public_awaiting_approval_deadline_id is 'Контрольный срок - общественный тр-т - на согласовании';

comment on column request.deadline_settings_message.public_trip_confirmation_deadline_id is 'Контрольный срок - общественный тр-т - подтверждение поездки';

comment on column request.deadline_settings_message.public_awaiting_affirmative_deadline_id is 'Контрольный срок - общественный тр-т - утверждение';

comment on column request.deadline_settings_message.carsharing_join_deadline_id is 'Контрольный срок – заявка на подключение к корп. каршерингу - на согласовании';

create table request.messages_geo_zone
(
    id        uuid   not null
        constraint geo_zone_pkey
            primary key,
    code      bigint not null,
    name      text   not null,
    parent_id uuid
);

comment on column request.messages_geo_zone.id is 'Идентификатор';

comment on column request.messages_geo_zone.code is 'Код геозоны';

comment on column request.messages_geo_zone.name is 'Название геозоны';

comment on column request.messages_geo_zone.parent_id is 'Идентификатор родительской геозоны';

create table request.transport_compensation
(
    id                       uuid         not null
        constraint transport_compensation_pkey
            primary key,
    compensation_type        varchar(255) not null,
    transport_type           varchar(255) not null,
    tickets_cost             varchar(255) not null,
    tickets_count            varchar(255) not null,
    tickets_expiration_start date,
    tickets_expiration_end   date,
    request_id               uuid
        constraint transport_compensation_request_id_fkey
            references request.request_for_public,
    attached_document_id     uuid
);

comment on column request.transport_compensation.compensation_type is 'Тип компенсации';

comment on column request.transport_compensation.transport_type is 'Тип транспорта';

comment on column request.transport_compensation.tickets_cost is 'Стоимость билета';

comment on column request.transport_compensation.tickets_count is 'Кол-во билетов';

comment on column request.transport_compensation.tickets_expiration_start is 'Дата начала действия билета';

comment on column request.transport_compensation.tickets_expiration_end is 'Дата окончания действия билета';

comment on column request.transport_compensation.request_id is 'Поездка';

comment on column request.transport_compensation.attached_document_id is 'Идентификатор документа';

create table request.dep_limit_message
(
    id            uuid not null
        constraint dep_limit_fkey
            primary key,
    department_id uuid,
    owner_id      uuid,
    year          integer
);

comment on table request.dep_limit_message is 'Cущность лимита подразделения, получаемая из сообщения';

comment on column request.dep_limit_message.id is 'ID';

comment on column request.dep_limit_message.department_id is 'ID подразделения';

comment on column request.dep_limit_message.owner_id is 'ID владельца лимита подразделения';

comment on column request.dep_limit_message.year is 'год';

create table request.request_status_overdue
(
    id                             uuid,
    request_id                     uuid,
    trip_request_status            varchar,
    carsharing_join_request_status varchar,
    deadline_chrono_unit           varchar,
    deadline_value                 smallint,
    overdue_time                   timestamp
);

comment on table request.request_status_overdue is 'Просроченные по КС заявки';

comment on column request.request_status_overdue.id is 'ID';

comment on column request.request_status_overdue.request_id is 'ID заявки';

comment on column request.request_status_overdue.trip_request_status is 'Статус заявки (на поездку)';

comment on column request.request_status_overdue.carsharing_join_request_status is 'Статус заявки (на подключение к копр. каршерингу)';

comment on column request.request_status_overdue.deadline_chrono_unit is 'Единица измерения времени КС';

comment on column request.request_status_overdue.deadline_value is 'Значение КС';

comment on column request.request_status_overdue.overdue_time is 'Время, в которое был превышен КС';


create schema if not exists request_audit;

create table if not exists request_audit.request_for_public_revinfo
(
    rev       bigserial not null
        constraint request_for_public_revinfo_pkey
            primary key,
    timestamp timestamp,
    user_id   uuid
);

create table request_audit.request_for_public
(
    id                     uuid    not null,
    rev                    int8 not null
        constraint request_for_public_rev_fkey
            references request_audit.request_for_public_revinfo,
    revtype                smallint,
    humanreadableid        varchar(100),
    creation_time          timestamp,
    transport_type         varchar(255),
    approval_date          timestamp,
    segments               jsonb,
    tariff_id              uuid,
    request_status         varchar(255),
    status_code            integer,
    approval_state         varchar(255),
    expected_cost          double precision,
    expected_distance      double precision,
    expected_time          bigint,
    request_options        jsonb,
    desired_date           timestamp,
    trip_confirmation_date timestamp,
    constraint request_for_public_pkey
        primary key (id, rev)
);

