export const DISPATCHER_ROOM = '/dispatcher-room';

export const GET_CONTRACTOR_DISPATCHERS = `${DISPATCHER_ROOM}/:contractorId/dispatcher/`;
export const GET_CONTRACTOR_DISPATCHER = `${GET_CONTRACTOR_DISPATCHERS}:dispId/`;
export const CREATE_CONTRACTOR_DISPATCHER = `${GET_CONTRACTOR_DISPATCHERS}`;
export const EDIT_CONTRACTOR_DISPATCHER = `${GET_CONTRACTOR_DISPATCHERS}:dispId/`;
export const DELETE_CONTRACTOR_DISPATCHER = `${GET_CONTRACTOR_DISPATCHERS}:dispId/`;
export const TRIP_TRANSPORT = `${DISPATCHER_ROOM}/transport/`;
