drop index if exists request_request_for_carsharing_approval_deadline_idx;
drop index if exists request_request_for_public_approval_deadline_idx;
drop index if exists request_request_for_personal_approval_deadline_idx;
drop index if exists request_request_for_taxi_approval_deadline_idx;