<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>parent</artifactId>
        <groupId>ru.sber.transport.address</groupId>
        <version>3.21</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>application</artifactId>
    <version>5.7</version>

    <properties>
        <server.port>8008</server.port>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>${maven.compiler.source}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!--suppress UnresolvedMavenProperty -->
        <source.image>
            registry.sigma.sbrf.ru/ci02351878/ci02353146_transport/open-jdk:17.5
        </source.image>
        <image-tag>${project.version}-${user.name}</image-tag>
        <liquibase-core.version>4.32.0</liquibase-core.version>
        <tomcat.version>10.1.42</tomcat.version>
        <spring-cloud-dependencies.version>2025.0.0</spring-cloud-dependencies.version>
        <embedded-postgres.version>4.10</embedded-postgres.version>
        <messaging.version>4.7</messaging.version>
        <file-works.version>3.18</file-works.version>
        <properties-loader.version>3.16.0.1</properties-loader.version>
        <kafka-functional.version>4.6.0.2</kafka-functional.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <grpc-bom.version>4.16</grpc-bom.version>
        <audit.version>3.16</audit.version>
        <jooq-database.version>3.16</jooq-database.version>
        <authorization.version>4.10</authorization.version>
        <role-check-starter.version>3.18</role-check-starter.version>
        <transport-core.version>3.24</transport-core.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport.grpc</groupId>
                <artifactId>bom</artifactId>
                <version>${grpc-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <!-- Spring -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-indexer</artifactId>
        </dependency>

        <!-- Database -->
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
            <version>${liquibase-core.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>audit</artifactId>
            <version>${audit.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>jooq-database</artifactId>
            <version>${jooq-database.version}</version>
        </dependency>

        <!-- Utils -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>authorization</artifactId>
            <version>${authorization.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>role-check-starter</artifactId>
            <version>${role-check-starter.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>transport-core</artifactId>
            <version>${transport-core.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>io.swagger.core.v3</groupId>
                    <artifactId>swagger-annotations</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>kafka-functional</artifactId>
            <version>${kafka-functional.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>io.swagger.core.v3</groupId>
                    <artifactId>swagger-annotations</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.grpc</groupId>
            <artifactId>client</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>file-works</artifactId>
            <version>${file-works.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>properties-loader</artifactId>
            <version>${properties-loader.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.corporate</groupId>
            <artifactId>messaging</artifactId>
            <version>${messaging.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-vault-config</artifactId>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>embedded-postgres</artifactId>
            <version>${embedded-postgres.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.liquibase</groupId>
                    <artifactId>liquibase-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.instancio</groupId>
            <artifactId>instancio-junit</artifactId>
            <version>5.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.grpc</groupId>
            <artifactId>test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test-autoconfigure</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.25.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jdbc</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-test-binder</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <finalName>address</finalName>
        <plugins>

            <plugin>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-maven-plugin</artifactId>
                <version>1.11.3</version>
                <executions>
                    <execution>
                        <id>generate-idl</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>schema</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sourceDirectory>../_documents/api/avro</sourceDirectory>
                    <fieldVisibility>PRIVATE</fieldVisibility>
                    <enableDecimalLogicalType>true</enableDecimalLogicalType>
                    <stringType>String</stringType>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <customConversions>org.apache.avro.Conversions$UUIDConversion</customConversions>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.6.0</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <typeMappings>
                                <typeMapping>Double=java.math.BigDecimal</typeMapping>
                            </typeMappings>
                            <inputSpec>
                                https://apistudio.sigma.sbrf.ru/public/bundle/yml/8634004a-007a-4428-bfb5-620b2d41b3ca
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <mergedFileName>openapi</mergedFileName>
                            <generateApiTests>true</generateApiTests>
                            <generateModelTests>true</generateModelTests>
                            <apiPackage>ru.sber.transport.web.api</apiPackage>
                            <modelPackage>ru.sber.transport.web.model</modelPackage>
                            <invokerPackage>ru.sber.transport.web.invoker</invokerPackage>
                            <strictSpec>true</strictSpec>
                            <generateAliasAsModel>true</generateAliasAsModel>
                            <generateSupportingFiles>true</generateSupportingFiles>
                            <supportingFilesToGenerate>ApiUtil.java,RFC3339DateFormat.java</supportingFilesToGenerate>
                            <configOptions>
                                <sourceFolder>.</sourceFolder>
                                <includeCollapsedSpecInArtifacts>true</includeCollapsedSpecInArtifacts>
                                <serializationLibrary>jackson</serializationLibrary>
                                <booleanGetterPrefix>is</booleanGetterPrefix>
                                <openApiNullable>false</openApiNullable>
                                <oas3>true</oas3>
                                <title>${project.build.finalName}</title>
                                <useJakartaEe>true</useJakartaEe>
                                <useBeanValidation>true</useBeanValidation>
                                <useOneOfDiscriminatorLookup>true</useOneOfDiscriminatorLookup>
                                <performBeanValidation>true</performBeanValidation>
                                <useGzipFeature>true</useGzipFeature>
                                <useEnumCaseInsensitive>true</useEnumCaseInsensitive>
                                <useOneOfInterfaces>true</useOneOfInterfaces>
                                <withSeparateModelsAndApi>true</withSeparateModelsAndApi>
                                <ignoreAnyOfInEnum>true</ignoreAnyOfInEnum>
                                <library>spring-boot</library>
                                <dateLibrary>java8</dateLibrary>
                                <delegatePattern>true</delegatePattern>
                                <useSpringfox>false</useSpringfox>
                                <modelPropertyNaming>camelCase</modelPropertyNaming>
                                <legacyDiscriminatorBehavior>false</legacyDiscriminatorBehavior>
                                <prependFormOrBodyParameters>true</prependFormOrBodyParameters>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-meta</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-codegen</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-meta-extensions</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-meta-extensions-liquibase</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <generator>
                        <strategy>
                            <matchers>
                                <tables>
                                    <table>
                                        <expression>frequently</expression>
                                        <recordImplements>ru.sber.transport.address.providers.model.IndexedRecord</recordImplements>
                                    </table>
                                    <table>
                                        <expression>favorite</expression>
                                        <recordImplements>ru.sber.transport.address.providers.model.IndexedRecord</recordImplements>
                                    </table>
                                </tables>
                            </matchers>
                        </strategy>
                        <database>
                            <name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
                            <forcedTypes>
                                <forcedType>
                                    <userType>ru.sber.transport.address.database.TsVector</userType>
                                    <binding>ru.sber.transport.address.database.TsVectorBinding</binding>
                                    <!-- A Java regex matching fully-qualified columns, attributes, parameters. Use the pipe to separate several expressions. -->
                                    <includeExpression>document</includeExpression>
                                </forcedType>
                            </forcedTypes>
                            <properties>
                                <property>
                                    <key>scripts</key>
                                    <value>/db/changelog-master.yml</value>
                                </property>
                                <property>
                                    <key>rootPath</key>
                                    <value>${project.basedir}/src/main/resources</value>
                                </property>
                                <property>
                                    <key>includeLiquibaseTables</key>
                                    <value>false</value>
                                </property>
                                <property>
                                    <key>unqualifiedSchema</key>
                                    <value>none</value>
                                </property>
                                <property>
                                    <key>renderNameCase</key>
                                    <value>lower</value>
                                </property>
                                <property>
                                    <key>defaultNameCase</key>
                                    <value>lower</value>
                                </property>
                            </properties>
                        </database>
                        <generate>
                            <deprecated>false</deprecated>
                            <records>true</records>
                            <javaTimeTypes>true</javaTimeTypes>
                        </generate>
                        <target>
                            <packageName>ru.sber.transport.database</packageName>
                            <directory>target/generated-sources/java/</directory>
                        </target>
                    </generator>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.4.3</version>
                <configuration>
                    <from>
                        <image>${source.image}</image>
                        <platforms>
                            <platform>
                                <architecture>amd64</architecture>
                                <os>linux</os>
                            </platform>
                        </platforms>
                        <auth>
                            <!--suppress MavenModelInspection -->
                            <username>${jib.to.auth.username}</username>
                            <!--suppress MavenModelInspection -->
                            <password>${jib.to.auth.password}</password>
                        </auth>
                    </from>
                    <to>
                        <!--suppress UnresolvedMavenProperty -->
                        <image>${jib.to.url}/transport/${project.build.finalName}:${image-tag}</image>
                        <tags>${image-tag}</tags>
                    </to>
                    <container>
                        <jvmFlags>
                            <jvmFlag>-Dfile.encoding=${project.build.sourceEncoding}</jvmFlag>
                            <jvmFlag>-Dsun.stderr.encoding=${project.build.sourceEncoding}</jvmFlag>
                            <jvmFlag>-Dsun.stdout.encoding=${project.build.sourceEncoding}</jvmFlag>
                            <jvmFlag>-Dnative.encoding=${project.build.sourceEncoding}</jvmFlag>
                            <jvmFlag>-server</jvmFlag>
                            <jvmFlag>-XX:+AlwaysActAsServerClassMachine</jvmFlag>
                            <jvmFlag>-XX:+UseStringDeduplication</jvmFlag>
                            <jvmFlag>-XX:+PerfDisableSharedMem</jvmFlag>
                        </jvmFlags>
                        <creationTime>${maven.build.timestamp}</creationTime>
                        <labels>
                            <maintainer>${user.name}</maintainer>
                            <version>${project.version}</version>
                        </labels>
                        <creationTime>${maven.build.timestamp}</creationTime>
                    </container>
                    <!--suppress MavenModelInspection -->
                    <allowInsecureRegistries>${jib.allowInsecureRegistries}</allowInsecureRegistries>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <release>${maven.compiler.target}</release>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.springframework</groupId>
                            <artifactId>spring-context-indexer</artifactId>
                            <version>6.1.11</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>-Amapstruct.defaultComponentModel=spring</compilerArg>
                        <compilerArg>-Amapstruct.defaultInjectionStrategy=constructor</compilerArg>
                        <compilerArg>-Amapstruct.verbose=true</compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.github.ascopes</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <configuration>
                    <sourceDirectories>
                        <sourceDirectory>${basedir}/../_documents/api/grpc/geo</sourceDirectory>
                    </sourceDirectories>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
