branch:
  #регулярное выражение для игнорирования пр-ов из ветки такой-то
  ignore_regex: "^master$|^release/.*$|^hotfix/.*$"
# режим ревью: можно выбрать либо использовать одновременно
#- SUGGESTIONS # предлагает изменение в коде
#- REPORT # оставляет комментарий в формате единого отчета
review_mode: [SUGGESTIONS]
# имя файла с инструкциями (отдельное ревью)
customer_instructions_file_name: "instructions.md"
# модификация существующих режимов
extra_instruction:
  #Данная инструкция модифирует поведение режима предложения, оставьте пустыми если не хотите менять поведение агента
  suggestion: "Предлагай изменения в формате: было: старый_код, предлагаю: предлагаемый_код. Не предлагай изменить бизнес логику. Особое внимание удели производительности"
  #Данная инструкция модифицирует поведение режима отчета, оставьте пустыми если не хотите менять поведение агента
  #report: "Инструкция"
# Фильтрация по серьезности дефектов
severity_type: ["MAJOR", "MINOR", "INFO"]
auto_approve: true
