DROP INDEX CONTRACTORS.CONTRACTOR_NAME_TIN_UNIQUE_INDEX;

ALTER TABLE CONTRACTORS.CONTRACTOR
    ADD CONSTRAINT CONTRACTOR_TIN_KEY UNIQUE (TIN);

ALTER TABLE CONTRACTORS.CONTRACTOR
    ADD CONSTRAINT CONTRACTOR_MSRN_KEY UNIQUE (MSRN);

ALTER TABLE CONTRACTORS.CONTRACTOR
    ADD CONSTRAINT CONTRACTOR_NAME_KEY UNIQUE (NAME);