//
// Generated by GigaCode AI.
//
package ru.sber.transport.notifications.services.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import ru.sber.transport.notifications.database.dao.settings.NotificationSettingsRepository;
import ru.sber.transport.notifications.database.dao.userNotificationSettings.UserNotificationSettingsRepository;
import ru.sber.transport.notifications.database.model.HasContactData;
import ru.sber.transport.notifications.database.model.coprorate.Employee;
import ru.sber.transport.notifications.database.model.settings.channel.ChannelType;
import ru.sber.transport.notifications.database.model.settings.notification.NotificationClass;
import ru.sber.transport.notifications.database.model.settings.userNotification.UserNotificationSettings;
import ru.sber.transport.notifications.dto.userNotification.UserNotificationSettingsSearchDto;
import ru.sber.transport.notifications.mapper.userNotificationSettings.UserNotificationSettingsMapper;
import ru.sber.transport.notifications.services.UserNotificationSettingsSpecService;

import java.util.*;
import java.util.stream.IntStream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class UserNotificationSettingsServiceImplGCTest {

    @Mock
    private UserNotificationSettingsMapper mapper;

    @Mock
    private UserNotificationSettingsRepository repository;

    @Mock
    private UserNotificationSettingsSpecService<UserNotificationSettingsSearchDto> specService;

    @Mock
    private NotificationSettingsRepository notificationSettingsRepository;

    @InjectMocks
    private UserNotificationSettingsServiceImpl service;

    private List<UserNotificationSettings> userNotificationSettingsList;


    @BeforeEach
    public void setUp() {
        userNotificationSettingsList = IntStream.range(0, 4)
                .mapToObj(i -> i == 3)
                .map(lie -> UserNotificationSettings.builder()
                        .id(UUID.randomUUID())
                        .userId(UUID.randomUUID())
                        .notificationId(UUID.randomUUID())
                        .notificationClass(NotificationClass.REQUEST_CARGO)
                        .name("Водитель/курьер на точке загрузки")
                        .smsActive(lie)
                        .pushActive(lie)
                        .emailActive(lie)
                        .smsEnabled(true)
                        .pushEnabled(true)
                        .emailEnabled(true)
                        .parentId(UUID.randomUUID())
                        .build())
                .toList();
    }

    @ParameterizedTest
    @ValueSource(ints = {1, 4})
    void testUpdateChannelMap(int size) {
        HasContactData receiver = Employee.builder()
                .id(UUID.randomUUID())
                .userId(UUID.randomUUID())
                .departmentId(UUID.randomUUID())
                .firstName("John")
                .lastName("Doe")
                .patronymic("Smith")
                .email("john.doe@example.com")
                .phone("123-456-7890")
                .organizationId(UUID.randomUUID())
                .build();

        Map<ChannelType, String> messages = new HashMap<>();
        messages.put(ChannelType.SMS, "message");
        messages.put(ChannelType.PUSH, "message");
        messages.put(ChannelType.EMAIL, "message");

        when(repository.findByUserIdAndNotificationId(any(UUID.class), any(UUID.class))).thenReturn(Optional.of(userNotificationSettingsList.get(size - 1)));

        service.updateChannelMap(receiver, messages, UUID.randomUUID());

        verify(repository, times(1)).findByUserIdAndNotificationId(any(UUID.class), any(UUID.class));
        assertThat(messages).hasSize(size - 1);
    }

}