spring.cloud.stream:
  binders:
    kafka-avro:
      type: kafka
      environment:
        spring.cloud.stream.kafka:
          default:
            consumer:
              enableDlq: true
              topic.properties:
                cleanup.policy: compact,delete
                retention.ms: 604800000
            producer:
              topic.properties:
                cleanup.policy: compact,delete
                retention.ms: 604800000
          binder:
            configuration:
              security.protocol: ${KAFKA_SECURITY_PROTOCOL:SSL}
              ssl:
                endpoint.identification.algorithm: ""
                client.auth: required
                enabled.protocols: TLSv1.2
                truststore:
                  location: ${KAFKA_SSL_TRUSTSTORE_LOCATION:}
                  password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD:}
                keystore:
                  location: ${KAFKA_SSL_KEYSTORE_LOCATION:}
                  password: ${KAFKA_SSL_KEYSTORE_PASSWORD:}
                key.password: ${KAFKA_SSL_KEY_PASSWORD:}
            auto-alter-topics: true
            autoAddPartitions: true
            brokers:
              - ${KAFKA_SSL_BROKERS}
            producerProperties:
              auto.register.schemas: true
              key.serializer: org.springframework.kafka.support.serializer.JsonSerializer
              value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
              compression.type: gzip
              schema.reflection: true
              schema.registry.url: ${SCHEMA_REGISTRY_URL}
            consumerProperties:
              key.serializer: org.springframework.kafka.support.serializer.JsonSerializer
              value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
              standardHeaders: both
              compression.type: gzip
              schema.registry.url: ${SCHEMA_REGISTRY_URL}
              specific.avro.reader: true
  bindings:
    pushInputSsl-in-0:
      group: ${spring.application.name}-avro
      destination: service-push
      binder: kafka-avro
      content-type: application/*+avro
      producer:
        useNativeEncoding: true