server:
    port: @server.port@

spring:
    threads:
      virtual:
        enabled: true
    config:
        import: optional:configserver:${spring.cloud.config.uri}
    jackson:
        default-property-inclusion: non_null
    application:
        name: geo
        version: @project.version@
    liquibase:
        change-log: db/changelog-master.yml
        url: ${spring.datasource.url}
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}
        database-change-log-table: changelog_${spring.application.name}
        database-change-log-lock-table: changelog_${spring.application.name}_lock
        liquibase-schema: ${MIGRATIONS_SCHEMA:public}
ssl:
    support: true
    client:
        enabled: ${CLIENT_ENABLED:false}
        store:
            path: ${CLIENT_CERTIFICATE:}
            password: ${CLIENT_STORE_PASSWORD:}
        password: ${CLIENT_CERT_PASSWORD:}
    trust:
        enabled: ${TRUST_ENABLED:false}
        store:
            path: ${TRUST_CERTIFICATE:}
            password: ${TRUST_CERT_PASSWORD:}
geo:
    method: GET
    errorMessagesPath: meta.error.message
    geoCoding:
        url: /3.0
        reverse:
            url: /items/geocode?fields=items.point,items.address,items.adm_div&page_size=1&page_size=50
            format:
                request:
                    fields:
                        latitude: lat
                        longitude: lon
                        sort: sort
                        type: type
                        radius: radius
                response:
                    root: result.items
                    fields:
                        street: address.components.street
                        house: address.components.number
                        region: adm_div[type=region].name
                        district: adm_div[type=district_area].name
                        city: adm_div[type=city].name
                        settlement: adm_div[type=settlement].name
                        living_area: adm_div[type=living_area].name
                        place: adm_div[type=place].name
                        country: adm_div[type=country].name
                        latitude: (point|geocoded_by).lat
                        longitude: (point|geocoded_by).lon
                        type: type
                        point: point
                        name: name
                        subtype: subtype
            sort:
                distance: distance
            requestType:
                type: building
        parking:
            url: /items?q=Московский%20паркинг,%20Москва,%20Объект&fields=items.geometry.centroid,items.geometry.hover,items.geometry.selection,items.attribute_groups,items.name_ex,items.is_paid,items.point&page_size=1&page_size=10
            format:
                request:
                    fields:
                        latitude: lat
                        longitude: lon
                        sort: sort
                        type: type
                        radius: radius
                response:
                    root: result.items
                    fields:
                        id: id
                        attribute_groups: attribute_groups
                        name_ex: name_ex
                        is_paid: is_paid
                        point: point
                        geometry: geometry
                        full_name: full_name
                        name: name
                        type: type
                        purpose_name: purpose_name
            sort:
                distance: distance
            requestType:
                type: branch
        parkingByNumber:
            url: /items?q=Москва,%20Объект,%20Московский%20паркинг%20зона%20&fields=items.geometry.centroid,items.geometry.hover,items.geometry.selection,items.attribute_groups,items.name_ex,items.is_paid,items.point
            format:
                request:
                    fields:
                        location: q
                        sort: sort
                        type: type
                response:
                    root: result.items
                    fields:
                        id: id
                        attribute_groups: attribute_groups
                        name_ex: name_ex
                        is_paid: is_paid
                        point: point
                        geometry: geometry
                        full_name: full_name
                        name: name
                        type: type
                        purpose_name: purpose_name
            sort:
                distance: distance
            requestType:
                type: branch
        coder:
            url: "/suggests?locale=ru_RU&fields=items.point,items.address,items.adm_div&page_size=10&type=adm_div.region,adm_div.district_area,adm_div.city,adm_div.settlement,adm_div.district,adm_div.living_area,adm_div.division,adm_div.place,street,branch,building,road,attraction,crossroad,route,route_type,station,station.metro,user_queries,attribute,rubric,meta_rubric,org,market.category,market.attribute,market.suggestor_category,special,coordinates,kilometer_road_sign"
            urlItems: "/items?fields=items.point,items.address,items.adm_div&page_size=5"
            format:
                request:
                    fields:
                        query: q
                        center: location
                response:
                    root: result.items
                    fields:
                        street: address.components.street
                        house: address.components.number
                        region: adm_div[type=region].name
                        district: adm_div[type=district_area].name
                        city: adm_div[type=city].name
                        settlement: adm_div[type=settlement].name
                        living_area: adm_div[type=living_area].name
                        place: adm_div[type=place].name
                        country: adm_div[type=country].name
                        latitude: (point|geocoded_by).lat
                        longitude: (point|geocoded_by).lon
                        type: type
                        point: point
                        name: name
                        subtype: subtype
    routing:
        url: /carrouting/6.0.0/global
        method: POST
        route:
            format:
                request:
                    fields:
                        type: type
                        location: points
                        latitude: y
                        longitude: x
                response:
                    root: result
                    fields:
                        waypoints: waypoints.original_point
                        segments: maneuvers
                        distance: (total_distance  / 1000|outcoming_path.distance / 1000)
                        time: (total_duration|outcoming_path.duration)
                        coordinates: outcoming_path.geometry.selection
                        latitude: (lat|y)
                        longitude: (lon|x)
        type:
            car: stop
            path: points.type
    routeRecreation:
        url: /map_matching/1.0.0
        method: POST
        defaultBadPointTolerance: high
        format:
            request:
                fields:
                    latitude: lat
                    longitude: lon
                    time: utc
                    location: query
                    bad_point_tolerance: bad_point_tolerance
grpc:
    server:
        port: 6565