spring:
  cloud:
    stream:
      bindings:
        contractorOutputSsl-out-0:
          destination: service.contractor
          binder: kafka-ssl
        contractorTripUpdateOutputSsl-out-0:
          destination: service.contractor.update.trip
          binder: kafka-ssl
        dispatcherOutputSsl-out-0:
          destination: service.contractor.dispatcher
          binder: kafka-ssl
        vehicleOutputSsl-out-0:
          destination: service.contractor.vehicle
          binder: kafka-ssl
        shiftOutputSsl-out-0:
          destination: service.contractor.shift
          binder: kafka-ssl
        cargoPackageOutputSsl-out-0:
          destination: service.contractor.cargo.package
          binder: kafka-ssl
        usersOutputSsl-out-0:
          destination: service.users
          binder: kafka-ssl
        driverOutputSsl-out-0:
          destination: service.contractor.driver
          binder: kafka-ssl
        requestOutputSsl-out-0:
          destination: service.contractor.request
          binder: kafka-ssl
        employeeRoleOutputSsl-out-0:
          destination: service.contractor.employee.role
          binder: kafka-ssl
        employeesInputSsl-in-0:
          group: ${spring.application.name}
          destination: service.organization.employee
          binder: kafka-ssl
        driverInputSsl-in-0:
          destination: service.trip.driver
          group: ${spring.application.name}
          binder: kafka-ssl
        shiftInputSsl-in-0:
          destination: service.trip.shift
          group: ${spring.application.name}
          binder: kafka-ssl
