ALTER TABLE CONTRACTORS.DRIVER
    DROP COLUMN AUTOPARK_ID,
    DROP COLUMN IS_ACTIVE,
    DROP COLUMN CONTACT_PHONE_NUMBER,
    DROP COLUMN DRIVER_LICENSE_NUMBER,
    DROP COLUMN SERVICE_PROVIDER_LICENSE_NUMBER,
    DROP COLUMN EXPERIENCE;