syntax = "proto3";

package ru.sber.transport.limits.grpc.service;

/*
 * Сервис для работы с лимитами
 */
service LimitService {

  /*
   * Резервирование средств. Если резерв уже существует и не зафиксирован, он отменится, и будет создан новый.
   * Если во время создания нового не хватит средств, значение будет возвращено на предыдущее.
   * Если требуется отменить всю цепочку резервов, необходимо с клиента на сервер кинуть ошибку
   */
  rpc reserve(stream ReserveRequest) returns(stream Response) {}

  /*
   * Подтверждение резерва. Резерв помечается как "потрачен". Поддерживается массовое резервирование.
   * Если требуется отменить всю цепочку фиксаций, необходимо с клиента на сервер кинуть ошибку
   */
  rpc confirm(stream FixRequest) returns(stream Response) {}

  /*
   * Отмена резерва. Резерв помечается как "отменен", средства возвращаются на счет.
   * Если требуется отменить всю цепочку фиксаций, необходимо с клиента на сервер кинуть ошибку
   */
  rpc cancel(stream FixRequest) returns(stream Response) {}

}

/*
 * Модель резерва средств
 */
message ReserveRequest {

  /*
   * Идентификатор лимитируемой операции
   */
  string id = 1;

  /*
   * Вид лимитируемой услуги
   */
  string service = 2;

  /*
   * Тип лимитируемой услуги
   */
  string type = 3;

  /*
   * Получатель услуги
   */
  string consumer = 4;

  /*
   * Сумма лимита
   */
  Cost cost = 5;

  /*
   * Предполагаемая дата предоставления услуги
   */
  DateTime date = 6;

}

/*
 * Модель даты
 */
message DateTime {

  /*
   * Год
   */
  uint32 year = 1;

  /*
   * Месяц
   */
  uint32 month = 2;

  /*
   * День
   */
  uint32 day = 3;

  /*
   * Часы
   */
  uint32 hour = 4;

  /*
   * Минуты
   */
  uint32 minute = 5;

  /*
   * Секунды
   */
  uint32 second = 6;

  /*
   * Миллисекунды
   */
  uint32 millis = 7;

  /*
   * Временная зона
   */
  string zone = 8;
}

/*
 * Модель фиксирования резерва лимита
 */
message FixRequest {

  /*
   * Идентификатор лимитируемой операции
   */
  string id = 1;

}

/*
 * Модель стоимости
 */
message Cost {

  /*
   * Целая часть
   */
  uint64 integerPart = 1;

  /*
   * Дробная часть
   */
  uint32 fractionPart = 2;

}

/*
 * Ответ на запрос лимита
 */
message Response {

  /*
   * Идентификатор лимитируемой операции
   */
  string id = 1;

  /*
   * Статус лимитируемой операции
   */
  Status status = 2;

}

/*
 * Возможные статусы работы с лимитами
 */
enum Status {

  /*
   * Операция выполнена
   */
  OK = 0;

  /*
   * Средств на лимите не достаточно
   */
  NOT_SUFFICIENT = 1;

  /*
   * Вид услуги не доступен
   */
  SERVICE_NOT_AVAILABLE = 2;

  /*
   * Тип услуги не доступен
   */
  TYPE_NOT_AVAILABLE = 3;

  /*
   * Данные резерва не найдены
   */
  DATA_NOT_FOUND = 4;
}