<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>parent</artifactId>
        <groupId>ru.sber.transport.geo</groupId>
        <version>4.23</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>application</artifactId>
    <version>5.12</version>

    <properties>
        <server.port>8006</server.port>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>${maven.compiler.source}</maven.compiler.target>
        <source.image>
            registry-ci.delta.sbrf.ru/dev/ci02351878/ci02353146_transport_dev/transport/open-jdk:21.0.3
        </source.image>
        <image-tag>${project.version}-${user.name}</image-tag>
        <liquibase-core.version>4.32.0</liquibase-core.version>
        <tomcat.version>10.1.42</tomcat.version>
        <spring-cloud-dependencies.version>2025.0.0</spring-cloud-dependencies.version>
        <embedded-postgres.version>4.10</embedded-postgres.version>
        <collections.version>4.6</collections.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <transport-core.version>3.24</transport-core.version>
        <authorization.version>4.10</authorization.version>
        <properties-loader.version>3.16.0.1</properties-loader.version>
        <audit.version>3.16</audit.version>
        <jooq-database.version>3.16</jooq-database.version>
        <documentation-starter.version>4.6</documentation-starter.version>
        <extended-rest-template.version>3.18</extended-rest-template.version>
        <instancio-junit.version>5.0.1</instancio-junit.version>
        <grpc-bom.version>4.16</grpc-bom.version>
        <grpc.version>4.23</grpc.version>
        <ext-logging.version>260408-1</ext-logging.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>ru.sber.transport.grpc</groupId>
                <artifactId>bom</artifactId>
                <version>${grpc-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- Spring -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-indexer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-vault-config</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>authorization</artifactId>
            <version>${authorization.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>properties-loader</artifactId>
            <version>${properties-loader.version}</version>
        </dependency>

        <!-- Database -->
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>audit</artifactId>
            <version>${audit.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.grpc</groupId>
            <artifactId>server</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>jooq-database</artifactId>
            <version>${jooq-database.version}</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
            <version>${liquibase-core.version}</version>
        </dependency>

        <!-- Utils -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>transport-core</artifactId>
            <version>${transport-core.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>documentation-starter</artifactId>
            <version>${documentation-starter.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>extended-rest-template</artifactId>
            <version>${extended-rest-template.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>

        <!-- Utils -->
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>collections</artifactId>
            <version>${collections.version}</version>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.geo</groupId>
            <artifactId>grpc</artifactId>
            <version>${grpc.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-vault-config</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>ext-logging</artifactId>
            <version>${ext-logging.version}</version>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.instancio</groupId>
            <artifactId>instancio-junit</artifactId>
            <version>${instancio-junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport.grpc</groupId>
            <artifactId>test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ru.sber.transport</groupId>
            <artifactId>embedded-postgres</artifactId>
            <version>${embedded-postgres.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.liquibase</groupId>
                    <artifactId>liquibase-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>geo</finalName>
        <plugins>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.4.3</version>
                <configuration>
                    <containerizingMode>packaged</containerizingMode>
                    <from>
                        <image>${source.image}</image>
                        <platforms>
                            <platform>
                                <architecture>amd64</architecture>
                                <os>linux</os>
                            </platform>
                        </platforms>
                        <auth>
                            <!--suppress MavenModelInspection -->
                            <username>${jib.to.auth.username}</username>
                            <!--suppress MavenModelInspection -->
                            <password>${jib.to.auth.password}</password>
                        </auth>
                    </from>
                    <to>
                        <!--suppress UnresolvedMavenProperty -->
                        <image>${jib.to.url}/transport/${project.build.finalName}:${image-tag}</image>
                        <tags>${image-tag}</tags>
                    </to>
                    <container>
                        <jvmFlags>
                            <jvmFlag>-Dfile.encoding=${project.build.sourceEncoding}</jvmFlag>
                            <jvmFlag>-Dsun.stderr.encoding=${project.build.sourceEncoding}</jvmFlag>
                            <jvmFlag>-Dsun.stdout.encoding=${project.build.sourceEncoding}</jvmFlag>
                            <jvmFlag>-Dnative.encoding=${project.build.sourceEncoding}</jvmFlag>
                            <jvmFlag>-XX:MaxRAMPercentage=75</jvmFlag>
                            <jvmFlag>-XX:+UseG1GC</jvmFlag>
                            <jvmFlag>-server</jvmFlag>
                            <jvmFlag>-Dspring.config.additional-location=optional:file:/app/resources/,optional:file:/app/resources/config/</jvmFlag>
                        </jvmFlags>
                        <creationTime>${maven.build.timestamp}</creationTime>
                        <labels>
                            <maintainer>${user.name}</maintainer>
                            <version>${project.version}</version>
                        </labels>
                        <creationTime>${maven.build.timestamp}</creationTime>
                    </container>
                    <!--suppress MavenModelInspection -->
                    <allowInsecureRegistries>${jib.allowInsecureRegistries}</allowInsecureRegistries>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.6.0</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>-Amapstruct.defaultComponentModel=spring</compilerArg>
                        <compilerArg>-Amapstruct.defaultInjectionStrategy=constructor</compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>aot</id>
                        <phase>install</phase>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>${jooq.version}</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-meta</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-codegen</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-meta-extensions</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-meta-extensions-liquibase</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <generator>
                        <database>
                            <name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
                            <properties>
                                <property>
                                    <key>rootPath</key>
                                    <value>${project.basedir}/src/main/resources</value>
                                </property>
                                <property>
                                    <key>scripts</key>
                                    <value>/db/changelog-master.yml</value>
                                </property>
                                <property>
                                    <key>includeLiquibaseTables</key>
                                    <value>false</value>
                                </property>
                                <property>
                                    <key>unqualifiedSchema</key>
                                    <value>none</value>
                                </property>
                                <property>
                                    <key>renderNameCase</key>
                                    <value>lower</value>
                                </property>
                                <property>
                                    <key>defaultNameCase</key>
                                    <value>lower</value>
                                </property>
                            </properties>
                        </database>
                        <generate>
                            <records>true</records>
                            <javaTimeTypes>true</javaTimeTypes>
                        </generate>
                        <target>
                            <packageName>ru.sber.transport.geo.database</packageName>
                            <directory>target/generated-sources/java/</directory>
                        </target>
                    </generator>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
