export enum StoreNames {
  configStore = 'configStore',
  selfStore = 'selfStore',
  rootStore = 'rootStore',
  authStore = 'authStore',
  settingsStore = 'settingsStore',
  geoStore = 'geoStore',
  cargoStore = 'cargoStore',
  cargosStore = 'cargosStore',
  compensationStore = 'compensationStore',
  exchangeStore = 'exchangeStore',
  cargoMassStoreMultiple = 'cargoMassStoreMultiple',
  cargoTariffStore = 'cargoTariffStore',
  cargoTypeStore = 'cargoTypeStore',
  employeeStore = 'employeeStore',
  limitsStore = 'limitsStore',
  limitsRequestStore = 'limitsRequestStore',
  corporateStore = 'corporateStore',
  tripStore = 'tripStore',
  addressStore = 'addressStore',
  transportTypesStore = 'transportTypesStore',
  filesStore = 'filesStore',
  delegatesStore = 'delegatesStore',
  mappedStore = 'mappedStore',
}
