ALTER TABLE CONTRACTORS.DRIVER
    ADD COLUMN AUTOPARK_ID                     UUID REFERENCES CONTRACTORS.AUTOPARK (ID),
    ADD COLUMN IS_ACTIVE                       BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN CONTACT_PHONE_NUMBER            VARCHAR(50),
    ADD COLUMN RATING                          INT,
    ADD COLUMN DRIVER_LICENSE_NUMBER           VARCHAR,
    ADD COLUMN SERVICE_PROVIDER_LICENSE_NUMBER VARCHAR,
    ADD COLUMN EXPERIENCE                      VARCHAR;

COMMENT ON COLUMN CONTRACTORS.DRIVER.IS_ACTIVE IS 'Водитель активен';
COMMENT ON COLUMN CONTRACTORS.DRIVER.AUTOPARK_ID IS 'Идентификатор автопарка';
COMMENT ON COLUMN CONTRACTORS.DRIVER.CONTACT_PHONE_NUMBER IS 'Контактный телефон';
COMMENT ON COLUMN CONTRACTORS.DRIVER.RATING IS 'Рейтинг водителя';
COMMENT ON COLUMN CONTRACTORS.DRIVER.DRIVER_LICENSE_NUMBER IS 'Серия номер водительского удостоверения';
COMMENT ON COLUMN CONTRACTORS.DRIVER.SERVICE_PROVIDER_LICENSE_NUMBER IS 'Номер лицензии предоставления услуг';
COMMENT ON COLUMN CONTRACTORS.DRIVER.EXPERIENCE IS 'Стаж вождения';
