CREATE TABLE CONTRACTORS.DRIVER_LICENSE_CLASSES
(
    DRIVER_ID UUID       NOT NULL REFERENCES contractors.driver (id),
    CLASS     VARCHAR(3) NOT NULL,
    PRIMARY KEY (DRIVER_ID, CLASS)
);

COMMENT ON TABLE CONTRACTORS.DRIVER_LICENSE_CLASSES IS 'Категории прав водителей';
COMMENT ON COLUMN CONTRACTORS.DRIVER_LICENSE_CLASSES.DRIVER_ID IS 'Идентификатор водителя';
COMMENT ON COLUMN CONTRACTORS.DRIVER_LICENSE_CLASSES.CLASS IS 'Категория прав';
