server:
    port: 8050
spring:
    config:
        import: database.yml, kafka.yml, management.yml, import.yml
    security:
        user: #убираем запись в логах, по которой есть вопросы у безопасности
            name: anonymous
            password: ${random.uuid}
            roles: anonymous
        oauth2:
            resourceserver:
                jwt:
                    jws-algorithms: RS512
                    jwk-set-uri: ${JWKS_URI}
    main:
        banner-mode: off
    jackson:
        serialization:
            write_dates_as_timestamps: false
    application:
        name: vehicle
        version: @project.version@ #used in Main.class
grpc:
    server:
        port: 6565