ALTER TABLE CONTRACTORS.CONTRACTOR
    ADD COLUMN CONTACT_PHONE_NUMBER VARCHAR(50),
    ADD COLUMN CONTACT_PERSON_INFO VARCHAR(1000),
    ADD COLUMN RATING INT,
    ADD COLUMN IMG VARCHAR(2000);

COMMENT ON COLUMN CONTRACTORS.CONTRACTOR.CONTACT_PHONE_NUMBER IS 'Контактный телефон';
COMMENT ON COLUMN CONTRACTORS.CONTRACTOR.CONTACT_PERSON_INFO IS 'Информация о контактном лице';
COMMENT ON COLUMN CONTRACTORS.CONTRACTOR.RATING IS 'Рейтинг контрагента, от 0 до 500';
COMMENT ON COLUMN CONTRACTORS.CONTRACTOR.IMG IS 'URL логотипа';