ALTER TABLE CONTRACTORS.DRIVER
    ADD COLUMN LAST_NAME  VARCHAR(255),
    ADD COLUMN FIRST_NAME VARCHAR(255),
    ADD COLUMN PATRONYMIC VARCHAR(255),
    ADD COLUMN PASSPORT   VARCHAR(11);

UPDATE CONTRACTORS.DRIVER
SET LAST_NAME  = P.LAST_NAME,
    FIRST_NAME = P.FIRST_NAME,
    PATRONYMIC = P.PATRONYMIC,
    PASSPORT   = ''
FROM CONTRACTORS.DRIVER_USER_PROFILE AS P
WHERE P.ID = USER_PROFILE_ID;

ALTER TABLE CONTRACTORS.DRIVER
    ALTER COLUMN FIRST_NAME SET NOT NULL,
    ALTER COLUMN PASSPORT SET NOT NULL,
    ALTER COLUMN LAST_NAME SET NOT NULL;

ALTER TABLE CONTRACTORS.DRIVER
    DROP CONSTRAINT DRIVER_USER_PROFILE_FK;

CREATE UNIQUE INDEX DRIVER_CONTRACTOR_UNIQUE_INDEX
    ON CONTRACTORS.DRIVER(CONTRACTOR_ID, PASSPORT);

COMMENT ON INDEX CONTRACTORS.DRIVER_CONTRACTOR_UNIQUE_INDEX IS 'Уникальность водителя в рамках контрагента';

DROP TABLE CONTRACTORS.DRIVER_USER_PROFILE;

ALTER TABLE CONTRACTORS.DRIVER
    DROP COLUMN USER_PROFILE_ID;