CREATE UNIQUE INDEX CONTRACTOR_NAME_TIN_UNIQUE_INDEX ON CONTRACTORS.CONTRACTOR(NAME, TIN);
COMMENT ON INDEX CONTRACTORS.CONTRACTOR_NAME_TIN_UNIQUE_INDEX IS 'Уникальность контрагента по имени + инн';

ALTER TABLE CONTRACTORS.CONTRACTOR
    DROP CONSTRAINT CONTRACTOR_TIN_KEY;

ALTER TABLE CONTRACTORS.CONTRACTOR
    DROP CONSTRAINT CONTRACTOR_MSRN_KEY;

ALTER TABLE CONTRACTORS.CONTRACTOR
    DROP CONSTRAINT CONTRACTOR_NAME_KEY;