ALTER TABLE IF EXISTS CONTRACTORS.DRIVER_TAG DROP CONSTRAINT FK_DRIVER_TAG_CONTRACTOR;

DROP TABLE CONTRACTORS.DRIVER_TAG_CONNECTOR;
ALTER TABLE CONTRACTORS.DRIVER_TAG
    DROP COLUMN name;
ALTER TABLE CONTRACTORS.DRIVER_TAG
    ADD COLUMN driver_id uuid;
ALTER TABLE CONTRACTORS.DRIVER_TAG
    RENAME COLUMN id TO tag_id;