ALTER TABLE CONTRACTORS.DRIVER_TAG
    RENAME COLUMN tag_id TO id;
ALTER TABLE CONTRACTORS.DRIVER_TAG
    DROP COLUMN driver_id;
ALTER TABLE CONTRACTORS.DRIVER_TAG
    ADD COLUMN name VARCHAR(128) NOT NULL default '';

CREATE TABLE CONTRACTORS.DRIVER_TAG_CONNECTOR
(
    TAG_ID        UUID NOT NULL,
    DRIVER_ID     UUID NOT NULL,
    PRIMARY KEY(TAG_ID, DRIVER_ID),
    foreign key (TAG_ID) references CONTRACTORS.DRIVER_TAG (id),
    foreign key (DRIVER_ID) references CONTRACTORS.DRIVER (id)
);

COMMENT ON TABLE CONTRACTORS.DRIVER_TAG_CONNECTOR is 'Таблица связей: признак водителя - водитель';
ALTER TABLE IF EXISTS CONTRACTORS.DRIVER_TAG
    ADD CONSTRAINT FK_DRIVER_TAG_CONTRACTOR FOREIGN KEY (CONTRACTOR_ID) REFERENCES CONTRACTORS.CONTRACTOR;