ALTER TABLE CONTRACTORS.VEHICLE
    ADD CONSTRAINT vehicle_passport_key UNIQUE (PASSPORT);

ALTER TABLE CONTRACTORS.VEHICLE
    ADD CONSTRAINT vehicle_state_number_key UNIQUE (STATE_NUMBER);

ALTER TABLE CONTRACTORS.VEHICLE
    ADD CONSTRAINT vehicle_vin_key UNIQUE (VIN);