export enum TableField {
  humanReadableId = 'humanReadableId',
  transportType = 'transportType',
  fraudMarkers = 'fraudMarkers',
  desiredDate = 'desiredDate',
  passenger = 'passenger',
  approvalDate = 'approvalDate',
  approver = 'approver',
  autoApproval = 'autoApproval',
  plannedCost = 'plannedCost',
  actualCost = 'actualCost',
  departureAddress = 'departureAddress',
  intermediatePointsCount = 'intermediatePointsCount',
  destinationAddress = 'destinationAddress',
  status = 'status',
  purpose = 'purpose',
  department = 'department',
}
