import * as t from 'io-ts';

export enum TransportTypes {
  TAXI = 'TAXI',
  PUBLIC = 'PUBLIC',
  PERSONAL = 'PERSONAL',
  CARSHARING = 'CARSHARING',
  BICYCLE = 'BICYCLE',
  WALK = 'WALK',
  SCOOTER = 'SCOOTER',
  DEDICATED = 'DEDICATED',
  INDIVIDUAL = 'INDIVIDUAL',
  COURIER = 'COURIER',
  INTERREGIONAL = 'INTERREGIONAL',
  DOMESTIC_COURIER = 'DOMESTIC_COURIER',
  GROUP_TRANSFER = 'GROUP_TRANSFER',
}

export const TransportTypeDescriptions: Record<TransportTypes, string> = {
  TAXI: 'Такси',
  PUBLIC: 'Общественный',
  PERSONAL: 'Личный',
  CARSHARING: 'Каршеринг',
  BICYCLE: 'Велосипед',
  WALK: 'Пешком',
  SCOOTER: 'Самокат',
  DEDICATED: 'Доставка сборного груза',
  INDIVIDUAL: 'Доставка выделенным транспортом',
  COURIER: 'Курьер',
  INTERREGIONAL: 'Межрегиональная',
  DOMESTIC_COURIER: 'Внутренний курьер',
  GROUP_TRANSFER: 'Трансфер',
};

export const TransportTypeLongDescriptions: Record<TransportTypes, string> = {
  TAXI: 'Такси',
  PUBLIC: 'Общественный транспорт',
  PERSONAL: 'Личный транспорт',
  CARSHARING: 'Каршеринг',
  BICYCLE: 'Велосипед',
  WALK: 'Пешком',
  SCOOTER: 'Самокат',
  DEDICATED: 'Доставка сборного груза',
  INDIVIDUAL: 'Доставка выделенным транспортом',
  COURIER: 'Курьер',
  INTERREGIONAL: 'Межрегиональная',
  DOMESTIC_COURIER: 'Внутренний курьер',
  GROUP_TRANSFER: 'Трансфер',
};

export enum TransportTypesCargo {
  DEDICATED = 'DEDICATED',
  COURIER = 'COURIER',
  INTERREGIONAL = 'INTERREGIONAL',
  DOMESTIC_COURIER = 'DOMESTIC_COURIER',
  INDIVIDUAL = 'INDIVIDUAL',
}

export const TransportTypeCargoDescriptions: Record<TransportTypesCargo, string> = {
  DEDICATED: 'Доставка сборного груза',
  COURIER: 'Курьер',
  INTERREGIONAL: 'Межрегиональная',
  DOMESTIC_COURIER: 'Внутренний курьер',
  INDIVIDUAL: 'Доставка выделенным транспортом',
};

export const OrganizationTransportTypes = t.strict({
  transportType: t.string,
  active: t.boolean,
});

export type OrganizationTransportTypes = t.TypeOf<typeof OrganizationTransportTypes>;

export const TransportType = t.strict({
  id: t.string,
  name: t.string,
  rusName: t.string,
});

export type TransportType = t.TypeOf<typeof TransportType>;

export enum TransportCompensations {
  CITY_TRIP_COMPENSATION = 'CITY_TRIP_COMPENSATION',
  SUBURB_TRIP_COMPENSATION = 'SUBURB_TRIP_COMPENSATION',
  TRAVEL_CARD_COMPENSATION = 'TRAVEL_CARD_COMPENSATION',
}

export enum TripStatusesEnum {
  ALL = 'ALL',
  CARSHARING_AWAITING_APPROVAL = 'CARSHARING_AWAITING_APPROVAL',
  CARSHARING_APPROVED = 'CARSHARING_APPROVED',
  CARSHARING_DECLINED = 'CARSHARING_DECLINED',
  CARSHARING_AWAITING_SEARCH = 'CARSHARING_AWAITING_SEARCH',
  CARSHARING_TRIP_IN_PROGRESS = 'CARSHARING_TRIP_IN_PROGRESS',
  CARSHARING_AWAITING_TRIP_APPROVAL = 'CARSHARING_AWAITING_TRIP_APPROVAL',
  CARSHARING_TRIP_FINISHED = 'CARSHARING_TRIP_FINISHED',
  CARSHARING_CANCELLED = 'CARSHARING_CANCELLED',
  PUBLIC_AWAITING_APPROVAL = 'PUBLIC_AWAITING_APPROVAL',
  PUBLIC_TRIP_CONFIRMATION = 'PUBLIC_TRIP_CONFIRMATION',
  PUBLIC_AWAITING_AFFIRMATIVE = 'PUBLIC_AWAITING_AFFIRMATIVE',
  PUBLIC_ORDER_PAYMENT_FORMATION = 'PUBLIC_ORDER_PAYMENT_FORMATION',
  PUBLIC_PAYMENT_AWAITING = 'PUBLIC_PAYMENT_AWAITING',
  PUBLIC_PAYMENT_DONE = 'PUBLIC_PAYMENT_DONE',
  PUBLIC_PAYMENT_NOT_DONE = 'PUBLIC_PAYMENT_NOT_DONE',
  PUBLIC_CANCELLED = 'PUBLIC_CANCELLED',
  PERSONAL_AWAITING_APPROVAL = 'PERSONAL_AWAITING_APPROVAL',
  PERSONAL_APPROVED = 'PERSONAL_APPROVED',
  PERSONAL_AWAITING_SHARED_RIDE_APPROVAL = 'PERSONAL_AWAITING_SHARED_RIDE_APPROVAL',
  PERSONAL_SHARED_RIDE_DECLINED = 'PERSONAL_SHARED_RIDE_DECLINED',
  PERSONAL_TRIP_IN_PROGRESS = 'PERSONAL_TRIP_IN_PROGRESS',
  PERSONAL_AWAITING_TRIP_APPROVAL = 'PERSONAL_AWAITING_TRIP_APPROVAL',
  PERSONAL_ORDER_PAYMENT_FORMATION = 'PERSONAL_ORDER_PAYMENT_FORMATION',
  PERSONAL_PAYMENT_AWAITING = 'PERSONAL_PAYMENT_AWAITING',
  PERSONAL_PAYMENT_DONE = 'PERSONAL_PAYMENT_DONE',
  PERSONAL_PAYMENT_DECLINED = 'PERSONAL_PAYMENT_DECLINED',
  PERSONAL_CANCELLED = 'PERSONAL_CANCELLED',
  PERSONAL_TRIP_FINISHED = 'PERSONAL_TRIP_FINISHED',
  TAXI_AWAITING_APPROVAL = 'TAXI_AWAITING_APPROVAL',
  TAXI_APPROVED = 'TAXI_APPROVED',
  TAXI_AWAITING_SEARCH = 'TAXI_AWAITING_SEARCH',
  TAXI_DRIVER_SEARCH = 'TAXI_DRIVER_SEARCH',
  TAXI_DRIVER_FOUND = 'TAXI_DRIVER_FOUND',
  TAXI_DRIVER_ON_THE_WAY = 'TAXI_DRIVER_ON_THE_WAY',
  TAXI_DRIVER_ARRIVED = 'TAXI_DRIVER_ARRIVED',
  TAXI_TRIP_IN_PROGRESS = 'TAXI_TRIP_IN_PROGRESS',
  TAXI_TRIP_FINISHED = 'TAXI_TRIP_FINISHED',
  TAXI_CANCELLED = 'TAXI_CANCELLED',
  GROUP_TRANSFER_AWAITING_APPROVAL = 'GROUP_TRANSFER_AWAITING_APPROVAL',
  GROUP_TRANSFER_APPROVED = 'GROUP_TRANSFER_APPROVED',
  GROUP_TRANSFER_AWAITING_SEARCH = 'GROUP_TRANSFER_AWAITING_SEARCH',
  GROUP_TRANSFER_DRIVER_SEARCH = 'GROUP_TRANSFER_DRIVER_SEARCH',
  GROUP_TRANSFER_DRIVER_FOUND = 'GROUP_TRANSFER_DRIVER_FOUND',
  GROUP_TRANSFER_DRIVER_ON_THE_WAY = 'GROUP_TRANSFER_DRIVER_ON_THE_WAY',
  GROUP_TRANSFER_DRIVER_ARRIVED = 'GROUP_TRANSFER_DRIVER_ARRIVED',
  GROUP_TRANSFER_TRIP_IN_PROGRESS = 'GROUP_TRANSFER_TRIP_IN_PROGRESS',
  GROUP_TRANSFER_TRIP_FINISHED = 'GROUP_TRANSFER_TRIP_FINISHED',
  GROUP_TRANSFER_CANCELLED = 'GROUP_TRANSFER_CANCELLED',
}
