CREATE TABLE CONTRACTORS.IMPORTED_DATA
(
    ID          UUID         NOT NULL PRIMARY KEY,
    FILE_NAME   VARCHAR(255) NOT NULL,
    IMPORT_DATE DATE         NOT NULL,
    DATA_TYPE   VARCHAR(255)  NOT NULL,
    DATA        JSONB,
    STATUS      VARCHAR(50)
);

COMMENT ON TABLE CONTRACTORS.IMPORTED_DATA IS 'Сессии импорта';
COMMENT ON column CONTRACTORS.IMPORTED_DATA.ID IS 'Идентификатор сессии импорта';
COMMENT ON column CONTRACTORS.IMPORTED_DATA.FILE_NAME IS 'Имя файла откуда был произведен импорт';
COMMENT ON column CONTRACTORS.IMPORTED_DATA.IMPORT_DATE IS 'Дата импорта';
COMMENT ON column CONTRACTORS.IMPORTED_DATA.DATA_TYPE IS 'Тип импортируемой сущности';
COMMENT ON column CONTRACTORS.IMPORTED_DATA.DATA IS 'Данные импорта';
COMMENT ON column CONTRACTORS.IMPORTED_DATA.STATUS IS 'Статус импорта, READY_FOR_IMPORT или IMPORTED';
