export enum KEYS {
  EXCHANGE_DETAILED = 'exchangeDetailed',
  HISTORY = 'history',
  EVALUATION = 'evaluation',
  EXCHANGE_FILTERS = 'exchangeFilters',
}

export enum RouteStatusEnum {
  CARGO_PLANNING = 'CARGO_PLANNING',
  CARGO_PLANNING_FINISHED = 'CARGO_PLANNING_FINISHED',
  CARGO_AWAITING_DATA = 'CARGO_AWAITING_DATA',
  CARGO_AWAITING_TRANSFER = 'CARGO_AWAITING_TRANSFER',
  CARGO_TRANSFER_FINISHED = 'CARGO_TRANSFER_FINISHED',
  CARGO_SHIPMENT_FINISHED = 'CARGO_SHIPMENT_FINISHED',
  CARGO_DELIVERY_CONFIRMATION_FINISHED = 'CARGO_DELIVERY_CONFIRMATION_FINISHED',
  CARGO_CANCELED = 'CARGO_CANCELED',
}

enum CargoRequestStatuses {
  CARGO_PLANNING = 'CARGO_PLANNING',
  CARGO_AWAITING_APPROVAL = 'CARGO_AWAITING_APPROVAL',
  CARGO_APPROVED = 'CARGO_APPROVED',
  CARGO_AWAITING_DATA = 'CARGO_AWAITING_DATA',
  CARGO_DATA_RECEIVED = 'CARGO_DATA_RECEIVED',
  CARGO_AWAITING_TRANSFER = 'CARGO_AWAITING_TRANSFER',
  CARGO_TRANSFER_FINISHED = 'CARGO_TRANSFER_FINISHED',
  CARGO_AWAITING_SHIPMENT = 'CARGO_AWAITING_SHIPMENT',
  CARGO_SHIPMENT_FINISHED = 'CARGO_SHIPMENT_FINISHED',
  CARGO_AWAITING_DELIVERY_CONFIRMATION = 'CARGO_AWAITING_DELIVERY_CONFIRMATION',
  CARGO_DELIVERY_CONFIRMATION_FINISHED = 'CARGO_DELIVERY_CONFIRMATION_FINISHED',
  CARGO_CANCELED = 'CARGO_CANCELED',
  CARGO_TRIAL = 'CARGO_TRIAL',
  CARGO_LOST = 'CARGO_LOST',
}

export enum CargoHistoryTypeEnum {
  PAST = 'PAST',
  NOW = 'NOW',
  FUTURE = 'FUTURE',
}

export interface CargoHistory {
  status: CargoRequestStatuses;
  date: number;
  type: CargoHistoryTypeEnum;
}
