DROP TABLE CONTRACTORS.TRANSPORT;
CREATE TABLE CONTRACTORS.VEHICLE
(
    ID                 UUID PRIMARY KEY,
    PASSPORT           VARCHAR(50) UNIQUE ,
    STATE_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    VIN                VARCHAR(50) UNIQUE NOT NULL,
    BODY_TYPE          VARCHAR(255),
    CHASSIS_TYPE       VARCHAR(255),
    COLOR              VARCHAR(255),
    ECO_CLASS          VARCHAR(255) NOT NULL,
    FUEL_CONSUMPTION   DOUBLE PRECISION NOT NULL,
    INSURANCE_NUMBER   VARCHAR(50) NOT NULL,
    MANUFACTURE_YEAR   INTEGER CHECK (MANUFACTURE_YEAR >= 1900),
    MAX_ALLOWED_WEIGHT INTEGER,
    MILEAGE            INTEGER,
    PACKAGE_CLASS      VARCHAR(255) NOT NULL,
    TRANSMISSION_TYPE  VARCHAR(255),
    AUTOPARK_ID        UUID NOT NULL REFERENCES CONTRACTORS.AUTOPARK,
    MODEL_ID           UUID NOT NULL REFERENCES CONTRACTORS.CAR_MODEL

);

COMMENT ON TABLE CONTRACTORS.VEHICLE IS 'Транспортные средства';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.ID IS 'Идентификатор ТС';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.BODY_TYPE IS 'Тип кузова';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.CHASSIS_TYPE IS 'Тип привода';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.COLOR IS 'Цвет';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.ECO_CLASS IS 'Класс Эко';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.FUEL_CONSUMPTION IS 'Потребление топлива';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.INSURANCE_NUMBER IS 'Номер страховки';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.MANUFACTURE_YEAR IS 'Год производства';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.MAX_ALLOWED_WEIGHT IS 'Максимальный разрешенный вес';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.MILEAGE IS 'Пробег';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.PACKAGE_CLASS IS 'Комплектация';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.PASSPORT IS 'Паспортный номер';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.STATE_NUMBER IS 'Автомобильный номер';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.TRANSMISSION_TYPE IS 'Тип трансмиссии';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.VIN IS 'Идентификационный номер транспортного средства';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.AUTOPARK_ID IS 'Принадлежность к автопарку';
COMMENT ON COLUMN CONTRACTORS.VEHICLE.MODEL_ID IS 'Идентификатор модели';



