CREATE TABLE CONTRACTORS.CAR_MODEL
(
    ID    UUID PRIMARY KEY,
    NAME  VARCHAR(255) NOT NULL,
    YEAR  INTEGER      NOT NULL,
    BRAND VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS CAR_MODEL_YEAR_BRAND_UNIQUE_INDEX
    ON CONTRACTORS.CAR_MODEL (NAME, YEAR, BRAND);

COMMENT ON TABLE CONTRACTORS.CAR_MODEL IS 'Модели автомобилей';
COMMENT ON COLUMN CONTRACTORS.CAR_MODEL.ID IS 'Идентификатор модели';
COMMENT ON COLUMN CONTRACTORS.CAR_MODEL.NAME IS 'Название модели';
COMMENT ON COLUMN CONTRACTORS.CAR_MODEL.YEAR IS 'Год появления модели';
COMMENT ON COLUMN CONTRACTORS.CAR_MODEL.BRAND IS 'Марка';
COMMENT ON INDEX CONTRACTORS.CAR_MODEL_YEAR_BRAND_UNIQUE_INDEX IS 'Индекс уникальности Модели'