package ru.sberbank.ditsib.transport.vehicle.dto.files;

import java.math.BigDecimal;
import java.time.LocalDate;

public interface TransportReportProjection {
    
    String getInventoryNumber();
    String getAssetNumber();
    String getOfficialName();
    String getDepartmentName();
    String getTypeTitle();
    String getSubtypeTitle();
    String getStateNumber();
    String getVinCode();
    String getChassisNumber();
    String getBodyNumber();
    String getCertificateNumber();
    LocalDate getCertificateIssuedDate();
    String getPassportNumber();
    LocalDate getPassportIssuedDate();
    String getBrandByPassport();
    String getModelByPassport();
    String getBodyColor();
    String getTelematicsIMEI();
    String getTelematicsTitle();
    LocalDate getExploitationStart();
    LocalDate getExploitationEnd();
    int getCurrentMileage();
    String getStatus();
    int getYear();
    String getVehicleType();
    String getLocationAddress();
    String getParkingAddress();
    String getComment();
    String getModelTitle();
    String getBrandTitle();
    String getCategoryTitle();
    String getManufacturer();
    String getEcologicalClass();
    int getEnginePower();
    String getEngineTypeTitle();
    int getEngineCapacity();
    int getFuelTankVolume();
    String getFuelTypeTitle();
    String getDriveTitle();
    boolean getMudguardInstalled();
    boolean getSpareWheelHolderInstalled();
    int getWeight();
    int getMaxWeight();
    int getHeight();
    int getWidth();
    int getLength();
    int getServiceIntervalDays();
    int getServiceIntervalMileage();
    int getServiceAuthorizationDays();
    int getServiceAuthorizationMileage();
    String getBodyTypeTitle();
    String getTransmissionTypeTitle();
    String getFrontWheelSizeTitle();
    String getRearWheelSizeTitle();
    int getYearManufactureBegin();
    Integer getYearManufactureEnd();
    BigDecimal getCityConsumptionRate();
    BigDecimal getCountryConsumptionRate();
    BigDecimal getHybridConsumptionRate();
    String getAccessiblePositionTitle();
    String getBalanceUnitNumber();
    String getFacility();
    String getEquipmentUnitSystemNumber();

    void setInventoryNumber(String value);
    void setAssetNumber(String value);
    void setOfficialName(String value);
    void setDepartmentName(String value);
    void setTypeTitle(String value);
    void setSubtypeTitle(String value);
    void setStateNumber(String value);
    void setVinCode(String value);
    void setChassisNumber(String value);
    void setBodyNumber(String value);
    void setCertificateNumber(String value);
    void setCertificateIssuedDate(LocalDate value);
    void setPassportNumber(String value);
    void setPassportIssuedDate(LocalDate value);
    void setBrandByPassport(String value);
    void setModelByPassport(String value);
    void setBodyColor(String value);
    void setTelematicsIMEI(String value);
    void setTelematicsTitle(String value);
    void setExploitationStart(LocalDate value);
    void setExploitationEnd(LocalDate value);
    void setCurrentMileage(Integer value);
    void setStatus(String value);
    void setYear(int value);
    void setVehicleType(String value);
    void setLocationAddress(String value);
    void setParkingAddress(String value);
    void setComment(String value);
    void setModelTitle(String value);
    void setBrandTitle(String value);
    void setCategoryTitle(String value);
    void setManufacturer(String value);
    void setEcologicalClass(String value);
    void setEnginePower(int value);
    void setEngineTypeTitle(String value);
    void setEngineCapacity(int value);
    void setFuelTankVolume(int value);
    void setFuelTypeTitle(String value);
    void setDriveTitle(String value);
    void setMudguardInstalled(Boolean value);
    void setSpareWheelHolderInstalled(Boolean value);
    void setWeight(int value);
    void setMaxWeight(int value);
    void setHeight(int value);
    void setWidth(int value);
    void setLength(int value);
    void setServiceIntervalDays(int value);
    void setServiceIntervalMileage(int value);
    void setServiceAuthorizationDays(int value);
    void setServiceAuthorizationMileage(int value);
    void setBodyTypeTitle(String value);
    void setTransmissionTypeTitle(String value);
    void setFrontWheelSizeTitle(String value);
    void setRearWheelSizeTitle(String value);
    void setYearManufactureBegin(int value);
    void setYearManufactureEnd(Integer value);
    void setCityConsumptionRate(BigDecimal value);
    void setCountryConsumptionRate(BigDecimal value);
    void setHybridConsumptionRate(BigDecimal value);
    void setAccessiblePositionTitle(String value);
    void setBalanceUnitNumber(String value);
    void setFacility(String value);
    void setEquipmentUnitSystemNumber(String value);
}
