export enum TripRequestFields {
  id,
  status,
  approvalState,
  passenger,
  author,
  approvedBy,
  creationTime,
  desiredDate,
  route,
  expectedTime,
  expectedCost,
  expectedDistance,
  passengerCount,
  purpose,
  transportType,
  taxiClass,
  contractor,
  commentary,
  department,
  tripType,
  limitType,
}

export enum TripRequestFieldsTitles {
  id = 'ID поездки',
  status = 'Статус',
  approvalState = 'Статус согласования',
  passenger = 'Пассажир',
  author = 'Создал',
  approvedBy = 'Согласующий',
  creationTime = 'Дата создания',
  desiredDate = 'Дата поездки',
  route = 'Маршрут',
  expectedTime = 'Предварительная длительность',
  expectedCost = 'Предварительная cтоимость',
  expectedDistance = 'Предварительная дальность',
  passengerCount = 'Количество пассажиров',
  purpose = 'Цель',
  transportType = 'Вид транспорта',
  taxiClass = 'Класс такси',
  contractor = 'Перевозчик',
  commentary = 'Комментарий',
  commentForPurpose = 'Комментарий к цели поездки',
  department = 'Подразделение',
  tripType = 'Тип поездки',
  limitType = 'Тип лимита',
  preferences = 'Предпочтения',
  restOfLimit = 'Остаток по лимиту',
  totalTripDuration = 'Общая продолжительность поездки',
  totalTripDistance = 'Общее расстояние поездки',
  totalTripCost = 'Итоговая сумма поездки',
}

export enum TripTypes {
  single = 'Индивидуальная',
  shared = 'Совместная',
}
